### ISSUE TITLE
pubsub.getTopics() returns topics that throw error on topic.delete()

### ISSUE THREAD

**Issue by chrishiestand** [GoogleCloudPlatform/gcloud-node#1005]
This is a problem in gcloud@0.26.0 and 0.25.0; v0.24.1 does not reproduce the problem. Tested with node v4 LTS.

The problem is that topics returned by pubsub.getTopics() are somehow constructed differently than pubsub.createTopic() - in that eventually the former uses an invalid url when topic.delete() is called.

It tries to send an api request to e.g. path: `/v1/projects/projectname/topics/projects/projectname/topics/delme_704317`

note the duplicated path portions.

See this for a reproducible test project:
https://github.com/chrishiestand/gcloud-node-pubsub-topic-bug

to reproduce:
just `git clone`, `npm install`, `export GCLOUD_PROJECT=$project`, and `node index.js`

**Comment by jgeewax** [comment]
Thanks for the super thorough report :) This is awesome. /cc @stephenplusplus

**Comment by stephenplusplus** [comment]
Great report, indeed! Sorry you ran into this. I'll look it over in a little bit and try to squash it for good and put out a patch release.

**Comment by stephenplusplus** [comment]
PR sent in #1008.

**Comment by chrishiestand** [comment]
Thanks for the quick turnaround!
