### ISSUE TITLE
upload file throw Not Found error

### ISSUE THREAD

**Issue by leibale** [GoogleCloudPlatform/gcloud-node#1013]
```javascript
fs.createWriteStream('path').pipe(bucket.file('path').createWriteStream({
  resumable: true
})).on('error', function (err) {
  // err = Not Found
});
```
when i send `resumable: true` or without `resumable` (the default is true) i get `Not Found` error on most of the files.
and when i send `resumable: false` i get the error less times, but still get it.

**Comment by stephenplusplus** [comment]
I'm confused where the "Not Found" is coming from. If you're writing to a file, it's not required to exist, so it must be some other API call that's going off. Can you give us the log of the error?

```js
on('error', function(err) {
  err.response.toJSON(); // < this
})
```

**Comment by stephenplusplus** [comment]
@leibale still happening?

**Comment by leibale** [comment]
I will check for you as sun as possible

**Comment by leibale** [comment]
I will check for you asap

**Comment by leibale** [comment]
@stephenplusplus you can close

**Comment by stephenplusplus** [comment]
Glad it's resolved!
