### ISSUE TITLE
ApiError: Insufficient Permission even when the same API wrote the file to Storage

### ISSUE THREAD

**Issue by ajpyoung** [GoogleCloudPlatform/gcloud-node#1017]
I'm at a loss here. My node code successfully uploaded files to gcloud Storage but can't seem to make the file public or even change the acl.

The error returned is
```
{ [ApiError: Insufficient Permission]
errors:
 [ { domain: 'global',
     reason: 'insufficientPermissions',
     message: 'Insufficient Permission' } ],
code: 403,
message: 'Insufficient Permission',
response: undefined }
```
Here's my code

```javascript
var gcs = GLOBAL.gcloud.storage();
var bucket = gcs.bucket(GLOBAL.storage_names.products);
var file = bucket.file('images/'+targetValue+'_'+filename);
stdout.pipe(file.createWriteStream())
  .on('error', function(err) {
    var msg = {
      "status":"Error"
      "err":err
    };
    console.log(msg);
    
  })
  .on('finish', function() {
    // The file upload is complete.
    console.log("Successfully uploaded "+targetValue+'_'+filename);
    file.acl.add({
      entity: 'allUsers',
      role: gcs.acl.READER_ROLE
    }, function(err, aclObject) {

      if(err==null)
      {
        //stream upload file
        file.makePublic();
      }else{
        console.log("ERROR in ACL Adding");
        console.log(err)
      }
      
    });
    file.makePublic(function(err, apiResponse) {
      if(err==null)
      {
        console.log("File made public");
      }else{
        console.log("make public error");
        console.log(err);
      }
    });
  });
```

**Comment by stephenplusplus** [comment]
It looks like the only way it's working for me is when I provide a `keyFilename` path to a service account key file. I was able to reproduce the error when trying to update the ACL as an authenticated user.

@jgeewax is this intentional, or is something off here?

**Comment by ajpyoung** [comment]
One note though, this error was in the Compute Engine environment and not in the app engine environment

**Comment by ajpyoung** [comment]
I did an experiment where I set the bucket allUsers as owner. Used the same program to upload pictures to the bucket and change the permissions through Compute Engine and the same error happened

**Comment by stephenplusplus** [comment]
(Attaching the SO thread: http://stackoverflow.com/questions/34235381/gcloud-apierror-insufficient-permission-even-when-the-same-api-wrote-the-file-t)

@jonparrott - any tips for this one?

**Comment by jonparrott** [comment]
@ajpyoung can you share with me your compute engine instance's scopes? run `gcloud compute instances describe your-instance-name` and the scopes should be listed under the `serviceAccounts` section.

**Comment by ajpyoung** [comment]
@stephenplusplus - the link you posted was written by me.
@jonparrott - sure... I hope this is what your looking for
```
serviceAccounts:
- email: 645996826377-compute@developer.gserviceaccount.com
  scopes:
  - https://www.googleapis.com/auth/cloud-platform
status: RUNNING
```

**Comment by stephenplusplus** [comment]
@ajpyoung I know :) It's helpful to link all of the places you post an issue.

**Comment by jonparrott** [comment]
@ajpyoung can you try with a new instance that has both `cloud_platform` and `devstorage.full_control`?

**Comment by ajpyoung** [comment]
@jonparrott - umm, sorry for asking this but how do I do that? I'm on the Google Cloud dashboard, clicked on Compute Engine and clicked on VM Instance and then New Instance. 

Add tags and firewall rules to allow specific network traffic from the Internet
>>Allow HTTP traffic
Allow HTTPS traffic
>>>Project access
>>Allow API access to all Google Cloud services in the same project.

How do I activate devstorage.full_control?

**Comment by jonparrott** [comment]
> sorry for asking

You don't have to apologize. :)

I seems you can no longer do this easily in the UI, so here's the command line to do it:

    gcloud compute instances create instance-name --scopes "https://www.googleapis.com/auth/devstorage.full_control","cloud-platform"

**Comment by ajpyoung** [comment]
@jonparrott - sorry for the delayed response, I've been busy writing technical papers for a Patent for the company I work for. Thank you for your help, I'll do execute this process ASAP and reply before the week ends. Again my apologies for my tardiness in replying and thank you for your assistance in this.

**Comment by jonparrott** [comment]
No worries. :) I will be on vacation until 2016 so I may not be able to
review your response quickly.

**Comment by stephenplusplus** [comment]
@ajpyoung happy new year! :tada: Just doing a little issue cleaning, are there any updates for how this one is progressing?
