### ISSUE TITLE
Authentication page needs to be updated to reflect the new Credentials UI

### ISSUE THREAD

**Issue by vsubramani** [GoogleCloudPlatform/gcloud-node#1018]
The Credentials UI in Google Developers Console has been updated. Some of the things to be updated:

- The nav hierarchy has changed. The phrases are different, but still recognizable with the old hierarchy.
- New credentials wizard has been added to help guide the users to the right credential type.

Please update the Getting Started -> Authentication in gcloud-node to reflect these changes.

**Comment by stephenplusplus** [comment]
Thanks for bringing this up. I just merged https://github.com/GoogleCloudPlatform/gcloud-common/pull/37, so our site is updated as well.
