### ISSUE TITLE
Need example using compositeFilter

### ISSUE THREAD

**Issue by bradabrams** [GoogleCloudPlatform/gcloud-node#1019]
Given a set of keys, I'd like to return in one batch all the entities with those keys.  Looks like compositeFilter might be the way to go, but I can't figure out how to use them with gcloud-node.. any suggestions or docs for this?

https://cloud.google.com/datastore/docs/concepts/queries#Datastore_Filters

**Comment by stephenplusplus** [comment]
We have [`dataset.get()`](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.26.0/datastore/dataset?method=get) which can take an array of keys and return the entities that match.

For queries, you can use filters: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.26.0/datastore/query?method=filter, which are formatted into one compositeFilter when the API request is made.

Are either of those what you're looking for?

// @pcostell

**Comment by bradabrams** [comment]
Perfect -- thanks. I somehow missed that in the docs

**Comment by jgeewax** [comment]
Cool - closing this out. Feel free to re-open if you have any ideas of how to improve the docs :)
