### ISSUE TITLE
keyFileName relies on .json suffix to parse correctly

### ISSUE THREAD

**Issue by yonah-codefresh** [GoogleCloudPlatform/gcloud-node#1021]
We ran into a very perplexing issue.
Our code suddenly started throwing:
"Error: email is required."
Assuming we missed some api change we added an email configuration property and hit the following error:
"Error: error:0906D06C:PEM routines:PEM_read_bio:no start line"
That error led us to issue #261 after which I double checked our service key files which were fine.
Long story short, our key file did not have a suffix of .json so it was apparently parsed as a PEM file.
I suggest either better parsing heuristics or else an explicit error if the key file name doesn't end in .json, .pem, or .p12

**Comment by stephenplusplus** [comment]
Thanks for reporting. This is an issue with another library: [gtoken](http://gitnpm.com/gtoken). I opened your issue there: https://github.com/ryanseys/node-gtoken/issues/5
