### ISSUE TITLE
Add more detailed overview section for Logging API

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#1024]
It'd be nice if we could add some more detail to the overview section of the docs on cloud logging. Key things to think about ...

- What are Sinks? What are Logs?
- What's are the 3 most common use cases for cloud logging? Let's make sure we have short snippets for those three.

(Added per comment in #865 )

**Comment by stephenplusplus** [comment]
#1084 will track our progress on updating the overviews for all of our APIs, so I'll close this one.
