### ISSUE TITLE
Cloud Datastore 'Index Not Found' error somewhat obscure

### ISSUE THREAD

**Issue by OverclockedTim** [GoogleCloudPlatform/gcloud-node#1030]
Using the gcloud-node library to do a query that cannot be fulfilled due to lack of indexing produces the obscure error 412, Precondition Failed error:

{ "code":412,"message":"Precondition Failed",...}

A FAQ or troubleshooting doc would be helpful, as would simply including a bit more information in the error itself.  Something along the lines of "Precondition Failed: The request index <index> required for this query is not found. To enable this query, please add it by <instructions/url-to-instructions/etc>

The Java Appengine version of this error message is extremely helpful and includes both the root cause of the error and instructions on how to create an appropriate index.

**Comment by stephenplusplus** [comment]
Thanks for the feedback! I just recently had the same thought: https://github.com/GoogleCloudPlatform/gcloud-node/issues/1016#issuecomment-164496987

When we return an error, if the response body is a string, we can append that to the error message that we return.

Before:
```js
console.log(error);
// Precondition Failed
```

After:
```js
console.log(error);
// Precondition Failed - no matching index found.
```

**Comment by stephenplusplus** [comment]
@callmehiphop is this a weird or good plan?

**Comment by callmehiphop** [comment]
It sounds like a good plan to me, what reasoning would make it weird?
