### ISSUE TITLE
Urgent: The specified key does not exist

### ISSUE THREAD

**Issue by wahengchang** [GoogleCloudPlatform/gcloud-node#1037]
What I do is upload file to bucket, and make public link. 
it work fine when I run my local nodejs host, upload succesed, make public link and able to download, however when I deploy to my nodejs hosting (Leancloud, something like Heroku) the error message was showed.

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

================

I am sure that the json file is in the root of the folder, and the "storage" is set.

```
var storage = gcloud.storage({
  keyFilename:  
  projectId: 
});
```

================

it works fine in local nodejs host `http://localhost:3000/#/upload` but not `http://mywebsite/#/upload`

================

and formidable is used to do the file handling

**Comment by stephenplusplus** [comment]
Can you show the code you're using and point out which part returns the error?

**Comment by stephenplusplus** [comment]
Browse some of these results for the error code and see if any strike some ideas: https://www.google.com/search?q=nosuchkey+google

It basically means the filename you're trying to download doesn't exist, so I'm wondering if it's an issue of escaping any special characters in the file name. Our library handles this already, though. And the fact it works locally but not when deployed doesn't give me any clarity on the issue either.

My only thought without seeing your code is maybe you're providing an already URI-escaped filename to this library and we are re-escaping it.

**Comment by wahengchang** [comment]
hi, stephen, thanks for your reply, my problem is solved. 

my project is hosted on "Leancloud", for some reason the service_key.json was not deployed and there is not error msg was showed, so I through it was a problem of the API. You are right the file is not either uploaded of makepublic.

Now, I have moved the project to Heroku, another nodejs hosting and it run well.

**Comment by stephenplusplus** [comment]
Oh, interesting. Glad it's resolved!
