### ISSUE TITLE
Enable Logging tests for Travis

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#1038]
RE: https://github.com/GoogleCloudPlatform/gcloud-node/pull/865#issuecomment-158101658

Currently, Travis is skipping these system tests because it can't auth as a user:

```
Logging
    sinks (user auth operations)
      - should create a sink with a Bucket destination
      - should create a sink with a Dataset destination
      - should create a sink with a Topic destination
      metadata
        - should set metadata
        - should set a filter
      listing sinks
        - should list sinks
        - should list sinks as a stream
        - should get metadata
```

@jgeewax, I think you mentioned there might be a way to auth these requests with a service account?

**Comment by stephenplusplus** [comment]
@jgeewax wdyt?

**Comment by jgeewax** [comment]
I don't have an answer just yet. @rimey - do you happen to know whether we can do logging admin-type operations as a service account?

**Comment by rimey** [comment]
I don't see why not. `gcloud-python` does it.

**Comment by stephenplusplus** [comment]
Cool, looks like things have changed: #1282.
