### ISSUE TITLE
Support App Engine local server

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/gcloud-node#104]
If user is running this client library from GAE context locally, we should turn authorization off and use local server for Datastore operations.

**Comment by jgeewax** [comment]
Possibly related to https://github.com/GoogleCloudPlatform/gcloud-meta/issues/4

**Comment by mstade** [comment]
Out of curiosity, how would this work? Would you have to run `gcloud preview app run .`, meaning you can't easily make use of tooling such as [nodemon]? Is there a way to run a local dev datastore instance by itself, without having to buy into the (a little bit too prescriptive) `gcloud preview app run .` run thing?

[nodemon]: https://github.com/remy/nodemon

**Comment by ryanseys** [comment]
"Should be able to talk to a Datastore local development server."

**Comment by stephenplusplus** [comment]
Custom API endpoints for Datastore can now be configured with `options.apiEndpoint`: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.13.2/datastore/dataset

It's not done automatically, however. Should we follow this plan: https://github.com/GoogleCloudPlatform/gcloud-node/issues/104#issuecomment-53913532 and default to a custom api endpoint of "localhost:8080"? That host and port can be changed per machine, though those are the defaults for a local server.

**Comment by stephenplusplus** [comment]
Ping @jgeewax - I'm stuck.

From `gcloud preview app run .`, how are requests to Google API endpoints authenticated?

\- Possible answer: They're not. You use a different endpoint on a local server that handles that for you.
\- Response: What is that endpoint? Here are the environment variables I have access to from a GAE dev-spun Node.js instance: https://gist.github.com/stephenplusplus/9851606fde29685af8ef

\- Possible answer: You ping a metadata server.
\- Response: Where do I find that? `http://metadata/` doesn't exist.

**Comment by jgeewax** [comment]
With the App Engine SDK (`gcloud preview app run .`) version of Datastore, I don't know if it "speaks" the Cloud Datastore API. When I said "local development server" I meant https://cloud.google.com/datastore/docs/tools/

That server, once running, shouldn't require any special auth -- all we should need is to update some magical environment variables.. So to summarize:

1. Turn on GCD local server (gcd.sh thing...)
1. Set env variables saying "talk to the datastore service at this host and this port"
1. Run my script that uses `require('gcloud')` and it should hit the local dev server

**Comment by stephenplusplus** [comment]
Okay, we can look for the `DATASTORE_HOST` environment variable, and use that as the `apiEndpoint` option sent to `gcloud.datastore.dataset()` if one wasn't already set.
