### ISSUE TITLE
Support Datastore default dataset env var

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#1040]
See https://github.com/GoogleCloudPlatform/gcloud-common/issues/24

We currently support `DATASTORE_HOST`, but not `DATASTORE_DATASET`.

**Comment by stephenplusplus** [comment]
@pcostell will `DATASTORE_DATASET` still be around in v1beta3? Are there other env vars we should look out for?

**Comment by pcostell** [comment]
DATASTORE_DATASET will go away in favor of DATASTORE_PROJECT_ID.

DATASTORE_HOST will go away and become DATASTORE_EMULATOR_HOST. However, it won't include the url scheme.

**Comment by stephenplusplus** [comment]
Thanks!
