### ISSUE TITLE
Error: Invalid request.  The number of bytes uploaded is required to be equal or greater than 262144 , While trying to upload file 

### ISSUE THREAD

**Issue by aneesv** [GoogleCloudPlatform/gcloud-node#1044]
Getting error

`Error: Invalid request.  The number of bytes uploaded is required to be equal or greater than 262144, except for the final request (it's recommended to be the exact multiple of 262144).  The received request contained 229591 bytes, which does not meet this requirement.`
while trying to upload file

**Comment by stephenplusplus** [comment]
Is this reproducible every time? (can you retry the upload?)

Does this occur with other files? What type of file is it? If possible, can you share the file or another one that fails consistently?

**Comment by aneesv** [comment]
@stephenplusplus Its occuring with one particular file 

I have attached error trace

`Error: Invalid request.  The number of bytes uploaded is required to be equal or greater than 262144, except for the final request (it's recommended to be the exact multiple of 262144).  The received request contained 229591 bytes, which does not meet this requirement.
     at Request._callback (/node_modules/gcloud/node_modules/gcs-resumable-upload/index.js:218:25)
     at Request.self.callback (/node_modules/request/request.js:198:22)
     at Request.emit (events.js:110:17)
     at Request.<anonymous> (/node_modules/request/request.js:1082:10)
     at Request.emit (events.js:129:20)
     at IncomingMessage.<anonymous> (/node_modules/request/request.js:1009:12)
     at IncomingMessage.emit (events.js:129:20)
     at _stream_readable.js:908:16
     at process._tickDomainCallback (node.js:381:11)`

**Comment by stephenplusplus** [comment]
Can you show the gcloud-node code you're using?

**Comment by aneesv** [comment]
I am using a wrapper , Code is working perfectly for all files expect one file. I tried reuploading it same error


```js
CloudStorage.prototype.uploadFile = function(localPath,cloudPath,options){
    options = options || {};
    var q = Q.defer();
    cloudPath = this.parseUrl(cloudPath);
    if(!options.destination)
        options.destination = cloudPath.path;
    this.gcs.bucket(cloudPath.bucket).upload(localPath,options,function(err, file) {
        if (!err) {
            q.resolve(file);
        }else{
            q.reject(err);
        }
    });
    return q.promise;
};

CloudStorage.prototype.parseUrl = function(url) {
    if(typeof url !== 'string') {
        throw new Error('only string parameter supported! ');
    }
    url = url.replace('gs://', '');
    var data = {};
    var bits = url.split('/');

    data.bucket = bits.shift();
    data.path = bits.join('/');

    return data;
};

**Comment by stephenplusplus** [comment]
I haven't been able to reproduce using a file of the same size. The library reporting the error is actually [gcs-resumable-upload](http://gitnpm.com/gcs-resumable-upload). It creates/re-uses a JSON file to store the progress of the resumable upload. Can you check `~/.config/configstore/gcloud-node.json` and remove it to see if that solves it?

**Comment by aneesv** [comment]
@stephenplusplus Thanks it worked ! Between name of file was  `~/.config/configstore/gcs-resumable-upload.json`

**Comment by stephenplusplus** [comment]
Oh, sorry, thanks for correcting. Glad it worked!
