### ISSUE TITLE
Move proto-compatible APIs to grpc

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#1049]
We should migrate our library to use [grpc](https://github.com/grpc/grpc) where possible. These APIs are proto-compatible, thus grpc-ready:

  - [ ] Datastore v1beta3
    - [.proto files](https://github.com/google/googleapis/tree/master/google/datastore/v1beta3)
  - [x] Logging
    - [.proto files](https://github.com/google/googleapis/tree/master/google/logging)
    - [PR](https://github.com/googlecloudplatform/gcloud-node/pull/1134)
  - [x] Pub/Sub v1
    - [.proto file](https://github.com/google/googleapis/tree/master/google/pubsub/v1)
    - [PR](https://github.com/googlecloudplatform/gcloud-node/pull/1070)

**Comment by dhermes** [comment]
:+1:

**Comment by stephenplusplus** [comment]
@tmatsuo is there anything preventing me from testing grpc / a protobuf endpoint for Pub/Sub?

**Comment by tmatsuo** [comment]
You can test it now. I will send instructions to you. Please send an e-mail to tmatsuo@google.com. I will respond with the instructions.
