### ISSUE TITLE
gcloud-node and Openshift

### ISSUE THREAD

**Issue by FredMichel** [GoogleCloudPlatform/gcloud-node#1050]
Hello Team,

I am using the component gcloud-node to access (read/write) Google storage bucket from my node-js application. It works fine when server starts locally (localhost), I am able to upload files within the remote bucket using the below function:
`
 function writeLocalFileToRemoteStorage(localName, remoteName, callback) {
    var localReadStream = fs.createReadStream(localName);
    var remoteWriteStream = bucket.file(remoteName).createWriteStream();
    localReadStream.pipe(remoteWriteStream);
    callback(null, 'OK');
  }
`

However, after pushing the code to my Openshift instance, an exception is raised :
/var/lib/openshift/11abcdefe0000000c8/app-root/runtime/repo/node_modules/mkdirp/index.js:90
                    throw err0;
                          ^
Error: EACCES, permission denied '/var/lib/openshift/11abcdefe0000000c8/.config'

It seems that the component  needs .config folder and it tries to create it. Unfortunately, Openshift denied to write the folder where .config is supposed to be.
How can I fix that issue?
Thank you in advance for your support to help me fix that issue.

**Comment by stephenplusplus** [comment]
Closing since #1051 is this issue with a tiny bit extra :)
