### ISSUE TITLE
Should topic.publish create the topic?

### ISSUE THREAD

**Issue by davidpadbury** [GoogleCloudPlatform/gcloud-node#1052]
In the [README.md](https://github.com/GoogleCloudPlatform/gcloud-node/blob/027a4ba52a29a447c157f76ed7d32b1823ac4f79/README.md#google-cloud-pubsub) docs for pubsub there is a comment which states that calling `publish` on a topic will create the topic if it doesn't already exist.

> var topic = pubsub.topic('my-topic');
>
> // Publish a message to the topic.
> // The topic will be created if it doesn't exist.
> topic.publish({
>   data: 'New message!'
> }, function(err) {});

However trying this code with version 0.27.0 of gcloud-node produces an error reporting a 404.

> { [ApiError: Resource not found (resource=my-topic).]
>  errors: undefined,
>  code: 404,
>  message: 'Resource not found (resource=my-topic).',
>  response: undefined }

Is this a bug, or are the docs just out of date? Happy to help correcting either way.

**Comment by stephenplusplus** [comment]
Thanks for catching this and offering to help! The docs are in fact incorrect. I think if we just remove the incorrect line (``// The topic will be created if it doesn't exist.`) will work. If you're up for a PR, that'd be awesome :)

**Comment by davidpadbury** [comment]
@stephenplusplus no problem. Just created #1053 to resolve.

**Comment by stephenplusplus** [comment]
Resolved in #1053 :+1:
