### ISSUE TITLE
What is Google Cloud Search? link to 404

### ISSUE THREAD

**Issue by allangarcia** [GoogleCloudPlatform/gcloud-node#1054]
The link to "What is Google Cloud Search?" is going to a 404 page. (on https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/search)

**Comment by stephenplusplus** [comment]
Great question. We implemented support for an API that requires whitelisting by Google. As its not generally available yet, the same goes for the docs.

You can request to be whitelisted [here](https://docs.google.com/a/google.com/forms/d/1TshVfwJBP8UoKN-cpjIo4yB6TIiBYrMuxTQQ8LQfPyk/viewform).

@jgeewax any insight into when something public-facing is available so we stop looking crazy? :)

**Comment by jgeewax** [comment]
Unfortunately we will have to keep looking crazy... Maybe we can put an "(alpha)" tag on the API so we look slightly less crazy?

**Comment by allangarcia** [comment]
I don't think that you get me.

1. Go to this link: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/search
2. Click on "What is Google Cloud Search?" (see image)
![screen shot 2016-01-12 at 20 42 59](https://cloud.githubusercontent.com/assets/7458936/12280506/267878da-b96d-11e5-8fed-e941a967c243.png)
3. BUM! Error... 404... please fix it.

**Comment by dhermes** [comment]
> As its not generally available yet, the same goes for the docs.

**Comment by allangarcia** [comment]
Ah! ok.

**Comment by jgeewax** [comment]
Yea, sorry about that :(

It's not just "not generally available" it's actually still "Alpha" ! If you're really excited about it, let me know and I can ask to get you whitelisted (I can't promise the team will say yes, but I can at least ask).

Sorry about the confusion (we had this same question come up with the gcloud-node documentation also).

@dhermes , can we add somewhere in the "This is an alpha release of search" something saying that alpha means it's private, so you'll see 404s if you're not whitelisted" ?

**Comment by stephenplusplus** [comment]
Definitely :+1:
