### ISSUE TITLE
Increase file upload size?

### ISSUE THREAD

**Issue by csaintc** [GoogleCloudPlatform/gcloud-node#1059]
Hey guys,

I'm currently trying to figure out how to increase the currently anemic 1mb file upload size limit, but I can't seem to find it in the documentation anywhere. Please advise!

Thanks a bunch!

**Comment by stephenplusplus** [comment]
@jgeewax is this a limitation at the project level?

**Comment by jgeewax** [comment]
Are you talking about Datastore ? Or Cloud Storage?

For Datastore, there is a hard limit of 1 MB per entity. For Cloud Storage ... there certainly isn't a 1MB limit...

**Comment by csaintc** [comment]
It's cloud storage, and I remember reading somewhere that gcloud-node imposes this limit, not gcloud itself.

Here is the error, I'm on version 0.27.0.
```
error: "Bad Request"
message: "Payload content length greater than maximum allowed: 1048576"
statusCode: 400
```

**Comment by stephenplusplus** [comment]
Our code don't have any such limitation. I'm thinking this is occurring somewhere else in the stack -- is the file being uploaded through the browser? What other libraries are involved?

**Comment by csaintc** [comment]
https://www.google.com/search?btnG=1&pws=0&q=Payload+content+length+greater+than+maximum+allowed%3A+1048576&gws_rd=ssl

hapi config, sorry!

**Comment by stephenplusplus** [comment]
No problem!
