### ISSUE TITLE
Datastore Query toString function should return a description of the query

### ISSUE THREAD

**Issue by krisnye** [GoogleCloudPlatform/gcloud-node#1060]
It should output a description of the ancestors, filters, order, select, limit, offset and any other relevant properties.

**Comment by callmehiphop** [comment]
Would `JSON.stringify` suffice? Queries are just plain old JavaScript objects.

**Comment by callmehiphop** [comment]
@krisnye just checking in! 

Does `JSON.stringify` work for you? If not do you have a specific use case in mind?

**Comment by krisnye** [comment]
JSON.stringify would work.  Was not sure that it was just a plain object.  It's dangerous calling JSON. stringify on objects you're not sure about.

**Comment by stephenplusplus** [comment]
It should be safe, but let us know if you run into problems.
