### ISSUE TITLE
Datastore Query order should use an explicit ascending/descending parameter instead of "-" in a string.

### ISSUE THREAD

**Issue by krisnye** [GoogleCloudPlatform/gcloud-node#1061]
Currently:

    // Sort by size ascendingly.
    var companiesAscending = companyQuery.order('size');

    // Sort by size descendingly.
    var companiesDescending = companyQuery.order('-size');

This is bad.  It is mixing the properties of a string based query language with a json based query API.

Instead, consider just adding a boolean ascending / descending property that defaults to ascending.

    var companiesAscendingImplicit = companyQuery.order('size');
    var companiesAscendingExplicit = companyQuery.order('size', true);
    var companiesDescending = companyQuery.order('-size', false);

**Comment by callmehiphop** [comment]
This seems like a pretty reasonable request, @krisnye. I think there might be a typo in your example and you were going for this..?

```javascript
var companiesDescending = companyQuery.order('size', false);
```

I'm not totally sold on using a boolean, only because at first glance it's not very obvious what it does and it may end up warranting a trip to the docs. I like the idea of separating the two, however I feel that a literal object (probably overkill) or simply passing in an optional sign would be more intuitive.

```javascript
var companiesDescending = companyQuery.order('size', { ascending: false });
var companiesDescending = companyQuery.order('size', '-');
```

@stephenplusplus thoughts?

**Comment by stephenplusplus** [comment]
I prefer the options object.

**Comment by krisnye** [comment]
Yes, I had a typo.  I fixed it.  My honest thoughts are that a JSON based API should have a JSON based query structure.  One that is easy to read and easy to write, while being explicit.

Here is the JSON query structure that I use to represent filters, limits, offsets and sorts.

    { "offset": 20, "limit":100, "where":{ "name": "foo", "age": { ">=": 10} }, "sort": [ { "age": true}, {"name": false} ] }

I actually combine this query format with a TYPE/ID path which captures ancestor searches in order to represent all queries.

Here are some examples.  They are all both REST urls and concise query descriptions:

    /Project/23                 # gets a single entity
    /Project                      # gets all Projects
    /Project?{"limit":50}    # gets first 50 projects
    /Project/23/Task/2      # gets a single descendant entity
    /Project/23/Task?{"where":{"percentComplete":{">=":1,"<=":99"}}     # get all tasks that are in progress

**Comment by stephenplusplus** [comment]
If I was to design the API today, I definitely would have went with that approach as well. I'm not sure why we went with the builder approach. Obviously, at the time, it was thought to be more convenient for the developer. In the end, it's really just a style choice, so to completely change to just a plain JS object now would be an unfair amount of work to put on developers without any clear rewards.

**Comment by krisnye** [comment]
True, but you can build such an object behind the scenes using the builder for backward compatibility and then expose the simpler interface when appropriate.

Something to think about for the future.
