### ISSUE TITLE
Datastore Query filter should use a separate parameter for operator instead of combining field and operator in a single string.

### ISSUE THREAD

**Issue by krisnye** [GoogleCloudPlatform/gcloud-node#1062]
Currently:

    var companyQuery = query
      .filter('name =', 'Google')
      .filter('size <', 400);

Instead, use a separate parameter for operator.  Combining them is weird.  It is more like a text based query language, instead of a JSON based API.

    var companyQuery = query
      .filter('name', '=', 'Google')
      .filter('size', '<', 400);

Later, if desired, this could easily be extended to use declared values for valid operators.

    var companyQuery = query
      .filter('name', query.operator.EQUALS, 'Google')
      .filter('size', query.operator.GREATER_THAN, 400);

I think that final example might be overkill, but at the least, the name and operator should not be combined in a single string.

**Comment by callmehiphop** [comment]
Thanks for the suggestion @krisnye! I think this is a pretty reasonable request.

@stephenplusplus is there a specific reason we do this? We extract the operator from the field name and store them separately, so I'm not sure I understand why we pass them in as a single string.

**Comment by stephenplusplus** [comment]
It was designed before my time. Let's go with the first suggestion.

@krisnye thanks for the suggestion. Are you interested in sending a PR?

**Comment by krisnye** [comment]
Sure, I can do that.  I'll assume we should keep the old behavior when there are only two arguments, correct?
