### ISSUE TITLE
instance-template instance-group not supported?

### ISSUE THREAD

**Issue by q42jaap** [GoogleCloudPlatform/gcloud-node#1071]
I could not find api's for instance-template or instance-groups in compute. I would really like to use it.
Using gcloud command line tool would be a major downside...

**Comment by callmehiphop** [comment]
@q42jaap currently we do not support the InstanceTemplate or InstanceGroup resources, I've opened an issue, #1073, to discuss adding further support for GCE resources.

In the meantime you could checkout the [google-api-nodejs-client](https://github.com/google/google-api-nodejs-client) which I believe does support them.

**Comment by q42jaap** [comment]
Thanks, I will look into that other library.
