### ISSUE TITLE
Improve CONTRIBUTING.md ?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#1072]
PM2 seems to have a really nice guide to contributing. Maybe we can take some guidance from them?

https://github.com/Unitech/PM2/blob/master/CONTRIBUTING.md

**Comment by stephenplusplus** [comment]
It's kinda tricky, cause we have https://github.com/GoogleCloudPlatform/gcloud-common/tree/master/contributing for the generic "How to open an issue", but someone looking at our CONTRIBUTING.md file (as opposed to https://googlecloudplatform.github.io/gcloud-node/#/contributing won't see that).

Maybe we should just have a link back to the gcloud-common file at the top of ours?

**Comment by callmehiphop** [comment]
Should we move this to gcloud-common?

**Comment by jgeewax** [comment]
Yes, and yes.

**Comment by callmehiphop** [comment]
Closing per https://github.com/GoogleCloudPlatform/gcloud-common/issues/50
