### ISSUE TITLE
duplicated information in runQuery docs

### ISSUE THREAD

**Issue by hrovira** [GoogleCloudPlatform/gcloud-node#1074]
https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/datastore/dataset?method=runQuery

the "Parameters" table seems to have dup'd entries for the callback arguments... err, entities, nextQuery, apiResponse, err, entities, nextQuery, apiResponse.

there are slightly different descriptions, so it may have been that the older descriptions did not get deleted.

**Comment by stephenplusplus** [comment]
Oops, we did duplicate these: https://github.com/GoogleCloudPlatform/gcloud-node/blob/v0.27.0/lib/datastore/request.js#L553-L565

Any chance you want to send a PR just removing the extras? The first `nextQuery` and the second `entities` are the good ones.

**Comment by hrovira** [comment]
sorry for the confusion, had to abort 2 PRs, issues with commits... last PR (1080) should be easily merged.

**Comment by stephenplusplus** [comment]
Fixed in 073dd09040b25618e59a64dfe9aa580129e10628.
