### ISSUE TITLE
missing doc page

### ISSUE THREAD

**Issue by hrovira** [GoogleCloudPlatform/gcloud-node#1075]
https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/datastore/entity

**Comment by callmehiphop** [comment]
That page isn't missing, the entity module is only used internally. Was there something you were expecting to see there?

**Comment by callmehiphop** [comment]
Ahh, ok, we link to that page else where in [Datastore docs](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/datastore/dataset?method=get). The page isn't missing, those shouldn't be links.

**Comment by callmehiphop** [comment]
@stephenplusplus do you know where we actually describe the structure of entity objects?

**Comment by stephenplusplus** [comment]
Well, we don't actually have an Entity type. The module (entity.js) is basically just a bunch of conversion methods, used to convert a POJO into an object the API understands. When it gets back to the user, it's just whatever object they associated with a key.

Anywhere we document a `module:datastore/entity` being returned, we just need to call it an `object`... [for now](#508).
