### ISSUE TITLE
Missing documentation for entity

### ISSUE THREAD

**Issue by q42jaap** [GoogleCloudPlatform/gcloud-node#1083]
The docs at https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/datastore/dataset?method=get reference the entity type: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/datastore/entity
However, this link does not do anything. I cannot find any of the methods in entity.js in the docs.

**Comment by stephenplusplus** [comment]
Thanks for reporting this! We actually just caught this after it was reported in #1075. The docs will update when we release the next version.
