### ISSUE TITLE
Integrate Logging API with Winston

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#1086]
https://github.com/winstonjs/winston

**Comment by VikramTiwari** [comment]
In past I have used https://github.com/winstonjs/winston-syslog to write logs directly to syslog. But a native integration with Winston will be a great win.

**Comment by JustinBeckwith** [comment]
@matthewloring and I actually have a plan for this one.

**Comment by stephenplusplus** [comment]
Awesome, let me or @callmehiphop know if you need any help.

**Comment by stephenplusplus** [comment]
I've seen this pop up: https://github.com/captiz/winston-googlecloud

@JustinBeckwith did your project ever go public?

**Comment by JustinBeckwith** [comment]
https://github.com/GoogleCloudPlatform/winston-gae is out there, but it only works for App Engine Flex today.  It would be awesome to have a winston transport that worked across the stack.  @matthewloring has already written a fair amount of this code, so we should work together :)

**Comment by stephenplusplus** [comment]
Definitely, feel free to ping me when/wherever there's something I can help with. Maybe we can even make our Logging API here better in the process!
