### ISSUE TITLE
Difference with new subscription callback vs object

### ISSUE THREAD

**Issue by thesandlord** [GoogleCloudPlatform/gcloud-node#1088]
There is a weird difference between the callback 'subscribe' method and the 'subscription' object that does not make sense.

I would expect these two snippets to act the same way

```javascript
topic.subscribe('new-subscription', function(err, subscription) {
  subscription.on('message', function(message){
    console.log(message.data);
  }
});
```

```javascript
var subscription = topic.subscription('new-subscription');
subscription.on('message', function(message){
    console.log(message.data);
}
```

However, the first one creates a subscription, but crashes if the subscription already exists.
The second one does not create a subscription, but works on pre-existing subscriptions.

So, I had to write this workaround code

```javascript
var subscription = topic.subscription('new-subscription');
subscription.exists(function(err, exists) {
  if (!exists){
    subscription.create(function(err, subscription, apiResponse) {
        if (!err) {
          subscription.on('message', function(message){
            console.log(message.data);
          });
       }
    });
  }
});
```

I really wish both of the first two examples automatically made the subscription AND worked on pre-existing subscriptions. Right now, it feels like the python API (check for the subscription, if it does not exist create it), but the callback hell is not good.

**Comment by stephenplusplus** [comment]
If you don't know if a subscription exists, you can write:

```js
var subscription = topic.subscription('new-subscription');

subscription.get({ autoCreate: true }, function(err, subscription) {
  subscription.on('message', function(message) {
    console.log(message.data);
  });
});
```

(`get` docs: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/pubsub/subscription?method=get)

**Comment by thesandlord** [comment]
(Just realized my workaround is a bit wrong, but the actual code would be even more complicated
