### ISSUE TITLE
Storing a long string throws an error

### ISSUE THREAD

**Issue by nikhilbobb** [GoogleCloudPlatform/gcloud-node#1091]
Storing a string longer than 1500 bytes in the datastore throws an error. Is there a way to store it as an instance of Text (the long string type referenced in the python docs)?

**Comment by stephenplusplus** [comment]
> (the long string type referenced in the python docs)?

Link: https://cloud.google.com/appengine/docs/python/datastore/typesandpropertyclasses?hl=en#TextProperty

@pcostell anything we can do here to support longer strings?

**Comment by nikhilbobb** [comment]
yes, that is the one. I realize as a workaround I can choose not to index those strings, but ideally I would like to do so.

**Comment by pcostell** [comment]
You can do this in gcloud-node by writing a `string_value` and setting `excludeFromIndexes=true`. This will let you write a string up to 1MB (minus overhead since this is also the Entity size limit).

**Comment by nikhilbobb** [comment]
Thanks!
