### ISSUE TITLE
Datastore client not getting ProjectID from env 

### ISSUE THREAD

**Issue by thesandlord** [GoogleCloudPlatform/gcloud-node#1092]
It looks like Datastore client is not getting the projectID from the env automatically.

```javascript
var pubsub = gcloud.pubsub();
```
This works fine, but:

```javascript
var dataset = gcloud.datastore.dataset();
```
returns:
```
Error: Sorry, we cannot connect to Google Cloud Services without a project ID. You may specify one with an environment variable named "GCLOUD_PROJECT". See https://googlecloudplatform.github.io/gcloud-node/#/authentication for a detailed guide on creating an authenticated connection.
```
This fixes the problem
```javascript
var dataset = gcloud.datastore.dataset({projectId: process.env.GCLOUD_PROJECT});
```

**Comment by stephenplusplus** [comment]
Good catch, thanks for letting us know. PR incoming!

**Comment by thesandlord** [comment]
im not sure if other clients also have this problem. I though they all extend the same base class?

**Comment by stephenplusplus** [comment]
I checked, all of the other APIs do it.

@callmehiphop can you think of a way we can move the normalizing to the Service constructor?

**Comment by callmehiphop** [comment]
@stephenplusplus we should be able to just normalize them in the Service constructor, no?

**Comment by stephenplusplus** [comment]
I think there might be an issue with double-instantion?

**Comment by callmehiphop** [comment]
`Service.call(...)` only gets called once IIRC - after a service class as been instantiated.. right?

**Comment by stephenplusplus** [comment]
Using this as an example: https://github.com/GoogleCloudPlatform/gcloud-node/blob/30817fcc10195da0136baefeb38b225986fb1c7e/lib/storage/index.js#L87-L90

```js
if (!(this instanceof Storage)) {
  options = util.normalizeArguments(this, options);
  return new Storage(options);
}
```

Why do we only normalize if it's not an instance of Storage?

**Comment by stephenplusplus** [comment]
Related: https://github.com/GoogleCloudPlatform/gcloud-node/pull/845#discussion_r38926943

**Comment by callmehiphop** [comment]
> Why do we only normalize if it's not an instance of Storage?

If the current context is not an instance of a service (e.g. `Storage`), that implies that the context is probably `gcloud`, which is where [we store global config](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/index.js#L429).

**Comment by stephenplusplus** [comment]
So I'm wondering, since we only normalize under that condition, how do we move that logic to the Service constructor?

**Comment by callmehiphop** [comment]
> So I'm wondering, since we only normalize under that condition, how do we move that logic to the Service constructor?

Ahh right, not sure if there's a way around that.. we might have to re-think things a little bit if we want to try and refactor that logic into the `Service` class.

**Comment by stephenplusplus** [comment]
Should we just leave it?

**Comment by callmehiphop** [comment]
Might be a good idea for now?
