### ISSUE TITLE
Could Compute operation emit 'running' event?

### ISSUE THREAD

**Issue by tgknight** [GoogleCloudPlatform/gcloud-node#1109]
It seems that the operation object can only emit 'complete' and 'error' events. I think it would be great if the object could also emit 'running' or similar event that indicate the 'RUNNING' status in all Operation resources.  
A use case example for that feature is to show users that the instance is in the process of creation. It can be done manually by the method similar to[`Operation.prototype.startPolling_`](https://github.com/GoogleCloudPlatform/gcloud-node/blob/v0.27.0/lib/compute/operation.js#252) but since there already is the function for that job, it should not be re-implemented.

**Comment by stephenplusplus** [comment]
How about progress events?

```js
operation.on('progress', function(progress, metadata) {
  // progress = 80;

  // metadata = {
  //   kind: 'compute#operation',
  //   id: '...',
  //   status: 'RUNNING',
  //   progress: 80,
  //   ...
  // };
});
```

**Comment by tgknight** [comment]
It sounds great! It will be much easier to implement progress tracking feature with 'progress' event.  
Thank you for your fast response.
