### ISSUE TITLE
Link to Pub/Sub API Docs from README goes to empty page and starts an endless 404 loop

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/gcloud-node#1112]
The [API docs page](https://googlecloudplatform.github.io/gcloud-node/#/docs/storage) linked to from the [README](https://github.com/GoogleCloudPlatform/gcloud-node#google-cloud-pubsub) is blank.

If you view the dev console from this page, you'll see it spews out 404 errors:

`https://googlecloudplatform.github.io/gcloud-node/json/storage/index.json Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by stephenplusplus** [comment]
Ooh, thanks for reporting. @callmehiphop do we have a catch-all route on the docs site?

**Comment by callmehiphop** [comment]
We do, but the issue here is that the README links omit the version (rightfully so) and I didn't include logic to check for that. I made a two small PRs to fix this.

**Comment by callmehiphop** [comment]
Thanks @jasonpolites! This should now be resolved per https://github.com/GoogleCloudPlatform/gcloud-common/pull/71
