### ISSUE TITLE
[Feature Request] Authorize using oAuth tokens

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/gcloud-node#1117]
Currently the authorization for gcloud-code is [done via a service account](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/guides/authentication) but it would be great if the client could be authorized via an oAuth token as an alternative.

This would make it easy to quickly iterate on solutions, and also share solutions with other people without needing to pass around keys etc.

For example, the [quickstart.js](https://developers.google.com/gmail/api/quickstart/nodejs) guide for the Gmail API materializes an oAuth token with a given scope.  It would be simple to add GCP scopes to this so I could re-use the one auth token to talk to both GMail and GCP resources (one using googleapis and one using gcloud)

This would mean I could create a snippet of code that depends on certain scopes and share that code with anyone else without them needing to create a service account to execute the code.

**Comment by stephenplusplus** [comment]
Do you mean literally a token string or a json file (from the guide, `client_secret.json`)?

**Comment by jasonpolites** [comment]
I would think the preferred option would be an in-memory value.  Developers can then immediately authorize gcloud from an oAuth dance, and if they want to store the token they can do that but they'll have to store/load it themselves (they may want to store it somewhere other than local file system, so I think just having a String value makes the most sense)

**Comment by stephenplusplus** [comment]
Sounds good to me!

@jgeewax should we move this to gcloud-common so other languages can support this style of auth?

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/gcloud-common#76
