### ISSUE TITLE
Add a spell checker to our lint task

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#1127]
Cont'd from https://github.com/GoogleCloudPlatform/gcloud-node/pull/1126#issuecomment-183034508

We have words written all over the place that might not be correct grammatically.

@callmehiphop found a tool called [write-good](https://github.com/btford/write-good) which we could add to our link task to catch such non-good writings. We would likely need a spell-checker as well, because it doesn't seem to do that.

We'd have to be precise in steering it only towards words and away from code. Sometimes they are mixed, such as our `@example`s. @callmehiphop, is there a good way to filter out only the text?

**Comment by callmehiphop** [comment]
We could generate the JSON and run spellcheck/write-good on the description properties throughout? I think the trickier part will be parsing markdown and skipping code snippets and possibly markdown syntax.

**Comment by stephenplusplus** [comment]
Ooh! https://github.com/wooorm/strip-markdown

**Comment by callmehiphop** [comment]
Nice!

**Comment by stephenplusplus** [comment]
I started to work on this and it seemed to be destined for failure from the start. I think the problem is we're trying to spell check tech sentences.

I started by plugging in `write-good`. It's is a great tool, but in practicality, it might be more detailed than we need. So I scaled back the scope and just went for spell checking. I realized quickly that meant we'd need to have an extensive custom dictionary to define things like "SDK", "gcloud", "getFiles", etc.

At this point, I'm not sure we'll be able to automate this. We might be better off just letting the users catch and contribute any grammar bugs we let seep through.

**Comment by callmehiphop** [comment]
That sounds good to me

**Comment by stephenplusplus** [comment]
:+1:

**Comment by jgeewax** [comment]
Would it be crazy to have it run and trigger just a warning? Or is it just
way too noisy?

**Comment by stephenplusplus** [comment]
I think I found a way that's not too gross!: #1166
