### ISSUE TITLE
ApiError errors field is alway [] during a failed save to datastore

### ISSUE THREAD

**Issue by firemuzzy** [GoogleCloudPlatform/gcloud-node#1128]
On preforming a duplicate insert the datastore normally returns
 
`{
  "error": {
    "errors": [
     {
       "domain": "global",
       "reason": "INVALID_ARGUMENT",
       "message": "entity already exists"
     }
    ],
    "code": 400,
    "message": "entity already exists"
  }
}`

but instead 'errors' in the ApiError are an []
**Is this intentional?**

From some digging around, the problem is in `lib/datastore/request.js` 
line 813 creates the request 

`813: ...  request(authenticatedReqOpts, function(err, resp, body)`

The value of `body` is already the expected json error message. 
On 'line 819' `util.parseHttpRespMessage(resp)` sets `parsedResp` with ApiError with [] for errors. 
The callback is called and `body` param with the nicely formatted error is lost.

The 'message' field is filled but it has the stringified error which would require re-parsing
`Bad Request - {
  "error": {
    "errors": [
     {
       "domain": "global",
       "reason": "INVALID_ARGUMENT",
       "message": "entity already exists"
     }
    ],
    "code": 400,
    "message": "entity already exists"
  }
}`

**Comment by stephenplusplus** [comment]
I was able to reproduce up until:

```
Bad Request - { "error": { "errors": [ { "domain": "global", "reason": "INVALID_ARGUMENT", "message": "entity already exists" } ], "code": 400, "message": "entity already exists" } }
```

When I `console.log(error.message)` I get:

```Bad Request - entity already exists: app: &quot;s~nth-circlet-705&quot;
path &lt;
  Element {
    type: &quot;Kind&quot;
    id: 1
  }
&gt;
```

My tests are from version 0.28. We have made some changes with how errors are parsed (#1030, #1048). Which version are you running?

**Comment by firemuzzy** [comment]
Thanks for taking a look. Am running 0.28 but against the local gcd.sh store. Switched it to the cloud and now I getting the same message as you are.

**Comment by stephenplusplus** [comment]
I reproduced using the local Datastore server as well. I put together a PR: #1130. Feel free to try the branch to see if the error is more aligned with what you'd expect:

```js
$ npm install --save stephenplusplus/gcloud-node#1128
```
