### ISSUE TITLE
Datastore NodeJS API's query.select([]) is not working

### ISSUE THREAD

**Issue by janaaronlee** [GoogleCloudPlatform/gcloud-node#1139]
query.select('title') works.

query.select(['title', 'author']) as the documentation suggests, returns nothing.

**Comment by stephenplusplus** [comment]
Are you getting an error?

**Comment by janaaronlee** [comment]
Actually, no. No errors. So I have nothing much to post. I moved on a bit to a different part of my app. I can post more concrete stuff later. But basically, like I already said, query.select('title') works and returns the expected result. But when I switch it out to query.select(['title', 'author']), nothing is returned (no errors, no data).

Feel free to close this if you feel that there is nothing much to go on. I can re-open it or something when I encounter the issue again.

**Comment by stephenplusplus** [comment]
We have a test that uses select with an array (https://github.com/GoogleCloudPlatform/gcloud-node/blob/4a862bd7bd503120cb1e1716054511d1f24c4abc/system-test/datastore.js#L418), and it's working here.

I will close, but please re-open if there's more we can dig into.
