### ISSUE TITLE
Resumable upload for BigQuery data import

### ISSUE THREAD

**Issue by dwsupplee** [GoogleCloudPlatform/gcloud-node#1143]
It looks as though the bigquery api supports [resumable upload](https://cloud.google.com/bigquery/loading-data-post-request#resumable), but there is only a resumable upload module built for storage.

This may be enough, given that you can import data to bigquery from storage, but I just wanted to check in and see if it made sense to include resumable upload support directly for bigquery as well.

**Comment by stephenplusplus** [comment]
I think the Storage -> BigQuery import is a better alternative here. Resumable uploads come with a lot of overhead in the implementation as well as on the user-- persisting a config file is unexpected.

Anyone feel free to discuss and re-open if this is something we need to support.

**Comment by jscinoz** [comment]
Is there any reason that this can't be done under the hood as part of table.createWriteStream from the Bigquery module, just as it's done for file.createWriteStream in the GCS module?
