### ISSUE TITLE
Add Cloud Vision API

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/gcloud-node#1144]
The Google Cloud Vision API recently went to beta.  It would be great to add API support:
https://cloud.google.com/vision/docs/

There's an existing NPM module here:
https://github.com/tejitak/node-cloud-vision-api

**Comment by stephenplusplus** [comment]
Check it out! https://github.com/GoogleCloudPlatform/gcloud-node/pull/1136 :)

**Comment by JustinBeckwith** [comment]
Great to see this coming along!
