### ISSUE TITLE
storage.channel stop request has invalid URL

### ISSUE THREAD

**Issue by AVVS** [GoogleCloudPlatform/gcloud-node#1145]
channel id is used to construct request URI, and always results in 404 (gsutil has the same bug btw),

ie it should be: `https://www.googleapis.com/storage/v1/channels/stop` instead of `https://www.googleapis.com/storage/v1/channels/channel-name/stop`

this can be temporarily fixed with (since there is only 1 method for .channel, which is `.stop` - there are no checks on the interceptor

```js
channel.interceptors.push({
  request: (requestOptions) => {
    requestOptions.uri = requestOptions.uri.replace(`${channel}/`, '');
    return requestOptions;
  },
});
```

**Comment by stephenplusplus** [comment]
Thanks for reporting! Sent a fix in #1146 -- feel free to try it out to make sure it works as intended.
