### ISSUE TITLE
Where's the "edit on github" button for our docs?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#1148]
https://googlecloudplatform.github.io/gcloud-node/#/docs/master/datastore Doesn't have the button

However https://googlecloudplatform.github.io/gcloud-node/#/docs/master/guides/authentication does?

**Comment by callmehiphop** [comment]
Could be wrong, but I think only markdown driven pages (auth, contrib, etc.) have ever had an "Edit on GitHub" button. @stephenplusplus is that correct?

We do have a link to the "Source code" for every method, however it's not quite as obvious. Should be a fairly small task to support this though.

**Comment by stephenplusplus** [comment]
We just have to figure out what makes it easiest for a user to help us catch bugs on the content on that page. There are multiple source types:

- The overview
- The description
- The parameters
- The examples

From a UI stance, what would make the most sense to convey those sections can be edited; and then when clicking on them, what happens?

Ideas:

- The overview -- On hover, show a pencil icon in the upper right. On click, go to the source code.
- A function/method description -- On hover, show a pencil icon in the upper right. On click, go to the source code.
- The parameters -- Next to each parameter description, on hover, show a pencil... (same as above)
- The examples -- On hover, show a pencil... (same as above)

**Comment by callmehiphop** [comment]
Perhaps we should move this to gcloud-common!

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/gcloud-common#103
