### ISSUE TITLE
Cloud SQL support

### ISSUE THREAD

**Issue by phanect** [GoogleCloudPlatform/gcloud-node#1160]
I want Google Cloud SQL support in Google Cloud Node.js Client.

I know [Google API Client Library supports Cloud SQL API](https://cloud.google.com/sql/docs/admin-api/libraries).
However, if you want to do something to other services supported by Google Cloud Node.js Client (e.g. Compute Engine) you need to authenticate twice and the code gets complex.

I hope if Cloud SQL is supported by Google Cloud Node.js Client, not by Google API Client Library.

**Comment by jgeewax** [comment]
Thanks for the note @phanect ! 

We have it on our list to cover Cloud SQL sometime this year. Any chance you'd be up for contributing ?

**Comment by phanect** [comment]
> We have it on our list to cover Cloud SQL sometime this year.

Great!

> Any chance you'd be up for contributing ?

Year, I'm considering it too, but not sure I have time and energy to do that :P

**Comment by stephenplusplus** [comment]
If you do beat us to it, don't worry about sending an imperfect PR. We're happy to work on these things together :)

**Comment by phanect** [comment]
@stephenplusplus Thank you :)

**Comment by stephenplusplus** [comment]
I've created [API Implementation Tracker](https://github.com/GoogleCloudPlatform/gcloud-node/issues/1338) which I've included this request in. Feel free to subscribe to that issue to stay updated!
