### ISSUE TITLE
Not working under strict mode

### ISSUE THREAD

**Issue by benhk2005** [GoogleCloudPlatform/gcloud-node#1161]
home-0 SyntaxError: Delete of an unqualified identifier in strict mode.
home-0     at exports.runInThisContext (vm.js:53:16)
home-0     at Module._compile (module.js:374:25)
home-0     at Object.Module._extensions..js (module.js:417:10)
home-0     at Module.load (module.js:344:32)
home-0     at Function.Module._load (module.js:301:12)
home-0     at Function._load (/node/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
home-0     at Module.require (module.js:354:17)
home-0     at require (internal/module.js:12:17)
home-0     at Object.<anonymous> (~/node_modules/gcloud/node_modules/google-auto-auth/node_modules/google-auth-library/node_modules/gtoken/node_modules/google-p12-pem/index.js:1:88)
home-0     at Module._compile (module.js:410:26)

**Comment by stephenplusplus** [comment]
Can you put together a sample script I can run to see this error?

**Comment by stephenplusplus** [comment]
Please report back if you can tell us how to reproduce.
