### ISSUE TITLE
Windows maxpath errors 

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/gcloud-node#1162]
Greetings folks!
We've had a few people report problems with our getting started guide over here:
https://code.google.com/p/google-cloud-sdk/issues/detail?id=496

Looking at the error:
ERROR: gcloud crashed (WindowsError): [Error 3] The system cannot find the path specified: 'C:\\Users\\miguel\\AppData\\Local\\Google\\Cloud-SDK\\nodejs-getting-started\\2-structured-data\\node_modules\\gcloud\\node_modules\\gce-images\\node_modules\\google-auto-auth\\node_modules\\google-auth-library\\node_modules\\gtoken\\node_modules\\google-p12-pem\\node_modules\\node-forge'

It looks like a Windows maxpath issue :(  `npm install -g npm@3` usually fixes the problem, but it would be great if there was a better answer.

Is there anything we could do to flatten the dependency graph here a little?

**Comment by stephenplusplus** [comment]
I believe `npm dedupe` even on older versions could provide some aide. We are pretty trapped on this, however. Even if we try to group more of our own code into a single module, we are still victims of what our dependencies choose to do when it comes to *their* dependencies. Windows users are usually pretty aware of this problem from running into it with other libraries, so they're familiar with the available solutions as well.

**Comment by JustinBeckwith** [comment]
Yeah - this is a pretty common issue with NPM and Windows.  I think this is likely just a documentation issue, but I wanted to check in to see if y'all had a magic solution.  For now I'll just recommend 3 options:

1. Install npm@3 if possible
1. Run `npm dedupe` after installation
1. Move files to `c:\` instead of users directory

**Comment by stephenplusplus** [comment]
That sounds right to me. I'll add the same to our Troubleshooting guide.

**Comment by jgeewax** [comment]
Is there any way to automate this deduping? Or catch the error and recommend running dedupe?

**Comment by stephenplusplus** [comment]
npm will dedupe by default if you use version 3 or greater. The app will crash before our code can run, so there's nothing we can do to catch it.

**Comment by Headcult** [comment]
I'm facing the same issue even with NPM v3.9.5. Is there any solution for this? Can this issue be reopened as there is no solution for this so far and none of the workarounds are successful? This is a major blocker issue as this prevents from deploying onto Google Cloud? Any sort of help is highly appreciated. Thank You.

**Comment by Headcult** [comment]
I'm able to get around this issue by deleting 'node_modules' folder before deploying the app. But, the issue still exists if 'node_modules' folder is not deleted. Looking for a permanent solution.

**Comment by Gemasoft** [comment]
I finalized python process and that fixed my problem, it seems it was stuck using the credentials file.
