### ISSUE TITLE
Cannot authenticate using `private_key` and `client_email`

### ISSUE THREAD

**Issue by eduardo-tenorio-guiabolso** [GoogleCloudPlatform/gcloud-node#1173]
I am trying to connect my NodeJS application to Pub/Sub. Since the production environment is in an AWS instance, I cannot use the *default credentials approach*. So, my approach is to pass a credentials object with the private key and the client email:

```node
var gcloud_config = {
    projectId: process.env.GCLOUD_PROJECT_ID,
    credentials: {
        client_email : process.env.GCLOUD_CLIENT_EMAIL,
        private_key : process.env.GCLOUD_PRIVATE_KEY
    }
}
```

According to the [docs](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.29.0/gcloud). This variable is passed as an argument in a class constructor:

```node
constructor(gcloud_config) {
        this.topicName = 'cerebro.TrackeableEvent';

        this.pubsub = gcloud.pubsub(gcloud_config);
        this.topic = this.pubsub.topic(this.topicName);
        this.topic.get({
            autoCreate: true
        }, function(err, data) {
            console.log('PubSubTrackeableEventAPI');
            console.log('err: ' + err);
            console.log('data: ' + data);
        });
    }
```

When I run locally, everything is OK. There is no `err` and I can publish to `this.topicName`. When I run on my staging environment, at AWS, I receive the error **Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.**. I don't know what I am doing wrong. I tried several combinations of the `GCLOUD_PRIVATE_KEY`. With and without the markers **"-----BEGIN PRIVATE KEY-----\n"** and **"\n-----END PRIVATE KEY-----\n"**.

Is this a bug or am I doing something wrong that I don't know?

**Comment by eduardo-tenorio-guiabolso** [comment]
I guess I found the error. Tomorrow I'll check at the office.

**Comment by eduardo-tenorio-guiabolso** [comment]
Changed

```node
private_key : process.env.GCLOUD_PRIVATE_KEY
```

by

```node
private_key : process.env.GCLOUD_PRIVATE_KEY.replace(/\\n/g, '\n')
```

**Comment by andershagebakken** [comment]
@eduardo-tenorio-guiabolso THANK YOU!

**Comment by biozork** [comment]
@eduardo-tenorio-guiabolso I had the same challenge with hosting on Heroku, I needed to store the private key in environment variable, and your fix saved my day (doing the newline .replace on the key)

Thank you so much :)

**Comment by UncertainConstraint** [comment]
@eduardo-tenorio-guiabolso I have been banging my head against a wall trying to figure out how to handle the newline characters, thank you so much for posting your solution, it worked perfectly!

**Comment by kavunshiva** [comment]
(╯°□°）╯︵ ┻━┻

...but yeah, this definitely does the trick. thanks a million!

**Comment by xuan0123** [comment]
SAVED MY LIFE! THANK YOU!

**Comment by mattwelke** [comment]
I'm struggling to understand what this step actually does. When I test this in a small Node.js program with new lines in a string, it appears to return a string that is the exact same.

```nodejs
const contents = `this
is
a
test`;

const replaced = contents.replace(/\\n/g, '\n');

console.log();
```

![image](https://user-images.githubusercontent.com/7719209/170389996-e06dbd37-e85e-417e-8bf3-37ce8f6be9ba.png)
