### ISSUE TITLE
Be able to set default object ACL on GCS upload

### ISSUE THREAD

**Issue by mcdonamp** [GoogleCloudPlatform/gcloud-node#1178]
Currently, there's no way to set the predefined object ACL on an object that is being uploaded (though there is in the [REST API](https://cloud.google.com/storage/docs/json_api/v1/objects/insert)). One can overwrite the metadata with a new ACL, but that is a hard overwrite, and doesn't preserve existing ACLs, unlike add default ACL. It would be neat if we had an API that worked like:

```javascript
var options = {
  predefinedAcl:'publicRead',
  validation: 'crc32',
  metadata: {/* add metadata here */}
};

bucket.upload('local/path/to/bar.txt', options, function(err, file) {
  // File is publicly readable!
});
```

**Comment by stephenplusplus** [comment]
Sounds like a good idea to me!

**Comment by stephenplusplus** [comment]
Sent a PR for this, feel free to test it out!

```sh
$ npm install --save stephenplusplus/gcloud-node#spp--1178
```
