### ISSUE TITLE
Datastore query filter failing on simple indexes

### ISSUE THREAD

**Issue by s4lesman** [GoogleCloudPlatform/gcloud-node#1180]
Hey,

I am trying to query datastore on a single variable (doc_id) and I always get the following error:

```

error:  ApiError: Bad Request - a filter value must be indexed
  at new util.ApiError (/opt/app/api/src/node_modules/gcloud/lib/common/util.js:105:10)

```

The piece of code is coffeescript but I dont think that is a problem to anyone here:

```
datastore = gcloud.datastore.dataset()
query = datastore.createQuery 'subs'
query.filter 'doc_id', '=', object._id
datastore.runQuery query, callback
```

I have already tried to create the index using the CLI but I always get that it is not necessary because its not a complex index and single indexes are automatically created. Does anyone have an idea? 

Thanks

**Comment by stephenplusplus** [comment]
@pcostell

**Comment by pcostell** [comment]
This error occurs in the backend if the query filter's property has `excludeFromIndexes = True`.

 @stephenplusplus any changes to gcloud recently that would set this on query filters?

What's `object._id` in this example?

**Comment by s4lesman** [comment]
@pcostell 

its an hex string.. the particular case was: "56d9ef9f2764e71200083a73"

**Comment by stephenplusplus** [comment]
> any changes to gcloud recently that would set this on query filters?

I don't believe so. We still allow a user to set `excludeFromIndexes` with [`dataset.save`](http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.29.0/datastore/dataset%23save). Did you save data with that option set?

**Comment by s4lesman** [comment]
@stephenplusplus no, I did not use any particular option set. I just set the key and store my json document on data.

**Comment by pcostell** [comment]
It may be helpful to see the actual proto that is getting sent to Datastore. @stephenplusplus do you have instructions for how to grab this from the query?

**Comment by stephenplusplus** [comment]
@s4lesman try running your code against this gcloud:

```js
$ npm install --save stephenplusplus/gcloud-node#spp--1180
```

It will output the format of the query (pre-protobuf encoding), which you can just copy-paste in here.

**Comment by s4lesman** [comment]
`
{"namespace":null,"kinds":["subs"],"filters":[{"name":"doc_id","op":"=","val":"56d9ef9f2764e71200083a73"}],"orders":[],"groupByVal":[],"selectVal":[],"autoPaginateVal":true,"startVal":null,"endVal":null,"limitVal":-1,"offsetVal":-1}
`

and

```

{
  "read_options": {},
  "query": {
    "projection": [],
    "kind": [
      {
        "name": "subs"
      }
    ],
    "filter": {
      "composite_filter": {
        "filter": [
          {
            "property_filter": {
              "property": {
                "name": "doc_id"
              },
              "operator": "EQUAL",
              "value": {
                "entity_value": {
                  "property": [
                    {
                      "name": "_bsontype",
                      "value": {
                        "string_value": "ObjectID"
                      }
                    },
                    {
                      "name": "id",
                      "value": {
                        "string_value": "VÙï'dç\u0012\u0000\b:s"
                      }
                    }
                  ]
                },
                "indexed": false
              }
            }
          }
        ],
        "operator": "AND"
      }
    },
    "order": [],
    "group_by": []
  }
}
```

**Comment by s4lesman** [comment]
@stephenplusplus I see that it is indexed false, maybe thats why.. any idea how I can enforce the index?

**Comment by stephenplusplus** [comment]
I'm wondering if `object._id` returns an object that needs to be unpacked for just the value ID value. Maybe try [`object._id.valueOf()`](https://docs.mongodb.org/manual/reference/method/ObjectId.valueOf/#ObjectId.valueOf)?

**Comment by s4lesman** [comment]
@stephenplusplus at first I was warned about the not indexed but then that triggered it.. I agree with you, I'm going to play around with the data here. But I am positive thats the issue. Thank you so much. You guys are amazing @stephenplusplus & @pcostell

**Comment by stephenplusplus** [comment]
Thank you! I'm glad it all worked out. Come back with any other questions.
