### ISSUE TITLE
Unexplained Logs

### ISSUE THREAD

**Issue by lafama** [GoogleCloudPlatform/gcloud-node#1187]
Am using the pub/sub example code but after afew idle minutes the process starts logging this on the console
```
D0326 20:35:23.510143000 123145308205056 chttp2_transport.c:683] got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'
D0326 20:35:24.358179000 123145308205056 chttp2_transport.c:683] got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'
D0326 20:35:26.633089000 123145308205056 chttp2_transport.c:683] got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'

```
Any Ideas why

**Comment by stephenplusplus** [comment]
Can you open this issue on the grpc repo? https://github.com/grpc/grpc/issues/new

I've observed similar unexplained output before, but the maintainers couldn't produce and it ultimately didn't result in any official resolution. Your testimony might help :)

Please link back after posting.
