### ISSUE TITLE
BigQuery - "dataset.createTable" doesn't support schema as array

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/gcloud-node#1196]
This works:

```js
dataset.createTable(tableName, {
  schema: 'Name:STRING,Age:INTEGER,Weight:FLOAT,IsMagic:BOOLEAN'
}, callback);
```

Based on the docs:

> Schemas can also be specified as a JSON array of fields, which allows for nested and repeated fields. See a [Table resource](http://goo.gl/sl8Dmg) for more detailed information.

Shouldn't this work? (It doesn't as far as I can tell, table is created without a schema.)

```js
dataset.createTable(tableName, {
  schema: [
    {
      "type": "STRING",
      "name": "Name"
    },
    {
      "type": "INTEGER",
      "name": "Age"
    },
    {
      "type": "FLOAT",
      "name": "Weight"
    },
    {
      "type": "BOOLEAN",
      "name": "IsMagic"
    }
  ]
}, callback);
```

Perhaps I missed something.

**Comment by stephenplusplus** [comment]
I think it was an oversight on our part. If it's an array, it had to be boxed in as a property "fields", so options.schema.fields = [...]

Our code should look for schema being an array and box it in accordingly.

**Comment by jmdobry** [comment]
Ah my mistake then, didn't look closely enough at the Table Resource schema.
