### ISSUE TITLE
Are we logging debug stuff accidentally?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#1204]
I have the following script:

```js
var projectId = 'my project';
var gcloud = require('gcloud')({projectId: projectId});
var datastore = gcloud.datastore();

var query = datastore.createQuery('TodoList'); // (1)
datastore.runQuery(query)
  .on('data', function(entity) {})
  .on('end', function() {});
```

When I run it I get this: (note there are no `console.log` calls in my script)

```
$ node gcdtest.js
Service URL: https://datastore.googleapis.com/google.datastore.v1beta3.Datastore
Bearer <a long token is here... not exposing it for obvious reasons>
$
```

**Comment by jgeewax** [comment]
(Also note that this isn't coming from stderr.... it's stdout AFAICT)

**Comment by jgeewax** [comment]
I can't seem to find anything in gcloud-node, google-auto-auth, google-auth-library, or grpc/grpc/src/node .... But I'm not as adept at sleuthing as you guys...

**Comment by stephenplusplus** [comment]
It's from grpc: https://github.com/grpc/grpc/issues/5967#issuecomment-204460329. We need them to release a new version.

**Comment by christyleung1987** [comment]
We should get rid of logging. console.log is performance heavy.
