### ISSUE TITLE
Read consistency support for Datastore

### ISSUE THREAD

**Issue by susanlinsfu** [GoogleCloudPlatform/gcloud-node#1218]
It would be great if we could specifiy the read consitency like the java sdk can for google datastore.

**Comment by stephenplusplus** [comment]
Sounds good to me! Any interest in working on a PR?

**Comment by susanlinsfu** [comment]
I don't believe I am a good enough coder to implement this myself.

**Comment by stephenplusplus** [comment]
No problem, I've put together a PR in #1259 -- please share any thoughts!

```sh
$ npm install --save stephenplusplus/gcloud-node#spp--1218
```
