### ISSUE TITLE
Bigquery BOOLEAN data type conversion bug

### ISSUE THREAD

**Issue by jakeorr** [GoogleCloudPlatform/gcloud-node#1219]
I'm running a query on a BigQuery table. The table includes a BOOLEAN field and has records where the field is `false`. Running `bigQuery.query(query)`with this library results in every record having its boolean variable set to `true`. The culprit is [this line](https://github.com/GoogleCloudPlatform/gcloud-node/blob/c38c548240257625b6a62342eeb3606479cd04a5/lib/bigquery/table.js#L225):

```javascript
value = Boolean(value).valueOf();
```

`value` comes in as the string `'false'`.

From the [Javascript docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean):

> The value passed as the first parameter is converted to a boolean value, if necessary. If value is omitted or is 0, -0, null, false, NaN, undefined, or the empty string (""), the object has an initial value of false. All other values, including any object or the string "false", create an object with an initial value of true.

**Comment by stephenplusplus** [comment]
Yes! I just caught this today in #1216. We'll do a release after that lands.

**Comment by jakeorr** [comment]
Awesome, thanks!
