### ISSUE TITLE
Google Cloud deployment issue with gcloud dependency

### ISSUE THREAD

**Issue by paulshapiro** [GoogleCloudPlatform/gcloud-node#1225]
Not sure if this is relevant specifically to gcloud, but it looks like it may be, so I figured I would ask here. 

We've deployed our app successfully to Google App Engine a number of times already, but recently after adding gcloud as a dependency, deployment does not succeed. It looks like there may be an issue with the available Node version or something similar. 

Upon deployment we get an error saying it times out when starting VMs and that the code may be unhealthy.

Digging through the VM logs, I found this error:

```
module.js:440
return process.dlopen(module, path._makeLong(filename));
^
Error: Module version mismatch. Expected 47, got 46.
at Error (native)
at Object.Module._extensions..node (module.js:440:18)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object.<anonymous> (/app/node_modules/gcloud/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object.<anonymous> (/app/node_modules/gcloud/node_modules/grpc/src/node/src/client.js:54:12)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
```

Time is something of a factor here so help or a nudge in the right direction would be greatly appreciated.

Many thanks,
Paul

**Comment by stephenplusplus** [comment]
I usually see that error when I switch node versions, then try to run the app. npm rebuild or removing the node_modules directory and running npm install again ensures any native dependencies are compiled correctly for the active version of Node. Is there a mismatch in versions between your staging and production environments?

**Comment by paulshapiro** [comment]
I haven't switched Node versions since our earlier successful attempts... and I didn't think I needed to manage node versions manually on App Engine (thought that was one of the points of it)…… but the package.json we're using has specified the same node version the whole time:

```
  "engines": {
    "node": ">=5.9.1"
  },

```

Could it be that I need to delete some VM or something on the App Engine dashboard and deploy again?

To see if I could verify the node version which App Engine is using I opened the Cloud Shell and `node -v` oddly reports v0.12.7. Wondering how that could be. It seems like a very old version. My staging env uses v5.9.1.

I'm somewhat new to App Engine, so I don't have much footing here.

**Comment by stephenplusplus** [comment]
Unfortunately, I'm not very well versed in the App Engine + Node relationship. @jonparrot any insight?

**Comment by stephenplusplus** [comment]
Also cc @jmdobry.

**Comment by jonparrott** [comment]
Cloud Shell's version is unrelated to the version in the runtime.

I'm not sure about the error. @jmdobry might be able to help.

**Comment by jmdobry** [comment]
@paulshapiro Cloud Shell isn't actually a shell into the machine running your App Engine app, it's just a preconfigured environment where can run gcloud commands, so it won't tell what version of node your app is running on. Your app should be running on a version of Node that satisfies `>=5.9.1`.

**Comment by paulshapiro** [comment]
Thanks a bunch @stephenplusplus 

@jmdobry Makes sense. During deployment, I did see an apparently successful installation of 5.9.1 as well:

> Step 4 : RUN /usr/local/bin/install_node '>=5.9.1'
> ---> Running in 318859c211e6
> Installed Node.js v5.9.1

The list of Module Versions under the app's dashboard seemed a bit of a mess. Among 10 or so versions only one of them was serving 100% of traffic and it had about 13 instances behind it. (I wonder if something had gone wrong during some hypothetical cleanup processes which should have removed stale module versions?) I switched traffic over to one of the dormant versions and then went through and deleted all of them, except for the one which was now serving 100% of traffic. Redeploying to see if it makes a difference but I have a feeling it's not going to work. Will update in a moment…

**Comment by jmdobry** [comment]
The stack trace in your log appears to have popped up in grpc. It's possible there's an issue building it (it uses a lot of C++) on the version of Node.js that you're using. Have you filed a bug with your stack trace in the grpc repository?

**Comment by paulshapiro** [comment]
Have not done so yet. Will do.

Is there a version of Node.JS you'd recommend I use on/with App Engine?

(FYI deploy failed again)

**Comment by jmdobry** [comment]
I've successfully deployed the latest gcloud-node to App Engine using the following:

```json
"engines": {
  "node": ">=0.12.7"
}
```

I believe App Engine will select v4.2.3 or something like that. You could try that.

**Comment by paulshapiro** [comment]
Will do. Many thanks, guys. Owe you some beers.

**Comment by paulshapiro** [comment]
Hurray, that version of Node worked.

**Comment by stephenplusplus** [comment]
Woo! However, I noticed you closed this issue before those beers were paid out... Just kidding :) Glad it works!
