### ISSUE TITLE
ReferenceProperty support

### ISSUE THREAD

**Issue by susanlinsfu** [GoogleCloudPlatform/gcloud-node#1226]
Reading the docs about Google Datastore at https://cloud.google.com/appengine/articles/modeling. It mentions properties which would be a great feature as many models require one to many relationships.

**Comment by jgeewax** [comment]
I believe you can do this by setting the property as a `Key` object.

We won't automatically de-reference this for you (ie, when you access the property it will return the key which you then need to `get`), but it's definitely possible to do...

**Comment by jgeewax** [comment]
@stephenplusplus , what are your thoughts here? It kind of gets us into ORM world if we start de-ref'ing keys for people automatically, right?

**Comment by stephenplusplus** [comment]
Yeah, I think what is wanted here is an ORM. We also have a very old issue that requested showing an integration: https://github.com/GoogleCloudPlatform/gcloud-node/issues/87 -- is it worth looking into that again?

@susanlinsfu in case this is helpful, I made a schema validator for gcloud-node + Datastore https://github.com/stephenplusplus/gcloud-datastore-schema -- I'm still working on adding nested array validation, but feel free to take a look.

**Comment by stephenplusplus** [comment]
Feel free to continue the ORM discussion in #87.
