### ISSUE TITLE
Does the vision api have support for more than 5 labels in the response?

### ISSUE THREAD

**Issue by silenceisgolden** [GoogleCloudPlatform/gcloud-node#1228]
In the docs, there are mentions of a `maxResults` property to include on the request.

1. Can this go to greater than a max of 5?
2. If so, can we get something in the `vision.detect` opts to set this property?

**Comment by stephenplusplus** [comment]
Yes and yes! PR sent: https://github.com/GoogleCloudPlatform/gcloud-node/pull/1229

**Comment by silenceisgolden** [comment]
@stephenplusplus Thanks for the quick response and PR!
