### ISSUE TITLE
404 when trying to use Search API

### ISSUE THREAD

**Issue by silenceisgolden** [GoogleCloudPlatform/gcloud-node#1232]
Is there a way that I can get this API to not 404? Thanks!

**Comment by stephenplusplus** [comment]
Are you whitelisted for the API? See #1054.

**Comment by silenceisgolden** [comment]
@stephenplusplus I have been looking all over for that link. Thanks

**Comment by silenceisgolden** [comment]
The form says the early access period has closed, but I submitted a response anyway.

**Comment by stephenplusplus** [comment]
:+1: @jgeewax is there still hope? Can you get him through?
