### ISSUE TITLE
[PubSub] subscription.ack(message.id, callback) returns 500

### ISSUE THREAD

**Issue by kunchenguid** [GoogleCloudPlatform/gcloud-node#1234]
a super simple nodejs script, but I just can't acknowledge the message I pulled. anything I'm doing wrong here?

```js
mySubscription.on('message', function (message) {
  console.log('GOT MESSAGE: ' + message.id) // this shows an integer-like value
  mySubscription.ack(message.id, (err, apiResponse) => {
    // err would be a 500 response here
  })
})
```

**Comment by stephenplusplus** [comment]
I can't seem to reproduce. Is there any more info in the error?

Something else to try would be `message.ack()`.

**Comment by kunchenguid** [comment]
unfortunately there was no more information in the error.. the message was just saying it's internal error and an error code 500.

i can definitely have a try with message.ack this evening. does it help if I share the subscription where I was hitting the error?

**Comment by stephenplusplus** [comment]
Yeah, it probably couldn't hurt. Thanks!

// cc @tmatsuo

**Comment by kunchenguid** [comment]
Sent details to your gmail. :)

**Comment by kunchenguid** [comment]
i figured out.. message.ackId is what we should use. message.id cannot be used in ack(). 
this should probably be better clarified in the documentation, examples, and also error message.

**Comment by stephenplusplus** [comment]
Woops, sorry that I didn't catch that. I'm going to be working on writing some better "overview"-style docs (as opposed to individual method docs), which will definitely cover this. However, if you have an idea to improve what we have already, it would be awesome to receive a pull request.
