### ISSUE TITLE
Ancestor query with filter on children not returning anything

### ISSUE THREAD

**Issue by susanlinsfu** [GoogleCloudPlatform/gcloud-node#1237]
I am using gcloud-node v.0.30.3 and since it doesn't support gRPC I am using gcd-rpc for my local datastore.

Say I run this query to get all the children:

```
        var query = datastore.createQuery('Contacts').hasAncestor(datastore.key(['ContactsParent', 'my_username']));
			datastore.runQuery(query, function (err, entities) {
			if (err) {
				console.log('error ' + err);
				return;
			}
			console.log(JSON.stringify(entities));
				return;
		});

```

This works and returns all the entities. If I go:

```
        var query = datastore.createQuery('Contacts').hasAncestor(datastore.key(['ContactsParent', 'my_username'])).filter('status', 'some status');
			datastore.runQuery(query, function (err, entities) {
			if (err) {
				console.log('error ' + err);
				return;
			}
			console.log(JSON.stringify(entities));
				return;
		});

```

Nothing is return even though it should return something. Nothing is printed in the node console.

I have noticed some strange behavior. If I add a limit clause  to this query it will return an empty array ( [] is printed in the console), but without it nothing.

My index.yaml file looks like this:

indexes: - kind: Contacts ancestor: yes properties: - name: status

I am expecting with this query that all the children get returned, and then from those children only the ones with a status of 'some status' return. This is not happening.

The records do exist in the datastore, but when I filter they do not. Example of a record:

```
datastore.save(
			{
			  key: datastore.key(['ContactsParent','my_username', 'Contacts','my_contact']),
			  method: 'insert',
			  data: {
				status: 'some status'
			  }
			}
}
```

**Comment by stephenplusplus** [comment]
cc @pcostell

**Comment by pcostell** [comment]
@stephenplusplus Could you verify what proto gets sent in this case?

**Comment by pcostell** [comment]
Note I tested this manually using direct gRPC to the emulator and it seems to work fine, so I think it may be limited to gcloud-node.

**Comment by stephenplusplus** [comment]
I'm trying this now and get stuck in an infinite loop. The response always has `batch.moreResults` as `MORE_RESULTS_AFTER_LIMIT`, so our code creates a `nextQuery`, and automatically runs it. The `endCursor` value is always the same as well, so it never gets anywhere.

**Comment by pcostell** [comment]
Didn't we address this in 30.3?

**Comment by stephenplusplus** [comment]
We handle `NOT_FINISHED` by running the query again automatically, regardless of "autoPaginate" being true or false. And we added some perpetual limit logic to make sure we only ask for the right amount of results on those "nextQuery"s. But when we get the `MORE_RESULTS_AFTER_LIMIT` response, we still build and run the nextQuery.

[Here's](https://github.com/GoogleCloudPlatform/gcloud-node/blob/5199cadb557bcbd1c5d34a5debccf97ec982561d/lib/datastore/request.js#L460) where our response logic starts-- anything look incorrect?

**Comment by pcostell** [comment]
Doesn't the logic say to create the nextQuery if `more_results` is `NOT_FINISHED` or `MORE_RESULTS_AFTER_LIMIT`, but only run it if it is `NOT_FINISHED`?

**Comment by stephenplusplus** [comment]
It looks that way because of the code in that function, but when `runQuery` is called, it's actually wrapped by another function which automatically runs any `nextQuery` automatically. This wrapper function is used throughout our API with any method that returns a "nextQuery" (storage.bucket.getFiles(), pubsub.getTopics(), etc). So we had to add in the manual override to continue running if it's "NOT_FINISHED", because the wrapper function wouldn't have continued running the query if the user had "autoPaginate" set to false.

Is it possible the emulator should have returned another value in place of "MORE_RESULTS_AFTER_LIMIT"? The code is only running over and over again because the response is telling us there are more results, but they're not coming.

**Comment by pcostell** [comment]
Yes this is definitely the case: the emulator always returns
MORE_RESULTS_AFTER_LIMIT or NOT_FINISHED, but never NO_MORE_RESULTS.

I am working on making the emulator match production Datastore now.
However, I don't think the client should ever be doing this automatically.
This is the point of having NOT_FINISHED. MORE_RESULTS_AFTER_LIMIT should
only be used as a signal to the user of the client library that there might
be another page. For resource reasons the API explicitly only guarantees
that the value of this field is more conservative from a correctness point
of view (it won't say that is is finished if it actually isn't -- except of
course for eventual consistency for eventually consistent queries).

**Comment by stephenplusplus** [comment]
This is just the default behavior of our API. If there is a "nextQuery" to run, we run it automatically. All methods that act this way can be instructed not to. In the case of `datastore.runQuery()`, `query.autoPaginate(false)` must be set.

We've done it [many ways in the past](https://github.com/GoogleCloudPlatform/gcloud-node/issues?utf8=%E2%9C%93&q=+nextquery+datastore), but [this](https://github.com/GoogleCloudPlatform/gcloud-node/pull/692#issuecomment-121021623) is why it was defaulted.

Do we need to rethink that approach for running Datastore queries, or is allowing auto-pagination to be disabled sufficient?

// @jgeewax

**Comment by susanlinsfu** [comment]
Sorry, but from what I understand adding autoPaginate(false) to my query should solve it? I have just tried adding it to my query and it still returns an empty array.

**Comment by pcostell** [comment]
@stephenplusplus that makes sense, I think in that case you should only
return nextQuery if more_results = NOT_FINISHED (and not do the request
inside runQuery, instead depend on the generic pagination).

**Comment by stephenplusplus** [comment]
@susanlinsfu regarding the empty result set, I'm not sure why they aren't being returned. Here's a script that I've tried: https://gist.github.com/stephenplusplus/8302ecb5892072f80db17f717a84a898. The query seems to return the results. Does that same script not work for you, or am I maybe not properly recreating your scenario?

**Comment by susanlinsfu** [comment]
@stephenplusplus  ahh yes it works for me now, I had a spelling mistake in the word "some stuff". And yes you are right if autopaginate is disabled it works, but if it is not there (or if limit) it will not return any data. Thanks!

**Comment by stephenplusplus** [comment]
Phew, I'm glad you found the fix! I'm not sure which will be first: the gcloud emulator supporting gRPC or a new release of the gcd.sh tool matching the production Datastore API. Until then, as long as you're using either one, `autoPaginate(false)` is a safe bet. Thanks for posting this issue!

**Comment by pcostell** [comment]
@stephenplusplus Do we have an issue tracking improper pagination? Even once the emulator has better handling of `more_results`, `gcloud-node` still needs to stop paging on `MORE_RESULTS_AFTER_LIMIT`.

**Comment by stephenplusplus** [comment]
I thought we should still do that when `autoPaginate` is true (which is default)?

**Comment by pcostell** [comment]
I don't think so -- If a user actually wanted all the results, they shouldn't set a limit. As it is now, anyone who wants a specific number of results has to set both a limit and `autoPaginate = false`. Anyone who wants all the results can either not set a limit or set a limit and leave `autoPaginate = true`.

**Comment by stephenplusplus** [comment]
`autoPaginate` respects the requested limit and stops running. This is built in to the wrapper function.

**Comment by pcostell** [comment]
Ah ok, you can probably ignore me then.

**Comment by stephenplusplus** [comment]
Sorry that the code made this more confusing than it needed to be.

**Comment by pcostell** [comment]
Coming back to this:

I think we need the following:
- On `more_results` = `NOT_FINISHED`, set `next_query`. Properly track offset/limit so that this `next_query` has these set.
- On any other `more_results`, do *not* set `next_query`.

This means we can defer to the normal paging tools to handle paging for us. It would also mean that when `more_results == MORE_RESULTS_AFTER_LIMIT`, `next_query` would not be set. This means we'll need to expose the `end_cursor` and `more_results` so that the user can make an informed decision when choosing to display information to the user.

All of this will apply regardless of the `auto_paginate` setting. Users that set `auto_paginate=False` will just have to deal with the case where `more_results=NOT_FINISHED`, however we'll properly setup the `next_query` for them.

**Comment by aloisDeLaComble** [comment]
autoPaginate(false) does not exist on datastore 0.6.0. Am I doing things wrong or was this method removed ? 
If it has been removed, then how to fix the issue that still occurs when mixing hasAncestor with filter ?

**Comment by dazraf** [comment]
I just installed the latest release of gcloud beta tools - this problem is still an issue. Why is it closed?

**Comment by ziong** [comment]
+1
problem not yet solved!
any update?
