### ISSUE TITLE
Allow recognition of image URL in Vision API

### ISSUE THREAD

**Issue by zywcode** [GoogleCloudPlatform/gcloud-node#1239]
Now, it's support two type that local file and gcsImageUri. 
`eg: 
/data/images/aa.jpg, {"name": aa.jpg, "bucket": {"name": "demo"}}`
Can you add the support of image url.
`eg:http://mydomain/images/aa.jpg`

**Comment by stephenplusplus** [comment]
Which part of our API are you referring to?

**Comment by zywcode** [comment]
`Vision.findImages_(images, callback);`
Can you accept the parameter of url type?
I want to detect the image of url, not File.
`eg:http://mydomain/images/aa.jpg`

**Comment by jgeewax** [comment]
I don't think the Vision API supports "any URL", but specifically a `gcs://` URL.

**Comment by stephenplusplus** [comment]
Cool idea @zywcode. I put a PR together: #1240 -- please try it out!

```js
$ npm install --save stephenplusplus/gcloud-node#spp--1239
```

**Comment by zywcode** [comment]
Thanks @stephenplusplus . That's it what I want.
