### ISSUE TITLE
Bugs with gcd.sh (gcd-rpc 1.0.0)

### ISSUE THREAD

**Issue by sebelga** [GoogleCloudPlatform/gcloud-node#1242]
Hello,

I know that the gcd.sh is a temporary fix until the gcloud emulator support gRPC but here are a few things that I noticed:

- generated IDs are incremental (1, 2, 3, 4, 5...) instead of the _random_ 16 figures number.
- queries don't work if we don't set a "limit"

Nothing big but just letting you know.
Thanks for the great work!

**Comment by stephenplusplus** [comment]
Thanks for the kind words :) This is just an issue tracker for gcloud-node, but I'll bring in @pcostell -- is there another place to report bugs/ask questions specific to the gcd tool that we can direct folks?

**Comment by sebelga** [comment]
Yeah sorry, I didn't know where to share that info :) I'll move it wherever @pcostell tells us.

**Comment by pcostell** [comment]
Moving them to [GoogleCloudPlatform/google-cloud-datastore issue tracker](https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues) is probably the best place for now.

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/google-cloud-datastore#109

**Comment by pcostell** [comment]
Thanks all for the bug reports -- the grpc-based gcd.sh tool is completely new so I really appreciate your help working out the kinks.
