### ISSUE TITLE
API Links in README.md file get stuck in redirect loop

### ISSUE THREAD

**Issue by jpdiazvaz** [GoogleCloudPlatform/gcloud-node#1250]
Hi, when clicking any **API Documentation** link in the README.md file, the browser gets stuck redirecting between two pages.

Here's one of the links
https://googlecloudplatform.github.io/gcloud-node/#/docs/datastore

It redirects back and forth between
`https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.30.3/datastore/gcloud`
and
`https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.30.3/datastore`

This really puts a load into CPU, so it's a really annoying bug if you don't notice the tab.

**Comment by callmehiphop** [comment]
Thanks for reporting this! We just merged a fix, would you mind taking a look and letting us know if you're still experiencing any issues?

**Comment by stephenplusplus** [comment]
Confirmed this is fixed. Thanks for letting us know about this one @jpdiazvaz!
