### ISSUE TITLE
Cannot click on 'Read the Docs' https://googlecloudplatform.github.io/gcloud-node/

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/gcloud-node#1255]
I open https://googlecloudplatform.github.io/gcloud-node/#/
I click on the 'Read the Docs' button.

Observed: Nothing happens.
Expected: the doc loads

Chrome on Linux

**Comment by stephenplusplus** [comment]
Thanks for reporting, I will get right on it.

**Comment by stephenplusplus** [comment]
The docs can now be read 📖
