### ISSUE TITLE
Datastore.runQuery with .on('data') doesn't demonstrate how to "abort"?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#1261]
In a for-loop, I can call `break;` to exit. When I'm in a runQuery stream, I'm unsure how to exit early. Is there a way to document that?

Ie, it might be...

```js
datastore.runQuery(query)
  .on('data', function(entity) {
    if (my exit criteria) this.exit(); // ?
  });
```

**Comment by callmehiphop** [comment]
All the streaming APIs can be exited early via `this.end()`. It would appear that `runQuery` is one of the few places we don't have that documented, I'll put together a PR with some doc updates
