### ISSUE TITLE
Remove search API

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#1262]
Looks like we're changing things around and search won't be it's own API surface.

Can we chop from gcloud-node? (It was a private alpha, so the impact to gcloud-node users should be relatively minimal). If there are concerns about timing, let's discuss here.

**Comment by modeswitch** [comment]
Where does/will the search API live now? I can't find any documentation about it for Node in the flexible environment.

**Comment by lostpebble** [comment]
Does anyone have any word on the Search API? I really need it for my current project that I'm migrating over from the Java app engine side of things. It's the one thing holding me back from going full nodejs.

**Comment by stephenplusplus** [comment]
The Search API was in an alpha state when we supported it. I can't be certain if it will resurface in our API someday, but for now, you should be able to roll back to [`gcloud` version 0.31.0](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.31.0/search) to get through to it.

**Comment by modeswitch** [comment]
Curious why it was removed if there's no plan to provide an alternative? If the code from version 0.31.0 still works, why not leave it in the current version (with warnings?) until the new API comes along?

I suppose there's nothing wrong with pulling the code out into a companion library that depends on this one.
