### ISSUE TITLE
App engine upload limits

### ISSUE THREAD

**Issue by VikramTiwari** [GoogleCloudPlatform/gcloud-node#1268]
Hey guys - Was trying to upload large assets to app engine. Here are quick details:

- File size: > 50MB  - exceeding security limits (32MB) set by app-engine
- Angular Library: https://github.com/danialfarid/ng-file-upload - Utilizing `multipart/form-data`
- NodeJS handler lib: https://github.com/felixge/node-formidable - Utilizing `multipart/form-data`
- Instance to GS using `gcloud-node`

When I am under file limits, everything is working as expected. I get the file in temporary location on instance, push it to GS and delete the file. When going over limits, I get HTTP error with status code `413 `
I stumbled across [this](http://stackoverflow.com/questions/6898736/upload-file-bigger-than-40mb-to-google-app-engine) while trying to debug. But of no help as I am utilizing both suggestions. Any help?

**Comment by jgeewax** [comment]
Hi @VikramTiwari -- how exactly are you using gcloud-node? I don't think there's a whole lot here that's AppEngine specific.

**Comment by VikramTiwari** [comment]
@jgeewax Yeah! That's the way I am doing it. Is there a way I can take file directly from browser to GS?

**Comment by stephenplusplus** [comment]
I put a repo together a while ago that has some examples of how to do just that! https://github.com/stephenplusplus/gcloud-upload-example/blob/master/server.js
