### ISSUE TITLE
gcloud logging not handling correctly entry timestamp

### ISSUE THREAD

**Issue by idosh** [GoogleCloudPlatform/gcloud-node#1270]
I am trying to send logs through my application server using GCP logging api.
When providing a timestamp to the entry I can't find it in the logs viewer but when omitting it I can easily find it.
This is my snippet for creating a log entry:
```javascript
const entry = log.entry(resource, {
    delegate: 'ido'
});
entry.severity = 'INFO';
entry.timestamp = new Date();
entry.labels = {
    tag1: 'true',
    tag2: 'true'
};
```

**Comment by idosh** [comment]
I fixed the problem, apparently gcloud timestamp object is not a date object but an object with `seconds` and `nanos` properties.
So here is my fix:
```javascript
const unix = parseInt(event.timestamp, 10);
const timestamp = {
     nanos: (unix % 1000) * 1000000,
     seconds: unix / 1000
};
```

**Comment by stephenplusplus** [comment]
We should definitely be converting it into a Date object. I'll work on this!

**Comment by stephenplusplus** [comment]
@idosh could you check out #1274 and let me know if it works?

```sh
$ npm install --save stephenplusplus/gcloud-node#spp--1270
```
