### ISSUE TITLE
Implement Cloud CDN API

### ISSUE THREAD

**Issue by gunta** [GoogleCloudPlatform/gcloud-node#1271]
Looking forward to the Cache Invalidation API.

**Comment by callmehiphop** [comment]
I'm not sure this is currently on our radar, but we're always more than happy to accept pull requests if you'd like to contribute!

Also, after looking through the CDN docs I don't see any references to a REST or grpc API. Is this only a command line API? Perhaps @jgeewax can give us some clues about the timing and documentation.

**Comment by gunta** [comment]
I'm not sure but it does looks like command line only / UI atm.

**Comment by stephenplusplus** [comment]
@jgeewax any insight into when this will be available from the HTTP API?

**Comment by stephenplusplus** [comment]
I've created [API Implementation Tracker](https://github.com/GoogleCloudPlatform/gcloud-node/issues/1338) which I've included this request in. Feel free to subscribe to that issue to stay updated!
