### ISSUE TITLE
Bigquery import does not populate err in callback when error occurs

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/gcloud-node#1285]
In trying to track down why data was not appearing in Bigquery even though the import completed "successfully", I noted that the `err` argument was not populated even though an error had occurred.

code:

```javascript

table.import(gcsFile, function(err, job, apiResponse) {
  if(err) {
    callback(err);
    return;
  } 

  console.log('Data import job created');
  console.log(apiResponse);
}
```

The `err` argument is `undefined` (or perhaps `null`), however the apiResponse reports (verbatim from logs):

```javascript
{ kind: 'bigquery#job',
  etag: '"oGMCLvGjZO7RB3oFjn17umMEDU4/v1SSKa6IBg_jGNKysjFGzeC_xYA"',
  id: 'gcf-tests:job_19Q8iGmmqYjyV0V7rj5fiSwiQFw',
  selfLink: 'https://www.googleapis.com/bigquery/v2/projects/gcf-tests/jobs/job_19Q8iGmmqYjyV0V7rj5fiSwiQFw',
  jobReference:
   { projectId: 'gcf-tests',
     jobId: 'job_19Q8iGmmqYjyV0V7rj5fiSwiQFw' },
  configuration:
   { load:
      { sourceUris: [Object],
        destinationTable: [Object],
        sourceFormat: 'CSV' } },
  status:
   { state: 'DONE',
     errorResult:
      { reason: 'invalid',
        message: 'No schema specified on job or table.' },
     errors: [ [Object] ] },
  statistics:
   { creationTime: '1462423012789',
     startTime: '1462423012849',
     endTime: '1462423012849' },
  user_email: '709128455856-compute@developer.gserviceaccount.com' }
```

It *might* be reasonable to have developers inspect the status/errorResult property of the apiResponse, but it seems like it would make more sense to report this as an error

**Comment by jasonpolites** [comment]
Addendum.. just realizing this is an async job, so reporting the status inline is not going to be reliable.  Maybe we can provide a helper function, or maybe just some docs to offer guidance as to how to check for error conditions

**Comment by stephenplusplus** [comment]
The `job` argument is a Job object: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.32.0/bigquery/job -- The docs for `cancel` show how you can set up a loop to get the results of the job.

We should switch to event emitters, like we use for [Compute operations](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.32.0/compute/operation), so it would be something like:

```js
table.import(gcsFile, function(err, job) {
  job.on('error', function(err) {});
  job.on('complete', function() {});
});
```
