### ISSUE TITLE
Fail on subscription.exists request

### ISSUE THREAD

**Issue by massimiliano-delia** [GoogleCloudPlatform/gcloud-node#1286]
Hi,
after updating to v0.32.0 we are facing a very odd problem:

When we call the pubSub module for checking the existence of a subscription whith the current code:

        subscription.exists((error, exists) => {
            if(error){
                return callback(error);
            }
            if(exists){
                subscription.delete((error) => {
                    if (error) {
                        return callback(error);
                    }
                    return callback(null);
                });
            }
            callback(null);
        }); 

we obtain an uncaught exception that breaks the execution.

      events.js:160
      throw er; // Unhandled 'error' event
          ^
      Error: Not Found
      at /Users/massimilianodelia/project/node_modules/grpc/src/node/src/client.js:411:17

we tried to surround exists function with try/catch but it doesn't work.
we are on node 6

please advise for any suggestion or workaround.

**Comment by stephenplusplus** [comment]
Have you narrowed it down to which line is throwing the error?

I believe you need to return after `subscription.delete` so the last `callback` doesn't get executed before the delete has finished running:

```diff
subscription.exists((error, exists) => {
        if(error){
            return callback(error);
        }
        if(exists){
            subscription.delete((error) => {
                if (error) {
                    return callback(error);
                }
                return callback(null);
            });
+           return;
        }
        callback(null);
    }); 
```

**Comment by massimiliano-delia** [comment]
@stephenplusplus Thank You for your fast reply! We fixed that logical error but sadly the issue reported is still here. We have found that the subscription.exists function throws the error. Any further suggestion? Thank You in advance.

**Comment by jgeewax** [comment]
Just to chime in, the error you're seeing in gRPC world is about not being able to parse the response (see https://github.com/grpc/grpc/blob/master/src/node/src/client.js#L411)

**Comment by stephenplusplus** [comment]
I can't reproduce in this case, though I do recall seeing a "Not Found" error before that felt out of place. @callmehiphop does this sound familiar?

**Comment by massimiliano-delia** [comment]
@jgeewax Hi,
checking your url we discovered that You are referring to a different, in-dev version (0.14.0-dev).

The version installed as gcloud-node dependency is the 0.13.1.
So, the interested line in client.js is this https://github.com/grpc/grpc/blob/release-0_13_1/src/node/src/client.js#L411

Thank You in advance.

**Comment by jgeewax** [comment]
Ah @massimiliano-delia -- right you are! Sorry for the misleading data!

Can you add any extra debug info (`console.log(err.code)` maybe?) so we can get a closer look at what's going on? (As @stephenplusplus said, reproducing is tricky given it might be specific to your project and subscription.)

**Comment by massimiliano-delia** [comment]
@jgeewax After putting a debugger at line 411 of client.js we captured this status:

      { code: 5,
        details: 'Resource not found (resource=dev_subscriptionName_1462462595301).',
        metadata: { _internal_repr: {} } }

Also, the error created at line 413 is the following:

       { handle: 12,
         type: 'error',
         className: 'Error',
         constructorFunction: { ref: 13 },
         protoObject: { ref: 14 },
         prototypeObject: { ref: 2 },
         properties: 
           [ { name: 'stack', attributes: 2, propertyType: 3, ref: 2 },
             { name: 'message', attributes: 2, propertyType: 0, ref: 15 },
             { name: 'code', propertyType: 0, ref: 16 },
             { name: 'metadata', propertyType: 0, ref: 17 } ],
         text: 'Error: Resource not found (resource=dev_subscriptionName_1462462595301).' }

After the callback is called (with the error above as the only parameter) and two events are raised, 'status' and 'metadata'.

We are not able to follow the debugging flow anymore.

Thanks in advance.

**Comment by stephenplusplus** [comment]
We definitely need to do a better job of getting that error text through to the gcloud-node user. I'm betting that we're parsing the response incorrectly on our end, not seeing it as a 404 and instead some other type of error. I'll dig into this right now and update you when I make some progress. Thanks for all of the details!

**Comment by jgeewax** [comment]
Yay :) Thanks @massimiliano-delia !

Seems like we're checking for the HTTP status code (404) but not the gRPC error code `grpc.status.NOT_FOUND` (which apparently is `5`...).

**Comment by stephenplusplus** [comment]
That's the part I haven't figured out yet. We do a conversion of gRPC codes to HTTP: https://github.com/GoogleCloudPlatform/gcloud-node/blob/243b52d4e6cca4043021e7ab0c76402b2105d895/lib/common/grpc-service.js#L67

I'm still not sure how it's working for me, but not @massimiliano-delia.

**Comment by callmehiphop** [comment]
> I can't reproduce in this case, though I do recall seeing a "Not Found" error before that felt out of place. @callmehiphop does this sound familiar?

@stephenplusplus unfortunately that does not ring a bell :(

Also, I tried to reproduce this locally as well, but `exists` seems to be working for me as expected.

**Comment by stephenplusplus** [comment]
@massimiliano-delia can you put up a very small test case repo? Everything needed to produce the error and nothing more?

**Comment by stephenplusplus** [comment]
@massimiliano-delia going to close since we can't reproduce. If you get a sample together, I'm happy to continue looking into this issue. Thanks!

**Comment by massimiliano-delia** [comment]
@stephenplusplus Sadly I'm not able to post a test repo that reproduces this issue! Anyway we solved in other manner. Thank You as well!

**Comment by stephenplusplus** [comment]
Oh, great! Glad to hear it worked out :)
