### ISSUE TITLE
Add support for google cloud print

### ISSUE THREAD

**Issue by gkorland** [GoogleCloudPlatform/gcloud-node#1289]
Add support for google cloud print for a server side print

**Comment by stephenplusplus** [comment]
We're more of a dev-ops type of library, so I don't think this type of API is on our radar. Others in this category would be the YouTube API, Drive, Contacts, etc. @jgeewax feel free to correct me if I'm wrong!

**Comment by gkorland** [comment]
Print API is an important service like other service. It's still a critical output for many services.

**Comment by stephenplusplus** [comment]
Our APIs now are essentially what you'll find in the Developers Console. So with this library, a user can upload and query data, start a VM, modify the DNS records of their domains, etc. Do you know of any examples of the Print service playing a dev-ops role that fits in with these other APIs?

**Comment by gkorland** [comment]
perhaps you're right and https://github.com/google/google-api-nodejs-client might fit better for this feature.

**Comment by stephenplusplus** [comment]
Yes, that library is great for the other APIs!

**Comment by gkorland** [comment]
@stephenplusplus it seems like this library doesn't match this API either [issuecomment-217543168](https://github.com/google/google-api-nodejs-client/issues/568#issuecomment-217543168) I'll try to find another place for it ...

**Comment by stephenplusplus** [comment]
Darn. I can try to whip something up. Is there anything wrong with that other project you linked?
