### ISSUE TITLE
logging functions (log.info, log.warning, etc) silently ignored entries

### ISSUE THREAD

**Issue by kunchenguid** [GoogleCloudPlatform/gcloud-node#1290]
in Log.assignSeverityToEntries_, this line
`var entriesClone = [].slice.call(entries);`
will result in an empty array if "entries" is a single entry, while all the logging functions like Log.info, Log.warning etc depends on its ability to process single entry objects. only Log.write can successfully write single entry objects at this time.

**Comment by stephenplusplus** [comment]
Thanks for reporting! I'm working on a PR.

**Comment by stephenplusplus** [comment]
PR sent: #1292 - feel free to try it out:

```sh
$ npm install --save stephenplusplus/gcloud-node#spp--1290
```
