### ISSUE TITLE
Get current instance id

### ISSUE THREAD

**Issue by mik115** [GoogleCloudPlatform/gcloud-node#1291]
Hi,
There's any way to get the current instance id from nodejs?
I found a solution for python 

     from google.appengine.api import modules
     instance_id = modules.get_current_instance_id()

There's a similar way for node js?

Thanks in advance.

**Comment by stephenplusplus** [comment]
We don't have anything like this at the moment. Feel free to discuss/subscribe to #917, which talks about opening up an API for the hosted environments.
