### ISSUE TITLE
Logger breaks on nested objects

### ISSUE THREAD

**Issue by mik115** [GoogleCloudPlatform/gcloud-node#1302]
Hi,
I'm facing a real strange problem:
after updating to 0.32.0 the logging service breaks when a nested object is passed.

es: 
          
       const gcloud = require('gcloud')({
            projectId: 'project_id',
            keyFilename: 'fileKey.json',
        });
        const logging = gcloud.logging();

        const resource = {
             type: 'gae_app',
             labels: {
                  module_id: 'Test',
                  version_id: '1'
              }
        };
 
       const log = logging.log('test');

       const entry = log.entry(resource, {
         message: 'messaggio di test',
         data: {
              error: 'no error',
               log: 'test'
          }
       });
       entry.severity = "INFO";
       //code breaks here
       log.write(entry, (err, apiResponse) =>{
           console.log(err, apiResponse);
       });

Thanks in advance

**Comment by stephenplusplus** [comment]
I'll look right into this, thanks for reporting!

**Comment by mik115** [comment]
The returned error is 

      /Users/mike/testProject/node_modules/protobufjs/dist/ProtoBuf.js:2440
                            throw Error(this+"#"+keyOrObj+" is not a field: undefined");
                            ^

    Error: .google.protobuf.Value#fields is not a field: undefined
    at Error (native)
    at MessagePrototype.set (/Users/mike/testProject/node_modules/protobufjs/dist/ProtoBuf.js:2440:35)
    at MessagePrototype.set (/Users/mike/testProject/node_modules/protobufjs/dist/ProtoBuf.js:2434:38)
    at Message (/Users/mike/testProject/node_modules/protobufjs/dist/ProtoBuf.js:2363:34)
    at ProtoBuf.Reflect.ElementPrototype.verifyValue (/Users/mike/testProject/node_modules/protobufjs/dist/ProtoBuf.js:1877:28)
    at new ProtoBuf.Map.Map (/Users/mike/testProject/node_modules/protobufjs/dist/ProtoBuf.js:4894:46)
    at ProtoBuf.Reflect.FieldPrototype.verifyValue (/Users/mike/testProject/node_modules/protobufjs/dist/ProtoBuf.js:3427:28)

**Comment by stephenplusplus** [comment]
PR sent: #1303

Please try it out!

```sh
$ npm install --save stephenplusplus/gcloud-node#spp--1302
```

**Comment by mik115** [comment]
It works this way! 
Great!

**Comment by 1N50MN14** [comment]
@stephenplusplus didn't this one make it to 0.33.0 on npm? facing the same issue here in my docker container

**Comment by stephenplusplus** [comment]
It did. Can you paste the code to reproduce and the error?

**Comment by 1N50MN14** [comment]
```javascript
Yes one sec, ps logging breaks with entries containing boolean fields as well throwing the error:

/src/node_modules/gcloud/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2440
                            throw Error(this+"#"+keyOrObj+" is not a field: undefined");
                            ^

Error: .google.protobuf.Value#booleanValue is not a field: undefined
```

**Comment by 1N50MN14** [comment]
```javascript
  bigquery.createDataset(datasetName, function(err, dataset) {
    if (err && err.code !== 409)
      throw err;

    logger.createSink(loggerName, {
      destination: bigquery.dataset(datasetName)
    }, function(err, sink){
      if (err && err.code !== 409)
        throw err;

      console.log('logger service started.');

      log = logger.log('syslogs');

      nc.subscribe('events.logger.error', function(data){
        _syslog(data);
      })
    });

  function _syslog(data)
  {    
    var entry = log.entry({}, data);
    log.write(entry, (err, apiResponse) =>{
           console.log(err, apiResponse);
      });
  }
```

The data I'm writing looks like this:
```javascript
{ error: 'Unprocessable Entity',
  message: 'Please check your phone number and try again.',
  code: 422,
  retry: false,
  whoami:
   { image: 'service-sms',
     port: 5000,
     online: true,
     host: '46.101.140.203',
     name: 'sms',
     region: 'local',
     version: '0.0.1',
     dockerhost: '172.17.0.5',
     publichost: '46.101.140.203',
     ports: [ 5000 ] },
  severity: 'INFO',
  origin: 'server',
  method: 'send',
  request: { to: 'xx', text: 'hello world' } }
```

**Comment by stephenplusplus** [comment]
Thanks for the details @1N50MN14 -- could you try out #1329?

```sh
$ npm install --save stephenplusplus/gcloud-node#spp--1302-2
```

**Comment by 1N50MN14** [comment]
Yup, one sec please

**Comment by 1N50MN14** [comment]
```javascript
It's throwing this error:
/src/node_modules/gcloud/node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2440
                            throw Error(this+"#"+keyOrObj+" is not a field: undefined");
                            ^

Error: .google.api.MonitoredResource#image is not a field: undefined
```

(It's also screaming about `autoPaginate` elsewhere in my code not being a function, wondering if the datastore query API has changed)

**Comment by 1N50MN14** [comment]
grr sorry my bad sec please

**Comment by 1N50MN14** [comment]
Ok that seemed to have fixed this error! the callback is returns error 400 though, I'm not sure why that is

**Comment by stephenplusplus** [comment]
I receive that as well without providing something like the following as the first argument to the entry:

```js
var entry = log.entry({
  type: 'gce_instance',
    labels: {
    zone: 'global',
    instance_id: '3'
  }
}, ...
```

**Comment by 1N50MN14** [comment]
yeah that's what I tried to replace, basically I passed my "whoami" object as the resource hence the error I just reported, I will try to place a dummy resource pr your example

**Comment by 1N50MN14** [comment]
the resource object structure seems to be strict and must contain those specific attributes, I tried to add additional labels that didn't work either; but OK that works for me as I'm storing the "whoami" as a part of the entry

**Comment by stephenplusplus** [comment]
Cool, thanks for catching this. It's out now under 0.34.0.

**Comment by 1N50MN14** [comment]
Awesome! Thank you!

Looking at the source of datastore/query.js I see you made some minor modifications there (added info to the cb and got rid of autoPaginate), is this out in 0.34.0 as well?

**Comment by stephenplusplus** [comment]
Yes, that's included as well. Here are the release notes: https://github.com/GoogleCloudPlatform/gcloud-node/releases/tag/v0.34.0
