### ISSUE TITLE
Logger breaks on null values

### ISSUE THREAD

**Issue by mik115** [GoogleCloudPlatform/gcloud-node#1304]
Hi,
Gcloud logger service breaks when the passed object contains null values.
Is this an expected behaviour?

this is the raised error:

      /Users/michelepini/testPubSub/node_modules/protobufjs/dist/ProtoBuf.js:3402
                throw Error("Illegal value for "+this.toString(true)+" of type "+this.type.name+": "+val+" ("+msg+")");
                ^

    Error: Illegal value for Message.Field .google.protobuf.Value.nullValue of type enum: object (proto3 field without field presence cannot be null)
    at Error (native)
    at .<anonymous> (/Users/michelepini/testPubSub/node_modules/protobufjs/dist/ProtoBuf.js:3402:23)
    at ProtoBuf.Reflect.FieldPrototype.verifyValue (/Users/michelepini/testPubSub/node_modules/protobufjs/dist/ProtoBuf.js:3408:21)
    at MessagePrototype.set (/Users/michelepini/testPubSub/node_modules/protobufjs/dist/ProtoBuf.js:2443:59)
    at MessagePrototype.set (/Users/michelepini/testPubSub/node_modules/protobufjs/dist/ProtoBuf.js:2434:38)
    at Message (/Users/michelepini/testPubSub/node_modules/protobufjs/dist/ProtoBuf.js:2363:34)

This is the test object that breaks the service:

     {
        message: 'messaggio di test',
        data: {
            info: {
                message: 'crawlerInterval fetching gAnalytics every 3456 ms',
                furtherInfo: null
            }
        }
    }

Thanks in advance.

**Comment by stephenplusplus** [comment]
> llegal value for Message.Field .google.protobuf.Value.nullValue of type enum: object (proto3 field without field presence cannot be null)

@pcostell you've helped me with similar things in the past... is this a decided limitation of proto3 or does this sound like a bug?

**Comment by pcostell** [comment]
What's the proto definition? I think there is some special parsing that happens for google.protobuf.Value types, I wouldn't be surprised if there was something broken here.

**Comment by stephenplusplus** [comment]
Looks like I missed that `NullValue` is a type, defined with this comment:

```
// `NullValue` is a singleton enumeration to represent the null value for the
// `Value` type union.
//
//  The JSON representation for `NullValue` is JSON `null`.
enum NullValue {
  // Null value.
  NULL_VALUE = 0;
}
```

Putting `0` instead of `null` in our code worked. I'll send a PR and let you try it out @mik115!

**Comment by mik115** [comment]
this way it works!
Great work!
thx

**Comment by stephenplusplus** [comment]
Great, thanks for all of the reports!
