### ISSUE TITLE
Error using gcloud-node behind proxy

### ISSUE THREAD

**Issue by tallesh** [GoogleCloudPlatform/gcloud-node#1305]
I'm trying to use gcloude node behind a corporate proxy on linux (ubuntu 16.04, node 4.4.3), but it always fails print the following log:

```
E0511 10:30:00.216453546    8395 tcp_client_posix.c:191]     failed to connect to 'ipv4:64.233.186.239:443': timeout occurred
E0511 10:30:00.216575680    8395 tcp_client_posix.c:269]     connect error to 'ipv6:[2800:3f0:4003:c00::ef]:443': Network is unreachable
E0511 10:30:01.217801258    8395 tcp_client_posix.c:269]     connect error to 'ipv6:[2800:3f0:4003:c00::ef]:443': Network is unreachable
E0511 10:30:02.974650474    8395 tcp_client_posix.c:269]     connect error to 'ipv6:[2800:3f0:4003:c00::ef]:443': Network is unreachable
E0511 10:30:05.643546905    8395 tcp_client_posix.c:269]     connect error to 'ipv6:[2800:3f0:4003:c00::ef]:443': Network is unreachable

```

I notice that it not respect the proxy settings and try to connect direct. I set the following vars:
HTTP_PROXY, HTTPS_PROXY, FTP_PROXY, http_proxy, https_proxy

The error ocorrur on line:
` datastore.runQuery(query, function(err, entities, nextQuery, apiResponse) `

Do I misunderstood some configuration or it is really a bug? Someone could hep me?

Thanks

**Comment by stephenplusplus** [comment]
// @murgatroid99

**Comment by murgatroid99** [comment]
CC @ctiller

**Comment by murgatroid99** [comment]
grpc does not support connecting through an explicit proxy.

**Comment by tallesh** [comment]
Thank you for your quick response!
I'll try to find some alternative. Thank you for your help.
