### ISSUE TITLE
Reading content of UTF-8 file using createReadStream

### ISSUE THREAD

**Issue by sitepx** [GoogleCloudPlatform/gcloud-node#1308]
We were using file.createReadStream() on gcloud node api to read a UTF-8 file contents.
In the beginning of the file some special characters broke on the process of concat the contents on "data" event.

We already made a workaround, but we think the createReadStrem needs more options like buffer size, or a function do get a file full content.

To ilustrate how the problem goes:

```js
file.createReadStream()
    .on('data', function(data) {
      // Here may be the problem, like if we have in the first 200 characters of the file a sequence of "ç" they some will broke when reading the content.
      content += data;
    }).on('end', function() {
        // use the file contents on content var
    });
```
Thanks!

**Comment by stephenplusplus** [comment]
Could you provide a file that is problematic for createReadStream that we can test with?

**Comment by stephenplusplus** [comment]
Also curious if you can share your workaround? Thanks!

**Comment by stephenplusplus** [comment]
Ping :)

**Comment by adbutterfield** [comment]
I just encountered this problem today, and found the fix. I thought I might as well leave it here in case someone else comes across it. 
You just have to wrap the chunks as they come in with a string decoder, which will buffer multi-byte characters.

```
const { StringDecoder } = require('string_decoder');
const decoder = new StringDecoder('utf8');

let fileBuffer = '';
file.createReadStream()
    .on('data', function(data) {
      fileBuffer += decoder.write(data);
    }).on('end', function() {
        // do something with fileBuffer
    });
```
