### ISSUE TITLE
session_timed_out error when making calls within process event callbacks

### ISSUE THREAD

**Issue by 1N50MN14** [GoogleCloudPlatform/gcloud-node#1309]
API calls (datastore in my case) for some reason timeout when running within process events and throw the following error to stdout:

` D0512 20:19:40.981177886     805 chttp2_transport.c:698]     got goaway [0]: 73 65 73 73 69 6f 6e 5f 74 69 6d 65 64 5f 6f 75 74 'session_timed_out'`

Example:
```javascript
 process.on('exit', function() {
  ds.get(key, fn) // <--- times out
 });
```
Move the API call outside the process event callback and it'll work as expected. Is there any reason for that?

My use case is that I'm keeping track of my processes / docker containers by updating each's online/offline state in datastore depending on whether the process is running or has exited.

It would also be nice to have such errors returned as an API session/timeout/deadline error as the callback never executes and my code logic is left in the dark.

**Comment by callmehiphop** [comment]
@1N50MN14 could you let us know what version of `gcloud` you're using? That error message is usually the result of an underlying transport idling for several minutes, we added some code to remedy this in <kbd>v0.32.0</kbd>.

**Comment by 1N50MN14** [comment]
@callmehiphop I'm on 0.32.0

**Comment by 1N50MN14** [comment]
@callmehiphop I'm also pretty sure the underlying transport isn't idiling (or it shouldn't be idiling) because to narrow down the issue I placed a X seconds timeout in my code before I manually execute `process.exit()` too see what happens, that is after I initialized datastore.

**Comment by stephenplusplus** [comment]
Can you try 0.33.0? Pretty sure this isn't actually an error, just noise from grpc. Originally reported here: https://github.com/grpc/grpc/issues/5967

**Comment by 1N50MN14** [comment]
@stephenplusplus I'm sure it's not grpc noise (I'm using grpc myself across my stack), with gcloud 0.33.0 / grpc 0.14.1 the noise is gone as expected but the underlying problem remains, i.e. the callback for the API call is never triggered... to reproduce the issue all you need to do is make a datastore API call within any process event (exit, siginit etc) and you'll see the issue immediately...

**Comment by stephenplusplus** [comment]
Thanks for calling that out, sorry I missed it the first time around. I was able to reproduce, though I was also able to reproduce for the following scenario as well:

```js
function makeRequest(callback) {
  require('http').get('http://www.yahoo.com', callback)
}

makeRequest(console.log) // callback executed

process.on('exit', function () {
  makeRequest(console.log) // no callback executed
})
```

Then I found: https://nodejs.org/api/process.html#process_event_exit

**Comment by 1N50MN14** [comment]
@stephenplusplus Oh very interesting! Thank you for figuring this out I wouldn't have though this would be the case in a million years... sticking to ping pong then.. thanks again, closing issue
