### ISSUE TITLE
Link to docs is broken

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/gcloud-node#1310]
This link, for example, https://googlecloudplatform.github.io/gcloud-node/#/docs/guides/authentication goes into an infinite redirect loop.

**Comment by stephenplusplus** [comment]
My bad, not fixed. @callmehiphop looks like `types.json` as well as some other files are missing. Could you take a look?

**Comment by stephenplusplus** [comment]
Okay, now we're live. I'm going to look into the Travis docs build process to see if we can prevent this next time.

**Comment by tswast** [comment]
Are we live? The docs links are still not working for me even after hard cache reset and reload.

**Comment by tswast** [comment]
Oh, working now. Thanks
