### ISSUE TITLE
storage/file#getSignedUrl: It shouldn't be necessary to add newline to end of extensionHeaders

### ISSUE THREAD

**Issue by aknuds1** [GoogleCloudPlatform/gcloud-node#1316]
The way storage/file#getSignedUrl computes the signature, it is necessary for the API client to end `extensionHeaders` with a newline, otherwise it won't correspond to the server's calculated signature. This should be handled automatically by gcloud-node.

**Comment by stephenplusplus** [comment]
Fixed via https://github.com/GoogleCloudPlatform/gcloud-node/commit/17e510b32b0b2dfb1901c5d4b918df10daf36cc9.
