### ISSUE TITLE
Date & Time converted when selecting properties

### ISSUE THREAD

**Issue by sebelga** [GoogleCloudPlatform/gcloud-node#1319]
Hi,

When I do a simple query like this:
````
var query = ds.createQuery('BlogPost');
ds.runQuery(query, function(err, entities) {
    // entities have a property 'modifiedOn' that looks like this
    console.log(entities[0].data.modifiedOn); // Fri May 13 2016 18:46:42 GMT+0200 (CEST)
});
```
But if I add to the query
```
query.select(['modifiedOn']);
```
The modifiedOn date time property is then converted in the entity and shows up like this:
```
    console.log(entities[0].data.modifiedOn); // 1463158002000000
```

Any idea why this is happening and how I can get the date correctly formated?

**Comment by stephenplusplus** [comment]
Thanks for reporting. Until we get this fixed, you can convert this like so:

```js
new Date(parseInt({num}, 10) / 1000);
```

**Comment by stephenplusplus** [comment]
@pcostell - The reason we're returning an int is because Datastore is marking the property as an integer value. First thought was we were saving the data incorrectly, but this is the mutation request:

```
[
  {
    "upsert": {
      "key": {
        "path": [
          {
            "kind": "Test",
            "id": 5
          }
        ]
      },
      "properties": {
        "time": {
          "timestampValue": {
            "seconds": 1463400924,
            "nanos": 272000074
          }
        }
      }
    }
  }
]
```

This is the response from the query (response.batch.entityResults):

```
[
  {
    "entity": {
      "key": {
        "partitionId": {
          "projectId": "nth-circlet-705",
          "namespaceId": ""
        },
        "path": [
          {
            "id_type": "id",
            "kind": "Test",
            "id": "5",
            "name": ""
          }
        ]
      },
      "properties": {
        "time": {
          "value_type": "integerValue",
          "nullValue": "NULL_VALUE",
          "booleanValue": false,
          "integerValue": "1463400924272000",
          "doubleValue": 0,
          "timestampValue": null,
          "keyValue": null,
          "stringValue": "",
          "blobValue": "",
          "geoPointValue": null,
          "entityValue": null,
          "arrayValue": null,
          "meaning": 18,
          "excludeFromIndexes": false
        }
      }
    }
  }
]
```

Is there another place you can think of we may be incorrectly sending/returning data?

**Comment by sebelga** [comment]
@stephenplusplus working fine with your fix, thank you!

**Comment by pcostell** [comment]
This is a KI with Datastore -- See https://github.com/GoogleCloudPlatform/gcloud-python/issues/1770.

My response there inline for convenience:

> 
> This is WAI (or WADNAI if you prefer -- Working as Designed, not as intended). timestamp_value is stored as a a fixed-point number in Cloud Datastore. You can see this in the sort order specification, Integers and Date/times are listed together in the sort order.
> 
> In the indexes, the property value is stored without additional information, in this case the indication that this is a datetime. In Cloud Datastore, projection queries aren't just field masks -- they indicate to the system that it should only perform an index scan and not do the full entity lookup. This means it won't have the opportunity to lookup the additional information.
> 
> We hope to be able to fix this eventually, but it has a large impact on backwards compatibility.

**Comment by stephenplusplus** [comment]
Alright, thanks for the info.

**Comment by rupreetg** [comment]
Did anything change in this? I am still getting the issue of getting integer value and if I use the recommended approach, then too I get incorrect date. 

new DateTime(x.Properties["lastrefreshed"].IntegerValue / 1000)  -> returns year 2001 which ideally should be today (27 Sep, 2018). 

Btw, I am using C#, with DataStore.v1 package (2.2.0-beta01). 

This is blocking for me as of now, any help would be appreciated.
