### ISSUE TITLE
[Feature] Cloud Endpoints

### ISSUE THREAD

**Issue by VikramTiwari** [GoogleCloudPlatform/gcloud-node#1323]
Is there any plan to bring cloud endpoints to NodeJS platform on app engine as well?

Most of the stuff that's built using NodeJS is API based and with services such as [loopback](https://loopback.io/) building APIs is being simpler and more standardised by the day. Cloud Endpoints can help in that area with scale and reliability of app engine.

**Comment by stephenplusplus** [comment]
CC: @jgeewax

**Comment by stephenplusplus** [comment]
I've created [API Implementation Tracker](https://github.com/GoogleCloudPlatform/gcloud-node/issues/1338) which I've included this request in. Feel free to subscribe to that issue to stay updated!
