### ISSUE TITLE
Implement Cloud Functions API

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/gcloud-node#1327]
https://developers.google.com/apis-explorer/#p/cloudfunctions/v1beta1/

(Internal & whitelist only right now, just planting the flag that we need/want it )

**Comment by stephenplusplus** [comment]
I've created [API Implementation Tracker](https://github.com/GoogleCloudPlatform/gcloud-node/issues/1338) which I've included this request in. Feel free to subscribe to that issue to stay updated!
