### ISSUE TITLE
Implement RemoteAPI for Node

### ISSUE THREAD

**Issue by susanlinsfu** [GoogleCloudPlatform/gcloud-node#1328]
I'd like to be able to connect to the datastore from any NodeJS application including my local. It would be great if the gcloud-node had the RemoteAPI implemented such as python(https://cloud.google.com/appengine/docs/python/tools/remoteapi).

**Comment by stephenplusplus** [comment]
I might misunderstand, but we support connecting to both the remote API and localhost as well. I know you've been connecting to the emulator, so you already know how to do that. To connect to the remote API, just unset the Datastore emulator environment variable, and make sure to provide a keyFilename with a path to your key file.

**Comment by susanlinsfu** [comment]
I have my nodejs directory which looks something like this:

MyApp
    -app.js
    -mycredetnials.json
    -package.json
    +node_modules
Inside of my app.js file I have the following code:;

var options = {
    projectId: 'mydatastoreproject'
}

var keyFile = './mydatastoreprojectsandbox-5265e25422c.json';

if (keyFile) {
  options.keyFilename = keyFile;
}

var datastore = gcloud.datastore(options);
I am running this from my local computer. I want my local computer to be able to connect to the Google Cloud Datastore (not the local emulator).

In my developer console I have enabled Google Datastore API. I created a KIND in the developer console and created one entity. I have also created credentials (service account key) in the form of a json file. I then included this json file in my code. By doing this I am still unable to connect to the datastore. Am I missing something or doing something wrong? Essentially all I want to do is to have my local machine connect to the Google Datastore.

**Comment by stephenplusplus** [comment]
When you start the local datastore and it prints out "Set these environment variables", did you do that? Is that how you've been connecting to your local Datastore so far? By default, gcloud-node tries to talk to the remote API and assumes there is no emulator running. It has to be told to talk to the emulator, which can be done via the env var (`DATASTORE_EMULATOR_HOST`). If that is what you've been setting, you will have to unset it (or manually do it from the JS script: `delete process.env.DATASTORE_EMULATOR_HOST;`).

**Comment by susanlinsfu** [comment]
ahhhhh yes I had this variable set. All works now thanks!

**Comment by stephenplusplus** [comment]
No problem, glad that it works now!

**Comment by vinodkumarmarupu** [comment]
how to run on pcf

**Comment by Dipesh-Das97** [comment]
How will I be able to use the datastore emulator without the key.json for nodejs?
