### ISSUE TITLE
Compute: Firewall.config.protocols empty array means "everything"

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#1330]
Looking specifically at https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.34.0/compute?method=createFirewall

Consider the following flow:

- I have a list of ports that I know I should allow (ports = `[1,2]`) and I store that somewhere.
- For my script, I know I **don't** want port 2 available, so I remove that before creating my firewall: `ports.pop(2)`
- Someone else has an interceptor after mine that says "I definitely don't want port 1" (`ports.pop(1)`)

At this point, ports is an empty list, and the developer(s) think this means "I've removed all the ports I don't want, so if there were more, fine, but otherwise, nothing is open". Instead it means "all ports are open!" which is ... scary.

Can we be more explicit about what our empty states mean? In this case, I think empty list should mean "no ports are open" and some other special flag (maybe `'*'` ?) or maybe a special subclass of Array that contains every valid port? (ie, when checked if N is in the array, always returns true?)

To give an example of what I'm aiming for...

```js
var ports = database.loadDefaultOpenPorts(); // [11211]
var portsToBlock = [11211, 8675];
ports = ports.filter(function(p) { return portsToBlock.indexOf(p) == -1 }); // []

gce.createFirewall('new-firewall-name', {
  protocols: { tcp: ports }, // [] here means "No ports are allowed"
  ranges: ['0.0.0.0/0']
}, cb);
```

If I want to explicitly say "all ports":

```js
gce.createFirewall('new-firewall-name', {
  protocols: { // Explicitly ask for all ports (shown two different ways)
    tcp: gce.firewall.allPorts,
    udp: '*'
  },
  ranges: ['0.0.0.0/0']
}, cb);
```

**Comment by stephenplusplus** [comment]
I might just be wrong about what the API does.

See the description of `allowed[].IPProtocol` here: https://cloud.google.com/compute/docs/reference/latest/firewalls/insert -- 

```js
  "allowed": [
    {
      "IPProtocol": "tcp"
    },
    {
      "IPProtocol": "17",
      "ports": [ "161" ],
    }
  ]
```

Are any ports opened for the TCP protocol? Whatever that does, that's all gcloud-node does when it receives an empty array.

**Comment by jgeewax** [comment]
I actually don't know. `ports` doesn't seem to be defined in the list (while `IPProtocol` -- redundantly named -- does). I'll have to ask...

**Comment by mziccard** [comment]
Quoting from [Firewalls docs](https://cloud.google.com/compute/docs/networking#firewalls):

> ports
[Optional] An array of target ports allowed for this connection. This is only applicable for TCP and UDP connections. Each value is a string that is either a single port or a port range. **If not specified, all ports are allowed.** Example: ["80", "160", "300-500"]

**Comment by jgeewax** [comment]
Right, so it seems like it does... not what we want. That's kinda scary. To clarify what I'd expect...

- Open all TCP ports to the world

  ```js
  gce.createFirewall('new-firewall-name', {
    protocols: {
      tcp: gce.firewall.ALL_PORTS // Or something like this
    },
    ranges: ['0.0.0.0/0']
  }, cb);
  ```

- Open *no* TCP ports to the world

  ```js
  gce.createFirewall('new-firewall-name', {
    protocols: { tcp: [] },
    ranges: ['0.0.0.0/0']
  }, cb);
  ```

- Check if port 350 is open


  ```js
  gce.createFirewall('new-firewall-name', {
    protocols: { tcp: ["300-400"] },
    ranges: ['0.0.0.0/0']
  }, function(firewall) {
    console.log(firewall.protocols.tcp.contains(350)); // true
  });
  ```

**Comment by stephenplusplus** [comment]
Fiest example, how about tcp: true?

Second example, how do I tell the API not to open ports? 

Third example, if they just opened it, why are they checking? Or are you just illustrating that it should have been opened?

**Comment by jgeewax** [comment]
> Fiest example, how about tcp: true?

SGTM.

> Second example, how do I tell the API not to open ports?

Technically it should be just removing the TCP key... but @mziccard may know a bit more.

> Third example, if they just opened it, why are they checking? Or are you just illustrating that it should have been opened?

Yea -- just an illustration. The idea though is that I set a range, and I'm checking a specific port. That's a bit trickier.

**Comment by mziccard** [comment]
> Technically it should be just removing the TCP key...

Yes by passing TPC you are saying "open all ports for TPC", by passing TCP + [port array] you are saying "open all ports in [port array] for TCP", if you don't pass TCP all TCP traffic is rejected.
