### ISSUE TITLE
How to save JSON objects in bigquery?

### ISSUE THREAD

**Issue by 1N50MN14** [GoogleCloudPlatform/gcloud-node#1336]
I'm thinking to move away from logging and write the logs myself directly to bigquery; looking at the API I can only see an `import` function which reads from file, but I would really like to write the objects myself, how can I do that?

**Comment by stephenplusplus** [comment]
Does `table#insert` work? https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.34.0/bigquery/table?method=insert

We also have `table#createWriteStream` for stream inputs: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.34.0/bigquery/table?method=createWriteStream

**Comment by 1N50MN14** [comment]
Oh absolutely (yay for `createWriteStream`!), apologies I missed that in the docs somehow I had the API docs like open on 0.33.0. Closing issue
