### ISSUE TITLE
How to specify logging sink?

### ISSUE THREAD

**Issue by 1N50MN14** [GoogleCloudPlatform/gcloud-node#1337]
I have created multiple sinks to better organize/group my logs, went through the docs (and the source) still can't figure out how to dynamically specify the sink I'd like to log to. 

Is there any way I could accomplish something like?
```javascript
var syslog = logging.log('syslog', sinkName);
```

**Comment by stephenplusplus** [comment]
```js
var sink = logging.sink(sinkName);
var syslog = sink.log('syslog');
```

**Comment by 1N50MN14** [comment]
@stephenplusplus That was the first thing I tried, doesn't work..

```
TypeError: sink.log is not a function
    at Logger.log (/src/lib/logger.js:117:18)
    at Logger.apiError (/src/lib/logger.js:60:15)
```

**Comment by 1N50MN14** [comment]
I also tried 
```
var log = sink.parent.log(tbl);
```
since `parent` is exposed and it contains a reference to Logging, but that still writes to all sinks.

**Comment by stephenplusplus** [comment]
Oh yeah, I was mistaken. I believe a sink is created to export log entries automatically as they are written. So you don't go through a sink to get to a log.

Here's an explanation from the docs:

--

You export log entries by creating a sink that directs a set of log entries to a specific destination. You stop exporting the log entries by deleting or changing the sink. You can have any number of sinks.

A project sink exports entries that match an advanced logs filter. Filters can specify specific logs, monitored resource types, log entry payload contents, and much more. Project sinks are supported by the Logging API v2 and by the SDK, but they cannot presently be configured in the Log Viewer's Export panel.

**Comment by 1N50MN14** [comment]
Right ok, now that I understand this I think the only way to accomplish what I'm looking for is to simply create X logging object, each assigned to a single sink and choose which logger I want to use based on the target sink.

Viewer panel is not important in my case as I'm hooking the logs to BIME. Thanks for the help! ;)

**Comment by 1N50MN14** [comment]
^^^ that didn't work either, still logs to all sinks, looks like `var this.logging[prop] = gcloud.logging(config)` yields a reference to the same Logging instance.

**Comment by stephenplusplus** [comment]
Are you setting the sinks with a filter that only matches the logs you are writing to? https://cloud.google.com/logging/docs/view/advanced_filters

```js
sink.create({
  filter: 'log=syslog'
}, function() {
  syslog.write(...) // should only go to that sink
})
```

**Comment by 1N50MN14** [comment]
That's a good question... I'm not doing that, my `syslog` is dynamic can I pass a regex to filter?

**Comment by 1N50MN14** [comment]
Or even something like
```javascript
sink.create({
  filter: 'log=api.error.*'
}, function() {
  syslog.write(...) // should only go to that sink
})
```
(reading the docs, thanks for the link)

**Comment by stephenplusplus** [comment]
It doesn't look like there's an option for that. If your logs are split for things like the severity of the entry, maybe you would get the same benefit by creating a sink that filters on the severity instead:

`filter: 'severity>=ERROR'`

**Comment by 1N50MN14** [comment]
Ok following the above example I decided to add a `__sink` filter to each sink basically holding the sink's name, and I will add this as an attribute to each log entry prior to writing it. Problem now is if I add a filter `create` throws error 400 even if I first delete the sinks.

Here's my code snippet, pretty straight forward.. 

```javascript
  return Promise.map(self.datasets, function(ds)
  {
      return new Promise(function(resolve, reject)
      {
        self.bigquery.createDataset(ds, function(err, dataset)
        {
          if (err && err.code !== 409)
            return reject(err);

            var conf = {
              destination:self.bigquery.dataset(ds),
              filter: '__sink = '+ds
            };

            //var sink = self.logging.sink(ds);
            //sink.create(conf, cb) <- same, throws error 400
            self.logging.createSink(ds, conf, function(err, sink){
              if (!err)
                return resolve()

              console.log(conf, err)
              err.code === 409 ? resolve()
                               : reject(err);
            })
        });
      });
  })
```

**Comment by stephenplusplus** [comment]
Is there such a thing as a `__sink` filter? I couldn't find it in the docs. Maybe you can use labels on your entries and filter on those:

```js
filter: 'labels.__sink = ' + ds
```

@jgeewax anyone from the Logging team available for general advice?

**Comment by 1N50MN14** [comment]
Hmmm sorry I think you're right for some reason I thought there was a reference to it, going to try to set  __sink on labels instead see how it works..

**Comment by 1N50MN14** [comment]
Ok that throws error 400 on the `log.write` call.. maybe resource labels don't like having a prop that starts with `__`, also going to try to use the `zone` label if adding my own fails too...

**Comment by 1N50MN14** [comment]
Ok it works by relying on the `zone` (which I'm not relying on, I have it as a part of my payload), i.e. filter becomes `filter: 'labels.zone = '+ds` and for each log write I set the appropriate ds/sink name for `labels.zone`. A bit hacky but works I guess, going to put a small note in my code to revisit this in case you decide to change the behaviour on how to accomplish this in the future.

Thank you very much for the help!

**Comment by stephenplusplus** [comment]
Of course, thanks for bringing up the discussion. I'll close this issue out, but if @jgeewax himself or a Logging ally can recommend a better solution, please let us know!
