### ISSUE TITLE
question: how to get the ending byte/offset of storage upload stream

### ISSUE THREAD

**Issue by 1N50MN14** [GoogleCloudPlatform/gcloud-node#1344]
I have the following use case scenario:

mobile video stream > pipe(multipluxer) -> pipe(writable stream) 

Upon client (mobile) network interruption / reconnection I first clean end the gcs write stream then restart the above process except that I need to write starting the last written offset+1. Is there any way I can get the size / offset within the `finish` callback or otherwise through a separate API call?   

I could inject a `through2` stream to count the bytes myself but this does not guarantee the bytes count matches what has been actually written in gcs storage..

**Comment by stephenplusplus** [comment]
Does it not "just work" when you try to upload the file the next time?

We use [`gcs-resumable-upload`](http://gitnpm.com/gcs-resumable-upload) behind the scenes. You can use it directly to get the offset:

```js
var gcsUpload = require('gcs-resumable-upload')

var uploader = gcsUpload({
  uri: 'http://resumable-upload-uri'
})

mobileVideoStream.pipe(multiplexer).pipe(uploader)

uploader.getAndSetOffset(function (err) {
  if (err) throw err
  console.log(uploader.offset)
})
```

I believe while researching, I caught a bug: https://github.com/stephenplusplus/gcs-resumable-upload/pull/13 -- so as of now, you can get the offset, but you can't instruct gcloud-node (or gcs-resumable-upload) to start from a given offset.

**Comment by 1N50MN14** [comment]
@stephenplusplus The behaviour I'm getting is that it starts writing from offset 0, it sounds like the bug you caught. Anyhow I'm going to triple check my code and put some tests in place to make sure it's not a mistake on my side

**Comment by stephenplusplus** [comment]
I wonder if not enough content makes it to GCS to be saved. I believe
there's a magic number out there where it retains the data. I observed that
number being around 5-10 MB.

**Comment by 1N50MN14** [comment]
I'll add a check for that it might be the case as I haven't rested with >5mb streams

**Comment by bhstahl** [comment]
Interesting about the < 5-10 mb streams. I think I noticed that as well

**Comment by 1N50MN14** [comment]
I'm spend few hours next Monday to try to narrow down this issue, hopefully I'll be able to come back with a concrete snippet that replicates the behaviour and post it here

**Comment by stephenplusplus** [comment]
Cool, thanks! I just released gcs-resumable-upload@0.6.1 so un- and re-installing gcloud should pick up the latest version.

**Comment by stephenplusplus** [comment]
@1N50MN14 be sure to let us know how it goes :)

**Comment by stephenplusplus** [comment]
No problem, and I'm sorry to hear that :( Fingers are crossed over here, too. Take your time!

**Comment by stephenplusplus** [comment]
@1N50MN14 I think everything should be okay now, so I'll close this out. If you're still having issues after testing, just let me know.
