### ISSUE TITLE
logging: Can't set "partialSuccess"

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/gcloud-node#1349]
This is possible with the google-api-nodejs-client, but my naive attempt to do this fails:

```js
log.write(entries, {partialSuccess: true}, cb)
```

**Comment by stephenplusplus** [comment]
Good catch. That's where it should go, and it should work, but it looks like the proto file doesn't specify it as an option: https://github.com/googleapis/googleapis/blob/master/google/logging/v2/logging.proto#L69

cc: @filipjs

**Comment by filipjs** [comment]
Hey, 
looks like the proto file on Github was last updated in January. 
I'll check what's the process of updating it.

**Comment by filipjs** [comment]
Update is in progress, should be done shortly

**Comment by ethanbao** [comment]
The updated logging protos are now available at https://github.com/googleapis/googleapis/tree/master/google/logging

**Comment by stephenplusplus** [comment]
Thanks, @ethanbao!

@zbjornson PR incoming.

**Comment by stephenplusplus** [comment]
@zbjornson until our next release, you can install from master:

```js
$ npm install --save googlecloudplatform/gcloud-node
```

**Comment by zbjornson** [comment]
Thank you all!
