### ISSUE TITLE
datastore transaction callbacks hang

### ISSUE THREAD

**Issue by 1N50MN14** [GoogleCloudPlatform/gcloud-node#1351]
Below is a code snippet where I perform simple `delete`and `insert` operations in a transaction, strictly following the 0.34.0 API documentation:

```javascript
  var datastore = gcloud.datastore(conf);
  var SLUGS = 'dummy_collection';

  var current_slug ="current_dummy_slug";
  var slug = "new_slug";
  var uid ="dummy_uid";

  datastore.runInTransaction(function(transaction, done)
  {
    transaction.delete(datastore.key([SLUGS, current_slug]), function(err)
    {
      if (err)
        return transaction.rollback(done(err));

      var entry = {
        key: datastore.key([SLUGS, slug]),
        data: {
          uid:uid 
        }
      };

      transaction.insert(entry, function(err)
      {
        return err ? transaction.rollback(done(err)) : done();
      });

    });
  }, function(err, apiResponse) {
    console.log(err, apiResponse)
  });
```
For some reason the callback for `transaction.delete()` hangs, as in it doesn't seem to run at all unless I call `transaction.datastore.delete()` instead, same goes for `transaction.insert()`. Is is the expected behaviour or am I doing something wrong?

**Comment by stephenplusplus** [comment]
Yes, save and delete don't get callbacks when run in a transaction: http://stackoverflow.com/questions/34969316/do-datastore-transactions-need-rollback-when-saving-or-deleting. The mutations are queued until done is called.

**Comment by 1N50MN14** [comment]
hmmm so how do I rollback if `delete` fails for some reason? or is that handled automatically as in the code becomes something like:

```javascript
  datastore.runInTransaction(function(transaction, done)
  {
    transaction.delete(datastore.key([SLUGS, current_slug]));
    transaction.insert(entry);  
    });
  }, function(err, apiResponse) {
    //if either delete or insert fails, transaction is rolledback 
    //and first error is returned?
    console.log(err, apiResponse)
  });
```

**Comment by 1N50MN14** [comment]
Yeah just tested the snippet this seems to be the case. Thanks @stephenplusplus
