### ISSUE TITLE
Change `gcloud-node` to `gcloud` in documentation

### ISSUE THREAD

**Issue by adambuczynski** [GoogleCloudPlatform/gcloud-node#1362]
See https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.35.0/guides/authentication

It mentions `gcloud-node` while the package seems to have been renamed to `gcloud` in the meantime.

**Comment by stephenplusplus** [comment]
It's kind of a naming overload. The package on npm is `gcloud`, but the repo name and officially recognized name is `gcloud-node` to distinguish it from `gcloud`, the CLI command for the cloud SDK (https://cloud.google.com/sdk/), as well as the other client libraries in other languages, like gcloud-php, gcloud-ruby, etc. Does that explain it, or did I miss something in that doc that needs to be corrected?

**Comment by adambuczynski** [comment]
Hmm.. the reason I brought this up as an issue, is because based on that documentation I tried to do an `npm install gcloud-node`, which failed, and it took me a little while to realise the package was actually called `gcloud`. 

I assume I'm not the only one to get confused by that :)

**Comment by stephenplusplus** [comment]
I updated it to hopefully avoid confusion. Thanks!

**Comment by adambuczynski** [comment]
Cheers, thank you!

**Comment by stephenplusplus** [comment]
@adambuczynski don't think we didn't appreciate this change, but it looks like we're going to have to stick to `gcloud-node` (https://github.com/GoogleCloudPlatform/gcloud-common/issues/142#issuecomment-228390686).

**Comment by adambuczynski** [comment]
@stephenplusplus no worries, I understand the reasoning.

Maybe it could just be made more clear in the documentation that the Node package itself is called `gcloud`.
