### ISSUE TITLE
Links in overview menu's do not link to the proper methods

### ISSUE THREAD

**Issue by adambuczynski** [GoogleCloudPlatform/gcloud-node#1363]
See the following pages (amongst others):

https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.35.0/storage/file
https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.35.0/storage/bucket

The links in the overview at the top to the `delete` method in fact take you to the `acl.delete` method. If you hover over both links, they both are linked to `?method=delete`. The same is true for other methods which share their name with `acl` counterparts, e.g. `get` and `acl.get`.

I assume this problem is widespread and probably affects many other docs pages.

**Comment by callmehiphop** [comment]
Thanks for opening this, @adambuczynski !

**Comment by adambuczynski** [comment]
No worries, thanks for fixing.
