### ISSUE TITLE
Datastore emulator error on query

### ISSUE THREAD

**Issue by mik115** [GoogleCloudPlatform/gcloud-node#1368]
Hi,
I started using the datastore emulator, installed with this command 

    gcloud components install cloud-datastore-emulator 
version 1.1.0

setted
      
    apiEndpoint: 'http://127.0.0.1:8082'

When  i run a simple test code that try to save an entity on datastore i obtain this error:

    [datastore] java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/sourceforge/yamlbeans/YamlException
    [datastore]     at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:477)
    [datastore]     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
    [datastore]     at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
    [datastore]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    [datastore]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    [datastore]     at java.lang.Thread.run(Thread.java:745)
    [datastore] Caused by: java.lang.NoClassDefFoundError: net/sourceforge/yamlbeans/YamlException
    [datastore]     at com.google.appengine.api.datastore.dev.LocalCompositeIndexManager$YamlIndexFileManager.read(LocalCompositeIndexManager.java:598)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalCompositeIndexManager.getIndexes(LocalCompositeIndexManager.java:884)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalCompositeIndexManager.getIndexesForKind(LocalCompositeIndexManager.java:901)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreCostAnalysis.changedIndexRows(LocalDatastoreCostAnalysis.java:138)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreCostAnalysis.getWriteOps(LocalDatastoreCostAnalysis.java:84)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreService$WriteJob.calculateJobCost(LocalDatastoreService.java:2363)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreService.commitImpl(LocalDatastoreService.java:1615)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreService.commit(LocalDatastoreService.java:1562)
    [datastore]     at com.google.appengine.api.datastore.dev.DatastoreV3Impl.commit(DatastoreV3Impl.java:57)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1$CanonicalCodeDatastoreV3.commit(CloudDatastoreV1.java:892)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.commitMutations(CloudDatastoreV1.java:757)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.applyMutationList(CloudDatastoreV1.java:655)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.commit(CloudDatastoreV1.java:331)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.commitNonTransactional(CloudDatastoreV1.java:377)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.commit(CloudDatastoreV1.java:315)
    [datastore]     at com.google.cloud.datastore.emulator.v1.DatastoreEmulator.commit(DatastoreEmulator.java:147)
    [datastore]     at com.google.cloud.datastore.emulator.v1.DatastoreEmulatorGrpcAdapter.commit(DatastoreEmulatorGrpcAdapter.java:131)
    [datastore]     at com.google.datastore.v1.DatastoreGrpc$MethodHandlers.invoke(DatastoreGrpc.java:570)
    [datastore]     at io.grpc.stub.ServerCalls$1$1.onHalfClose(ServerCalls.java:151)
    [datastore]     at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:259)
    [datastore]     at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:471)
    [datastore]     ... 5 more
    [datastore] Caused by: java.lang.ClassNotFoundException: net.sourceforge.yamlbeans.YamlException
    [datastore]     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    [datastore]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    [datastore]     at java.security.AccessController.doPrivileged(Native Method)
    [datastore]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    [datastore]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    [datastore]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    [datastore]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    [datastore]     ... 26 more
    [datastore] 
    [datastore] Jun 08, 2016 8:40:10 AM io.grpc.internal.SerializingExecutor$TaskRunner run
    [datastore] SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2@20724c76
    [datastore] java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/sourceforge/yamlbeans/YamlException
    [datastore]     at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:477)
    [datastore]     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
    [datastore]     at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
    [datastore]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    [datastore]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    [datastore]     at java.lang.Thread.run(Thread.java:745)
    [datastore] Caused by: java.lang.NoClassDefFoundError: net/sourceforge/yamlbeans/YamlException
    [datastore]     at com.google.appengine.api.datastore.dev.LocalCompositeIndexManager$YamlIndexFileManager.read(LocalCompositeIndexManager.java:598)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalCompositeIndexManager.getIndexes(LocalCompositeIndexManager.java:884)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalCompositeIndexManager.getIndexesForKind(LocalCompositeIndexManager.java:901)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreCostAnalysis.changedIndexRows(LocalDatastoreCostAnalysis.java:138)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreCostAnalysis.getWriteOps(LocalDatastoreCostAnalysis.java:84)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreService$WriteJob.calculateJobCost(LocalDatastoreService.java:2363)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreService.commitImpl(LocalDatastoreService.java:1615)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreService.commit(LocalDatastoreService.java:1562)
    [datastore]     at com.google.appengine.api.datastore.dev.DatastoreV3Impl.commit(DatastoreV3Impl.java:57)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1$CanonicalCodeDatastoreV3.commit(CloudDatastoreV1.java:892)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.commitMutations(CloudDatastoreV1.java:757)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.applyMutationList(CloudDatastoreV1.java:655)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.commit(CloudDatastoreV1.java:331)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.commitNonTransactional(CloudDatastoreV1.java:377)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.commit(CloudDatastoreV1.java:315)
    [datastore]     at com.google.cloud.datastore.emulator.v1.DatastoreEmulator.commit(DatastoreEmulator.java:147)
    [datastore]     at com.google.cloud.datastore.emulator.v1.DatastoreEmulatorGrpcAdapter.commit(DatastoreEmulatorGrpcAdapter.java:131)
    [datastore]     at com.google.datastore.v1.DatastoreGrpc$MethodHandlers.invoke(DatastoreGrpc.java:570)
    [datastore]     at io.grpc.stub.ServerCalls$1$1.onHalfClose(ServerCalls.java:151)
    [datastore]     at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:259)
    [datastore]     at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:471)
    [datastore]     ... 5 more
    [datastore] Caused by: java.lang.ClassNotFoundException: net.sourceforge.yamlbeans.YamlException
    [datastore]     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    [datastore]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    [datastore]     at java.security.AccessController.doPrivileged(Native Method)
    [datastore]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    [datastore]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    [datastore]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    [datastore]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    [datastore]     ... 26 more
    [datastore] 
    [datastore] Jun 08, 2016 8:40:14 AM io.grpc.internal.SerializingExecutor$TaskRunner run
    [datastore] SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2@7168fb5a
    [datastore] java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/sourceforge/yamlbeans/YamlException
    [datastore]     at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:477)
    [datastore]     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
    [datastore]     at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
    [datastore]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    [datastore]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    [datastore]     at java.lang.Thread.run(Thread.java:745)
    [datastore] Caused by: java.lang.NoClassDefFoundError: net/sourceforge/yamlbeans/YamlException
    [datastore]     at com.google.appengine.api.datastore.dev.LocalCompositeIndexManager$YamlIndexFileManager.read(LocalCompositeIndexManager.java:598)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalCompositeIndexManager.getIndexes(LocalCompositeIndexManager.java:884)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalCompositeIndexManager.getIndexesForKind(LocalCompositeIndexManager.java:901)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreCostAnalysis.changedIndexRows(LocalDatastoreCostAnalysis.java:138)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreCostAnalysis.getWriteOps(LocalDatastoreCostAnalysis.java:84)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreService$WriteJob.calculateJobCost(LocalDatastoreService.java:2363)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreService.commitImpl(LocalDatastoreService.java:1615)
    [datastore]     at com.google.appengine.api.datastore.dev.LocalDatastoreService.commit(LocalDatastoreService.java:1562)
    [datastore]     at com.google.appengine.api.datastore.dev.DatastoreV3Impl.commit(DatastoreV3Impl.java:57)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1$CanonicalCodeDatastoreV3.commit(CloudDatastoreV1.java:892)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.commitMutations(CloudDatastoreV1.java:757)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.applyMutationList(CloudDatastoreV1.java:655)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.commit(CloudDatastoreV1.java:331)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.commitNonTransactional(CloudDatastoreV1.java:377)
    [datastore]     at com.google.appengine.api.datastore.dev.CloudDatastoreV1.commit(CloudDatastoreV1.java:315)
    [datastore]     at com.google.cloud.datastore.emulator.v1.DatastoreEmulator.commit(DatastoreEmulator.java:147)
    [datastore]     at com.google.cloud.datastore.emulator.v1.DatastoreEmulatorGrpcAdapter.commit(DatastoreEmulatorGrpcAdapter.java:131)
    [datastore]     at com.google.datastore.v1.DatastoreGrpc$MethodHandlers.invoke(DatastoreGrpc.java:570)
    [datastore]     at io.grpc.stub.ServerCalls$1$1.onHalfClose(ServerCalls.java:151)
    [datastore]     at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:259)
    [datastore]     at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:471)
    [datastore]     ... 5 more
    [datastore] Caused by: java.lang.ClassNotFoundException: net.sourceforge.yamlbeans.YamlException
    [datastore]     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    [datastore]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    [datastore]     at java.security.AccessController.doPrivileged(Native Method)
    [datastore]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    [datastore]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    [datastore]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    [datastore]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    [datastore]     ... 26 more
    [datastore] 

Any ideas on how i can make it work?

Thanks in advance

**Comment by stephenplusplus** [comment]
cc @pcostell

**Comment by pcostell** [comment]
This looks like a bug in our jar minimizer -- I'll take a look. In the mean time, you may be able to make progress by running the emulator directly `$GCLOUD_PATH/platform/cloud-datastore-emulator/cloud_datastore_emulator` and passing it the `--testing` flag, which won't try to read the `index.yaml` file.

**Comment by pcostell** [comment]
This should be fixed in the next version of the Cloud Datastore emulator. It will go out with a future version of the Cloud SDK, but if you'd like to get it early you can [download it here](storage.googleapis.com/gcd/tools/cloud-datastore-emulator-1.1.1.zip).

**Comment by mik115** [comment]
@pcostell thanks for the answer,
unfortunately your link sends on a 404 github page.

**Comment by stephenplusplus** [comment]
Fixed the link :)

**Comment by pcostell** [comment]
Thanks @stephenplusplus
