### ISSUE TITLE
cron support in node.js App Engine

### ISSUE THREAD

**Issue by bamapookie** [GoogleCloudPlatform/gcloud-node#1371]
I apologize if this is the wrong place for this, but I am trying to deploy a node.js app to the App Engine with a cron job.  I added the cron.yaml file to the app and deployed, but the job never gets executed.

cron.yaml:

    cron:
    - description: test cron job
      url: /api/crontest
      schedule: every 1 mins

The endpoint exists in my app and I can hit it directly from the browser, but it never executes from the cron.  The only thing I see in the logs is an occasional cron: unrecognized service, but it does not correspond with the one minute frequency.

What am I missing? Is cron supported in the platform?

**Comment by stephenplusplus** [comment]
This repository is for the [`gcloud`](http://www.npmjs.com/gcloud) Node module. I think you'll have good luck posting this question to StackOverflow under the right keywords (node, appengine, google cloud platform). After you post, please come back here and drop a link.

**Comment by bamapookie** [comment]
Thanks, Stephen++.  Here is the link: http://stackoverflow.com/questions/37734030/cron-support-in-node-js-app-engine

**Comment by bamapookie** [comment]
@stephenplusplus Should this have been asked in the nodejs-docker project (https://github.com/GoogleCloudPlatform/nodejs-docker)?

**Comment by bamapookie** [comment]
I found the answer.  I missed the previous page in the docs (here: https://cloud.google.com/appengine/docs/flexible/java/yaml-configuration-files) that mentioned needing to run `gcloud preview app deploy cron.yaml`.

**Comment by stephenplusplus** [comment]
Nice, thanks for coming back to share the answer!
