### ISSUE TITLE
Datastore queries for IN and NE

### ISSUE THREAD

**Issue by ajagnanan** [GoogleCloudPlatform/gcloud-node#1376]
Is there a timeline for when datastore will include IN and Not Equals filters? Or if it will be supported?

**Comment by stephenplusplus** [comment]
// @pcostell 

Also, what is the ideal venue for questions like these?

**Comment by pcostell** [comment]
You can redirect these to the google-cloud-datastore github project.

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/google-cloud-datastore#127

**Comment by simoami** [comment]
@stephenplusplus Just want to weigh in and said I'm another user blocked by lack of support for IN, OR and NE. I'm working on a connector for the loopback framework, while also using in a project. Looking at the google-cloud-datastore project, it seems to be specific to Java and Python. Is the Node version dependent any of them? If yes, then I understand.

Thanks
