### ISSUE TITLE
Incorrect memcache url in app.yaml

### ISSUE THREAD

**Issue by sankalpk** [GoogleCloudPlatform/gcloud-node#1377]
In appengine/express-memcached-session/app.yaml the MEMCACHE_URL is listed as localhost:11211, when it should actually be memcache:11211

**Comment by stephenplusplus** [comment]
Want to send a PR over to the nodejs-docs-samples repo? https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/express-memcached-session/app.yaml

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/nodejs-docs-samples#123
