### ISSUE TITLE
upload or download file error

### ISSUE THREAD

**Issue by uqutub** [GoogleCloudPlatform/gcloud-node#1389]
```js
// download file function...
var bucket = gcs.bucket('xxx.appspot.com');
bucket.file('avatar_2_99737.jpg').download({
   destination: '/testAbc/avatar_2_99737.jpg'
}, function(err) {
   console.log(err)
});
```
**Whenever i try to upload or download file i got this error.**
```
../GoogleCloudStorage/node_modules/mime/mime.js:70
  var ext = path.replace(/.*[\.\/\\]/, '').toLowerCase();
                        ^

_TypeError: path.replace is not a function_
```

**Comment by stephenplusplus** [comment]
I haven't been able to reproduce. As it is currently, we don't use the module `mime`. Could this be coming from a line of code that wasn't in your example? If not, a simple reproducible sample repo would be great to help debug.

**Comment by stephenplusplus** [comment]
I'm going to close, but if you can share a small repo that I can clone to reproduce the bug, I'll re-open.

**Comment by stephenplusplus** [comment]
Another issue (#1445) popped up with this same error. We traced it back to an argument type mismatch. gcloud takes an object with either a `keyFilename` string or a `credentials` object. In #1445, an object was provided, but under the name `keyFilename`. String functions were trying to be called on that object, which is what threw the error. Naming it `credentials` instead solved the problem.
