### ISSUE TITLE
Get kinds list from datastore

### ISSUE THREAD

**Issue by mik115** [GoogleCloudPlatform/gcloud-node#1390]
Hi,
I'd like to retrieve a complete list of kinds from datastore. 
There' s any way using gcloud-node?

thanks in advance

**Comment by stephenplusplus** [comment]
@pcostell

**Comment by jgeewax** [comment]
AFAIK there actually isn't a reliable way to do that in an authoritative way. I believe we have a cache of the Kinds (updated every so often, for the UI), but it's not a reliable strongly-consistent method of figuring out which kinds are in your Datastore...

**Comment by mik115** [comment]
hi, 
thanks @jgeewax for the quick reply.
There's any intention to implement this basic functionality in the future? and if the response is yes there are any deadlines?

thanks

**Comment by pcostell** [comment]
You can do this with a [metadata query][https://cloud.google.com/datastore/docs/concepts/metadataqueries#kind_queries]. 

There is a snippet there that shows how to get a list of all kinds. This queries your actual data so it will be up-to-date, but as with other global queries it will be impacted by eventual consistency.

**Comment by mik115** [comment]
@pcostell Great! 
Thanks for the answer!
