### ISSUE TITLE
File inconsistent after rewriting

### ISSUE THREAD

**Issue by Gr1g0ry** [GoogleCloudPlatform/gcloud-node#1391]
1. I save "SOME TEXT" to Google Cloud Storage file (__OK__)
1. I read "SOME TEXT" from Google Cloud Storage file (__OK__)
1. I save "OTHER TEXT" to Google Cloud Storage file (__OK__)
1. I read "OTHER TEXT" from Google Cloud Storage file (__ERROR__). I get "SOME TEXT" instead of "OTHER TEXT".

There are correspondent mocha tests:

``` javascript
var assert = require('assert');
var config = require('config');
var gcloud = require('gcloud');
var gcs = gcloud.storage({
  keyFilename: config.gcloud.keyFilename, // should be changed to your "keyFilename"
  projectId:   config.gcloud.projectId    // should be changed to your "projectId"
});
var myBucket = gcs.bucket(config.buckets.test.name); // should be changed to your "bucket name"
var file = myBucket.file('someFile');

describe('Double Search Test', function () {

  it('Writing "SOME TEXT" to file', function (done) {
    file.save('SOME TEXT', {resumable: false, metadata: {contentType: 'text/plain' }}, done);
  });

  it('reading "SOME TEXT" from file', function (done) {
    var text = '';
    file.createReadStream()
      .on('error', function (err) { done(err); })
      .on('data', function (chunk) { text += chunk; })
      .on('end', function () {
        assert.equal('SOME TEXT', text);
        done(null);
      });
  });

  it('Writing "OTHER TEXT" to file', function (done) {
    file.save('OTHER TEXT', {resumable: false, metadata: {contentType: 'text/plain' }}, done);
  });

  it('reading "OTHER TEXT" from file', function (done) {
    var text = '';
    file.createReadStream()
      .on('error', function (err) { done(err); })
      .on('data', function (chunk) { text += chunk; })
      .on('end', function () {
        assert.equal('OTHER TEXT', text);
        done(null);
      });
  });
});
```

There are tests results:
```shell
  Double Search Test
    ✓ Writing "SOME TEXT" to file (1130ms)
    ✓ reading "SOME TEXT" from file (723ms)
    ✓ Writing "OTHER TEXT" to file (541ms)
    1) reading "OTHER TEXT" from file


  3 passing (3s)
  1 failing

  1) Double Search Test reading "OTHER TEXT" from file:

      Uncaught AssertionError: 'OTHER TEXT' == 'SOME TEXT'
      + expected - actual

      -OTHER TEXT
      +SOME TEXT
      
      at DestroyableTransform.<anonymous> (test/entities/test-second-saving.js:42:16)


```

But [Google Cloud Storage docs](https://cloud.google.com/storage/docs/consistency) says:

> When you upload an object to Cloud Storage, and you receive a success response, the object is immediately available for download and metadata operations from any location where Google offers service. This is true whether you create a new object or overwrite an existing object.

**Comment by Gr1g0ry** [comment]
It is interesting that I see correct "OTHER TEXT" through Google Console web inerface after performing tests.

**Comment by jgeewax** [comment]
Are you 100% certain that these things are being executed in exact order? For example, is it at all possible that the it's may be executing in somewhat parallel order? 

Since reads are faster than writes, it wouldn't be surprising if the reading "OTHER TEXT" test executed before the writing "OTHER TEXT" had completed. 

Do you see the same error if you string these together? In other words, if you only execute the next step after `done()` is called?

**Comment by jgeewax** [comment]
Also, can you log the output of the second save just to be 100% certain that it's not throwing an error?

**Comment by stephenplusplus** [comment]
I think the JSON API is having problems -- (JJ: cc them please!)

The new data is saved successfully, but the link (https://storage.googleapis.com/stephen-has-a-new-bucket/1466776492878) returns the first data you saved to the object.

@Gr1g0ry -- the new data is available for download from the console, but see if it's still the stale data when you go to: https://storage.googleapis.com/{bucket}/{fileName}. That's what I'm seeing, and would confirm the problem is happening upstream.

**Comment by Gr1g0ry** [comment]
I'm sure that tests are executed one by one. I mean that next test starts only after perevious has got response from server. I added time output to show it:

``` javascript
var assert = require('assert');
var config = require('config');
var gcloud = require('gcloud');
var gcs = gcloud.storage({
  keyFilename: config.gcloud.keyFilename, // should be changed to your "keyFilename"
  projectId:   config.gcloud.projectId    // should be changed to your "projectId"
});
var myBucket = gcs.bucket(config.buckets.test.name); // should be changed to your "bucket name"
var file = myBucket.file('someFile');

describe('Double Search Test', function () {

  it('Writing "SOME TEXT" to file', function (done) {
    console.log('Start  ' + (new Date()).toISOString());
    file.save('SOME TEXT', {resumable: false, metadata: {contentType: 'text/plain' }}, function (err) {
      console.log('Finish ' + (new Date()).toISOString());
      done(err);
    });
  });

  it('reading "SOME TEXT" from file', function (done) {
    console.log('Start  ' + (new Date()).toISOString());
    var text = '';
    file.createReadStream()
      .on('error', function (err) { done(err); })
      .on('data', function (chunk) { text += chunk; })
      .on('end', function () {
        console.log('Finish ' + (new Date()).toISOString());
        assert.equal('SOME TEXT', text);
        done(null);
      });
  });

  it('Writing "OTHER TEXT" to file', function (done) {
    console.log('Start  ' + (new Date()).toISOString());
    file.save('OTHER TEXT', {resumable: false, metadata: {contentType: 'text/plain' }}, function (err) {
      console.log('Finish ' + (new Date()).toISOString());
      done(err);
    });
  });

  it('reading "OTHER TEXT" from file', function (done) {
    console.log('Start  ' + (new Date()).toISOString());
    var text = '';
    file.createReadStream()
      .on('error', function (err) { done(err); })
      .on('data', function (chunk) { text += chunk; })
      .on('end', function () {
        console.log('Finish ' + (new Date()).toISOString());
        assert.equal('OTHER TEXT', text);
        done(null);
      });
  });
});
```
You can see that tests go in right order:

``` shell
  Double Search Test
Start  2016-06-25T04:57:04.546Z
Finish 2016-06-25T04:57:05.396Z
    ✓ Writing "SOME TEXT" to file (851ms)
Start  2016-06-25T04:57:05.399Z
Finish 2016-06-25T04:57:05.520Z
    ✓ reading "SOME TEXT" from file (121ms)
Start  2016-06-25T04:57:05.521Z
Finish 2016-06-25T04:57:05.958Z
    ✓ Writing "OTHER TEXT" to file (437ms)
Start  2016-06-25T04:57:05.959Z
Finish 2016-06-25T04:57:06.077Z
    1) reading "OTHER TEXT" from file


  3 passing (2s)
  1 failing

  1) Double Search Test reading "OTHER TEXT" from file:

      Uncaught AssertionError: 'OTHER TEXT' == 'SOME TEXT'
      + expected - actual

      -OTHER TEXT
      +SOME TEXT
      
      at DestroyableTransform.<anonymous> (test/entities/test-second-saving.js:52:16)
```

Sometimes when file is already in bucket I have error on first reading:

``` shell
  Double Search Test
Start  2016-06-25T04:54:39.034Z
Finish 2016-06-25T04:54:40.300Z
    ✓ Writing "SOME TEXT" to file (1267ms)
Start  2016-06-25T04:54:40.304Z
Finish 2016-06-25T04:54:40.426Z
    1) reading "SOME TEXT" from file
Start  2016-06-25T04:54:40.430Z
Finish 2016-06-25T04:54:40.885Z
    ✓ Writing "OTHER TEXT" to file (456ms)
Start  2016-06-25T04:54:40.887Z
Finish 2016-06-25T04:54:41.000Z
    ✓ reading "OTHER TEXT" from file (113ms)


  3 passing (2s)
  1 failing

  1) Double Search Test reading "SOME TEXT" from file:

      Uncaught AssertionError: 'SOME TEXT' == 'OTHER TEXT'
      + expected - actual

      -SOME TEXT
      +OTHER TEXT
      
      at DestroyableTransform.<anonymous> (test/entities/test-second-saving.js:31:16)
```

**Comment by stephenplusplus** [comment]
I modified the test script to show the problem happens when you use the JSON API directly: https://github.com/stephenplusplus/gissue-1391

**Comment by Capstan** [comment]
Are you happening to set `Cache-Control` metadata at all? Is there a way we can get a copy of the request and response headers for each (write plus failed read)?

**Comment by stephenplusplus** [comment]
@Capstan can you see if you can reproduce it with this repo: https://github.com/stephenplusplus/gissue-1391 -- just added instructions on how to run from the readme, which will log requests and responses. Feel free to tweak the code in `test.js` if necessary.

**Comment by stephenplusplus** [comment]
Got the code to work if we ask for a non-cached copy in the download request:

```
'cache-control': 'no-cache, no-store, max-age=0, must-revalidate'
```

Would it be expected for us to automatically set that header in this library when a user requests to download a file?

**Comment by Capstan** [comment]
No; we obey the `cacheControl` metadata attached to the object. So now the question is, if you get the object metadata, what does that `cacheControl` say? And did you ask for it?

**Comment by stephenplusplus** [comment]
My bucket has a predefinedAcl giving `allUsers` read rights. This is the response right after uploading the file.

```js
// GET https://www.googleapis.com/storage/v1/b/stephen-has-a-new-bucket/o/1467059644713
{
  kind: 'storage#object',
  id: 'stephen-has-a-new-bucket/1467059644713/1467059645112000',
  selfLink: 'https://www.googleapis.com/storage/v1/b/stephen-has-a-new-bucket/o/1467059644713',
  name: '1467059644713',
  bucket: 'stephen-has-a-new-bucket',
  generation: '1467059645112000',
  metageneration: '1',
  timeCreated: '2016-06-27T20:34:05.071Z',
  updated: '2016-06-27T20:34:05.071Z',
  storageClass: 'STANDARD',
  size: '3',
  md5Hash: 'FJYD5sA1FjYqjaI/Yk25RQ==',
  mediaLink: 'https://www.googleapis.com/download/storage/v1/b/stephen-has-a-new-bucket/o/1467059644713?generation=1467059645112000&alt=media',
  crc32c: '/7oBBA==',
  etag: 'CMC9i4iHyc0CEAE='
}
```

**Comment by Capstan** [comment]
If you have a publicly readable object and you've not overridden `Cache-Control`, then you get 3600s by default. It appears to be documented in [XML API Standard Headers](https://cloud.google.com/storage/docs/xml-api/reference-headers#standard) but not in the [JSON API metadata](https://cloud.google.com/storage/docs/json_api/v1/objects#cacheControl).

So, you're getting caching behavior. You can override it by setting `cacheControl: "max-age=0"` in JSON metadata for your uploads, or not using `publicRead`.

**Comment by stephenplusplus** [comment]
Good to know, thanks. Does that explain it for your experiences, @Gr1g0ry?

Maybe we should add a cache option to download() that will use the headers I used above. Also, we could put a cache option on upload() that takes a number that would get set for maxAge.

**Comment by Gr1g0ry** [comment]
Thank you very much. You investigation is brilliant. I added `cacheControl: "max-age=0" ` it works fine for me.

**Comment by stephenplusplus** [comment]
Okay, seems simple enough. If anyone stumbles upon this issue and wants something like a `cache` option that I mentioned above, feel free to vote for it / send a PR.
