### ISSUE TITLE
bucket api using a lot of memory due to retry-request

### ISSUE THREAD

**Issue by richtera** [GoogleCloudPlatform/gcloud-node#1392]
Since the bucket api is using the retry-request module it's growing my node heap to around 7G due to large files being up and downloaded. Node is not willing to give up all that memory right away. Since I really don't need retry for such large requests and would rather know when an error happens due to rate restrictions is there a way to turn of the usage of retry-request?
Thanks
Andy

**Comment by stephenplusplus** [comment]
You can disable the retries by providing `{ maxRetries: 0 }` to Storage:

```js
var gcs = gcloud.storage({ maxRetries: 0 });
```

Let me know if that helps.

**Comment by richtera** [comment]
That will prevent a retry, but I need it to revert to using a plain request rather than a retry-request. The retry-request will pipe all of the request and response data into a streamcache which is what's taking up all the memory. I need to be able to disable caching of the stream data in memory.
Thanks
Andy

**Comment by stephenplusplus** [comment]
Ah, I see. I didn't realize stream-cache was keeping that in memory indefinitely. I'll see if I can think of something to release those after we don't need the cache stream anymore.

**Comment by richtera** [comment]
It's not indefinitely and does get eventually released but node does not free up the underlying OS memory for quite a while and maybe never. And for large files I would rather have it fail than clobbering memory to this extent.
Thanks
Andy

**Comment by stephenplusplus** [comment]
I would guess the buffers a stream-cache instance retains go out of scope when the stream itself goes out of scope. But I think we could try only retaining that data until we pipe a single stream to it.

In other words, I believe stream-cache now is holding internally all of the data it receives, because it thinks we want to replay them to possibly multiple streams. I think we should modify it to stop holding data internally *after* it has already had a stream connected to it. I'll put this into code and see if this works. Hope you won't mind if I ping you to try it out!

**Comment by stephenplusplus** [comment]
@richtera I made a branch of retry-request that removes stream-cache completely, instead just using a normal passthrough stream to hold data. Can you see if it improves the memory usage in your project?

```sh
$ npm install --save stephenplusplus/retry-request#rm-stream-cache
```

**Comment by richtera** [comment]
Works great. My memory footprint went from 7G to 700M :)
Thanks.
Andy

**Comment by stephenplusplus** [comment]
Great! Thanks for catching this, it's going to be very appreciated by our users :) I'm going to run it through a few more tests, then merge and release 👍

**Comment by stephenplusplus** [comment]
Released the [fix](https://github.com/stephenplusplus/retry-request/commit/1afb91a2b75be74104fb01f67dbc45684fcbcc3b) in retry-request under 1.3.1. gcloud will automatically pick it up in new installs. Thanks again!
