### ISSUE TITLE
Storage: file.copy, file.move(, others?) don't accept "gs://" URLs

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/gcloud-node#1395]
I was rather surprised when this command:

```js
bucket.file("foo").copy("gs://otherbucket/something", cb)
```

created an object in the original bucket in a "gs:/" subdirectory. I see how to do what I want by passing a file or bucket instead of a string, but it seems like this could easily be supported with something like this:

```diff
--- lib/storage/file.js
+++ lib/storage/file.js
@@ File.prototype.copy = function(destination, callback) { @@
  if (is.string(destination)) {
+   if (destination.startsWith("gs://") {
+     var parsed = /^gs\:\/\/([a-z_\.\-]+)\/(.+)$/.exec(destination);
+     // assert parsed.length === 3
+     destBucket = parsed[1];
+     destName = parsed[2];
+   } else {
+     destBucket = this.bucket;
+     destName = destination;
+   }
-   destBucket = this.bucket;
-   destName = destination;
  } else if (destination.constructor &&
```

(Happy to make a PR with something like that.)

**Comment by stephenplusplus** [comment]
I'm totally cool with that. A PR would be great! Only note is to use indexOf instead of startsWith since we still support 0.12. Thanks!

**Comment by zbjornson** [comment]
Thanks. Heading out of town, probably won't get to a PR until ~10 July.

**Comment by stephenplusplus** [comment]
Sounds good, safe travels!
