### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by vjameson** [GoogleCloudPlatform/gcloud-node#1396]
I'm unable to install gcloud:

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "gcloud"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.5
npm ERR! path /usr/local/lib/node_modules/gcloud/node_modules/gcs-resumable-upload/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/gcloud/node_modules/gcs-resumable-upload/cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/gcloud/node_modules/gcs-resumable-upload/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by stephenplusplus** [comment]
I think this is an npm bug. Can you try now?

**Comment by stephenplusplus** [comment]
(I republished gcs-resumable-upload)

**Comment by vjameson** [comment]
That worked. Thank you!

**Comment by stephenplusplus** [comment]
Great, thank you for letting me know!
