### ISSUE TITLE
deleting a nonexistent record from datastore does not return an error

### ISSUE THREAD

**Issue by lowagner** [GoogleCloudPlatform/gcloud-node#1397]
it would be nice if it did, then we wouldn't have to run a check on the full API response in addition to the error message, before proceeding safely...

only checked on version 0.36

**Comment by stephenplusplus** [comment]
@pcostell should we return an error in this case? And if so, what logic should we use to determine an error?

**Comment by pcostell** [comment]
This is expected. In particular, the [Datastore API documentation](https://github.com/googleapis/googleapis/blob/master/google/datastore/v1beta3/datastore.proto#L257) states:

```
// The key of the entity to delete. The entity may or may not already exist.
// Must have a complete key path and must not be reserved/read-only.
Key delete = 7;
```

Doing this in the client would require doing a transaction first with a `Lookup`. I'm not sure it makes sense to provide this functionality, as it would require doing multiple round trips to delete. In the case of `delete`, the end result is the same regardless of if the entity existed or not (the entity will not exist).

**Comment by lowagner** [comment]
i guess the idea is if you chain deletes; if you delete something, then you always delete something else (which is related to the first).  in the event that someone goes to the "delete" page again, the first delete will go through without issue, and the second delete may fail for weird reasons...  i was just getting the whole nodejs server to crash.

anyhoo, it's something i can check, through the full response, checking if fullResponse.indexUpdates === 0, right?
