### ISSUE TITLE
Uncaught TypeError w/ GRPC

### ISSUE THREAD

**Issue by NawarA** [GoogleCloudPlatform/gcloud-node#1398]
The following error is occurring sporadically, and causing an unrecoverable error in our production process:
```
/.../node_modules/grpc/src/node/src/credentials.js:108
     callback(code, message, metadata._getCoreRepresentation());
     ^
TypeError: The callback's first argument must be a status code
   at TypeError (native)
   at /.../node_modules/grpc/src/node/src/credentials.js:108:7
   at /.../node_modules/grpc/src/node/src/credentials.js:124:9
   at /.../node_modules/google-auth-library/lib/auth/oauth2client.js:286:14
   at /.../node_modules/google-auth-library/lib/auth/jwtclient.js:138:16
   at Request._callback (/.../node_modules/gtoken/lib/index.js:220:9)
   at self.callback (/.../node_modules/request/request.js:200:22)
   at emitOne (events.js:90:13)
   at Request.emit (events.js:182:7)
   at Request.onRequestError (/.../node_modules/request/request.js:831:8)
```

We're using v0.33

**Comment by stephenplusplus** [comment]
Is there a chance you've manually installed `grpc` as your own dependency? It seems like a version conflict must have occurred; gcloud-node is being given the wrong version of grpc.

It might not hurt to try upgrading to the latest gcloud, v0.36.0: https://github.com/GoogleCloudPlatform/gcloud-node/releases

**Comment by stephenplusplus** [comment]
@NawarA I'm going to close as I can't reproduce. Please reply back if there are still issues.

**Comment by NawarA** [comment]
Feel free to close, if issue arises in the future, we can then reopen

**Comment by gargol** [comment]
The same thing happens for my production environment. Am using `google-cloud@0.39.0` and what I found odd was that two modules inside the library were using completely differenr grpc versions as follows:
```
+-- google-cloud@0.39.0
| +-- @google-cloud/bigquery@0.1.2
| | +-- @google-cloud/common@0.3.0
| | | +-- array-uniq@1.0.3
| | | +-- ent@2.2.0
| | | +-- google-auto-auth@0.2.4
| | | +-- grpc@0.14.1
```
and
```
| +-- @google-cloud/language@0.1.2
| | +-- arguejs@0.2.3
| | +-- google-gax@0.6.0
| | | +-- eventemitter2@1.0.5
| | | +-- grpc@0.15.0
```
How would you advice to address this issue best ?

**Comment by stephenplusplus** [comment]
Can you try upgrading google-cloud? We've worked to mitigate duplicate dependencies as much as possible.

**Comment by gargol** [comment]
Yeap, will do. Any suggestion on how issues like this could be addressed on higher application level if they arrasie in the future? My express application crashes irrecoverably and the process ends up being restarted. Maybe there's a better way of handling such errors?

**Comment by stephenplusplus** [comment]
I'm not sure, but I think that's a question on Express best practices, which is probably best posed to that community.
