### ISSUE TITLE
Datastore query fails when including a sort and a filter.

### ISSUE THREAD

**Issue by bamapookie** [GoogleCloudPlatform/gcloud-node#1402]
gcloud datastore.runQuery fails with a "412 Precondition Failed" when the query contains a filter.  Below is a mocha test that creates a new datastoreKind, adds a record, then queries for the record.  The only difference between the queries is that the second query contains a filter that should match.

    'use strict';

    var datastore = require('gcloud').datastore({
        projectId: 'test-playground',
        keyFilename: './serviceAccountCredentials.json'
    });
    var kind = 'Scratch-' + require('node-uuid').v4();

    describe('Datastore Filter', function () {
        it('should add two records', function (done) {
            datastore.upsert({
                key: {namespace: 'Scratch', path: [kind]},
                data: {category: 'Scratch', date: new Date(), text: 'Find me too!'}
            }, function () {
                datastore.upsert({
                    key: {namespace: 'Scratch', path: [kind]},
                    data: {category: 'Scratch', date: new Date(), text: 'Find me!'}
                }, done);
            });
        });
        it('should find records sorted by date', function (done) {
            var query = datastore
                .createQuery('Scratch', kind)
                .order('date', {descending: true});
            datastore.runQuery(query, function (err) {
                if (err) done(err);
                else done();
            });
        });
        it('should find records matching a filter', function (done) {
            var query = datastore
                .createQuery('Scratch', kind)
                .filter('category', 'Scratch');
            datastore.runQuery(query, function (err) {
                if (err) done(err);
                else done();
            });
        });
        it('should find records matching a filter sorted by date', function (done) {
            var query = datastore
                .createQuery('Scratch', kind)
                .filter('category', 'Scratch')
                .order('date', {descending: true});
            datastore.runQuery(query, function (err) {
                if (err) done(err);
                else done();
            });
        });
    });

**Comment by bamapookie** [comment]
Note:  Updated to include that the combination of sort and filter causes the failure.

**Comment by stephenplusplus** [comment]
// @pcostell

**Comment by pcostell** [comment]
The combination of filters requires an index to be defined. You should have an `index.yaml` file that includes:

```
indexes:
  - kind: Scratch
    properties:
    - name: category
    - name: date
      direction: desc
```

**Comment by bamapookie** [comment]
Thanks.  I updated the original comment to be consistent with the updated code.
