### ISSUE TITLE
loading data using partition decorators by row timestamp field,

### ISSUE THREAD

**Issue by zloof** [GoogleCloudPlatform/gcloud-node#1415]
Hi,
1.How can I load data (using streaming - "table.insertAll") to a partition decorators
(https://cloud.google.com/bigquery/docs/partitioned-tables#loading_data_using_partition_decorators)
2. can I do it by providing field name from the data row (the field is in timestamp format ), and insert each row to the relevant partition by getting the date from the timestamp.

Thanks 
Nir

**Comment by stephenplusplus** [comment]
Sorry for the delay, I'll look into this as soon as I can. You might get a quicker/better response by posting on StackOverflow. If you do post, please cross-link so others can follow along.

**Comment by stephenplusplus** [comment]
Closing as I believe we addressed this adequately here: https://github.com/GoogleCloudPlatform/gcloud-node/issues/1455

Let me know if that's incorrect. Thanks!
