### ISSUE TITLE
create serving_url on image uploads

### ISSUE THREAD

**Issue by reco** [GoogleCloudPlatform/gcloud-node#1419]
there is currently no way to generate a serving_url of a image blob inside google cloud storage. 

there should be away to do this similar to the python api: 

from: https://cloud.google.com/appengine/docs/python/refdocs/google.appengine.api.images#google.appengine.api.images.delete_serving_url

google.appengine.api.images.get_serving_url(blob_key, size=None, crop=False, secure_url=None, filename=None, rpc=None)

**Comment by stephenplusplus** [comment]
I believe this is beyond the scope of what we support. If it isn't possible from the Storage JSON API, we don't have a way to offer this. Do you know how we could support this?

**Comment by stephenplusplus** [comment]
Anyone can feel free to comment with ideas of how we can support this, and I'll re-open. For now, I think this is beyond our scope.
