### ISSUE TITLE
I don't understand how to use query.groupBy 

### ISSUE THREAD

**Issue by CVarisco** [GoogleCloudPlatform/gcloud-node#1426]
Hi,

I've used query.groupBy as per example on a simple get operation (list all entities of a kind grouped by property):
`groupBy(['prop']);`

With one arguments I have the complete list of kind without any grouping applied.
With two arguments I have this response:
```javascript
{
  "code": 412,
  "metadata": {
    "_internal_repr": {}
  }
}
```

Can you please help me understand how am I supposed to use the groupBy API?

**Comment by stephenplusplus** [comment]
I think this is a matter of setting the correct indexes to support that query. Maybe a search on the Datastore docs as well as this repo's issues will give some ideas. I'm going to close as this isn't a bug with our library. StackOverflow would likely be a better place for this question. Feel free to let me know if you can't find any answers, and we will bug the Datastore team :)
