### ISSUE TITLE
bigquery:  insert directcly to specific partition 

### ISSUE THREAD

**Issue by zloof** [GoogleCloudPlatform/gcloud-node#1455]
please add support to insert partition table directly to a specific partition like 
bq load  --replace --source_format=NEWLINE_DELIMITED_JSON mydataset.table1$20160101'
(see https://cloud.google.com/bigquery/docs/creating-partitioned-tables#restating_data_in_a_partition )

thanks

**Comment by stephenplusplus** [comment]
I think you can do this currently like this:

```js
var gcloud = require('gcloud')
var bigquery = gcloud.bigquery()
var dataset = bigquery.dataset('a_dataset')
var table = dataset.table('a_partitioned_table')
var partition = dataset.table('a_partitioned_table$20160727')

dataset.get({ autoCreate: true }, err => {
  if (err) throw err

  table.get({
    autoCreate: true,
    schema: 'name',
    timePartitioning: {
      type: 'DAY'
    }
  }, err => {
    if (err) throw err

    partition.createWriteStream('json')
      .on('error', err => { throw err })
      .on('finish', () => { console.log('success!') })
      .end(JSON.stringify({ name: 'stephen' }))
  })
})
```

Let me know if that's not what you're looking for.

Also, does this answer #1415?

**Comment by zloof** [comment]
Can it be dane with table.insert ?
It return: partition table not support streaming

**Comment by stephenplusplus** [comment]
I believe that's a limitation of the API in its current state, so it's nothing we can get around. In the event its supported in the future (I don't know if it will be), it should work immediately with our library's `insert` method.

**Comment by zloof** [comment]
OK thanks 
I will stick to table.insert and templateSuffix

**Comment by stephenplusplus** [comment]
Cool. Is it okay to close this issue and #1415 or is there more we need to do with this library?

**Comment by stephenplusplus** [comment]
Going to close. Just let me know if we need to re-open.
