### ISSUE TITLE
API documentation is not available.

### ISSUE THREAD

**Issue by gromtech** [GoogleCloudPlatform/gcloud-node#1457]
https://cloud.google.com/gcloud-node is not available during 3 days...

**Comment by stephenplusplus** [comment]
Our docs are at https://googlecloudplatform.github.io/gcloud-node -- where did you find the cloud.google link?

**Comment by gromtech** [comment]
The browser always redirects me to this url from https://googlecloudplatform.github.io/gcloud-node

**Comment by stephenplusplus** [comment]
Oh, I wonder if that's a cache issue from something that happened recently: https://github.com/GoogleCloudPlatform/gcloud-common/issues/154. Can you try in an incognito window or going to an inner page like https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.37.0/gcloud?method=bigquery directly?

**Comment by gromtech** [comment]
https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.37.0/gcloud?method=bigquery works in incognito mode

**Comment by gromtech** [comment]
Thank you

**Comment by stephenplusplus** [comment]
No problem!
