### ISSUE TITLE
catch Exceptions in pubsub

### ISSUE THREAD

**Issue by mytholog** [GoogleCloudPlatform/gcloud-node#1465]
#### Environment details

  - OS: Mac (Capitan)
  - Node.js version: 4.4.7
  - gcloud-node version: 0.37.0

#### Steps to reproduce

  1. require `gcloud-node`
  2. run code from https://github.com/GoogleCloudPlatform/nodejs-getting-started/tree/master/6-pubsub

````js
"stack":[
  "Error: Deadline Exceeded",
  " at Function.GrpcService.decorateError_ (/node_modules/gcloud/lib/common/grpc-service.js:482:34)",
  " at Object.callback (/node_modules/gcloud/lib/common/grpc-service.js:247:35)",
  " at /node_modules/gcloud/node_modules/grpc/src/node/src/client.js:420:14"
],
"level":"error",
"message":"uncaughtException: Deadline Exceeded"
```

**Comment by stephenplusplus** [comment]
Thanks for the report. We have a couple of blocking PRs to get to first, but I will look into this as soon as I can.

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/nodejs-getting-started#68

**Comment by stephenplusplus** [comment]
I tried to reproduce and so far things are working as expected. I moved the issue over to the tutorial's repo. I'm subscribed to the new issue, so I'll be watching to see if something needs to be done in this repo.
