### ISSUE TITLE
Releasing the modules

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#1471]
Our repo has been split up into ready-to-publish modules. This issue will track what needs to be done before we can get the next release out.

- [x] Make a module-friendly docs site: [PR](https://github.com/GoogleCloudPlatform/gcloud-common/pull/157)
- [x] Modify our JSDocs -> JSON build process to suit the changes from [the docs site PR](https://github.com/GoogleCloudPlatform/gcloud-common/pull/157)
  - [x] Combine `@classdesc` docs with `@description` docs
  - [x] Write package specific *Getting Started* docs in `@description` tag
  - [x] Automate <kbd>toc.json</kbd> creation
  - [x] Move configuration object documentation to a *Getting Started* markdown file
  - [x] Update all links to configuration objects
- [x] Publish all `@google-cloud/service` modules to npm at `0.1.0`
- [x] Publish the umbrella package, `google-cloud`, at `0.38.0`
- [x] Revert README change

**Comment by stephenplusplus** [comment]
@callmehiphop please update the post if I got any of those steps wrong / left anything out.

**Comment by nvartolomei** [comment]
`Publish the umbrella package, google-cloud`

next time, please, update readme at the same time you publish new npm package or change the active branch on github so people do not read broken readme/doc or add notices like kubernetes repo does.

**Comment by stephenplusplus** [comment]
Yep, we should have left a message for users directing them to the accurate docs here: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.37.0/gcloud. I'll do that now, sorry for the confusion.

**Comment by stephenplusplus** [comment]
We're published!
