### ISSUE TITLE
Broken example in documentation

### ISSUE THREAD

**Issue by nvartolomei** [GoogleCloudPlatform/gcloud-node#1472]
This one gives me an error.

```js
var datastoreClient = datastore({
  projectId: 'grape-spaceship-123',
  keyFilename: '/path/to/keyfile.json'
});
```
adding `new` keyword makes it work:

```js
var datastoreClient = new datastore({
  projectId: 'grape-spaceship-123',
  keyFilename: '/path/to/keyfile.json'
});
```

**Comment by nvartolomei** [comment]
Actually, if I do it this way the new keyword is not needed:

```
const gcloud = require('gcloud')({
  projectId: '...',
})
const dsClient = gcloud.datastore()
```

**Comment by stephenplusplus** [comment]
Yes, sorry for this confusion. master represents the latest state of the repository, so if you were cloning directly from master, the readme would be accurate. The latest version on npm is 0.37.0 -- those docs can be found here: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.37.0/gcloud

I'll add a note in the readme that directs users to those docs. Sorry again!
