### ISSUE TITLE
Unparsed link on bigquery.table.export page

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/gcloud-node#1499]
A link on [this page](https://googlecloudplatform.github.io/gcloud-node/#/docs/google-cloud/0.38.3/bigquery/table?method=export) (CTRL-F for "http://goo.gl/dKWIyS") doesn't seem to be recognized by the Markdown parser.

When I looked at [this file](https://github.com/GoogleCloudPlatform/gcloud-node/blob/c835d333fb313c7c5c3c5dc9c3d0ea6db8927bba/packages/bigquery/src/table.js#L261) (which I believe is the source of that page), it seemed like the associated code was indeed valid Markdown according to [this Markdown parsing tool](http://markdownlivepreview.com/).

**Comment by stephenplusplus** [comment]
Thanks for the heads up! @callmehiphop -- is this a bug, or is markdown not supported there?

**Comment by callmehiphop** [comment]
Right now it's not supported there, I believe that link lives inside of a comment delimiter of that specific example. So `dox` sees it as a JS comment and not something to be formatted and the Angular app doesn't parse example captions as markdown snippets.

**Comment by stephenplusplus** [comment]
Will `<a>` links work?

**Comment by callmehiphop** [comment]
I believe so!

**Comment by stephenplusplus** [comment]
@ace-n any interest in sending a PR to use just normal `<a href="">...</a>` style?
