### ISSUE TITLE
Redirect Loop!

### ISSUE THREAD

**Issue by 3vivekb** [GoogleCloudPlatform/gcloud-node#1504]
Go here!
https://googlecloudplatform.github.io/gcloud-node/#/docs/guides/authentication

Found it here:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/bigquery/getting_started.js

**Comment by stephenplusplus** [comment]
Woops!

**Comment by quartzmo** [comment]
@3vivekb Thanks for catching this! I was having the same problem using an earlier version of the site, and fixed it just by upgrading, thanks to this.
