### ISSUE TITLE
URLs not containing an explicit version drop their "method" argument

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/gcloud-node#1511]
For example, [this link](https://googlecloudplatform.github.io/gcloud-node/#/docs/google-cloud/latest/storage/bucket?method=acl.add) to a non-specific version has a method argument attached to it - but it _isn't_ honored.

[This link](https://googlecloudplatform.github.io/gcloud-node/#/docs/google-cloud/0.38.3/storage/bucket?method=acl.add) is specific to a version - so its method argument _is_ honored.

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/gcloud-common#166
