### ISSUE TITLE
App Engine dev tries and fails to reach Datastore

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#233]
## Updated 12/12/14

I'm running https://github.com/stephenplusplus/sillycloud/tree/gae with an app.yaml and Dockerfile copied from the [appengine quickstart project](https://github.com/googlecloudplatform/appengine-nodejs-quickstart). I only made small modifications to match my structure.

When I run `gcloud preview app run .` I see that my routes are correctly configured. I have a handler for GET requests to /api/users: https://github.com/stephenplusplus/sillycloud/blob/master/actions.js#L10. The first api request, `runQuery`, is where I start experiencing errors.

**NOTE: I'm using my branch from #328 to test against**

See https://github.com/GoogleCloudPlatform/gcloud-node/issues/233#issuecomment-57473169 for the error I'm experiencing.

**Comment by jgeewax** [comment]
Are we talking about the App Engine dev server? or the GCD dev server (https://cloud.google.com/datastore/docs/tools/devserver) ?

**Comment by ryanseys** [comment]
https://cloud.google.com/datastore/docs/tools/devserver

**Comment by stephenplusplus** [comment]
I think this will be resolved by #513. "Managed VMs default service account doesn't include scopes to access datastore, pubsub, etc."
