### ISSUE TITLE
How are you using gcloud?

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#274]
As discussed, BigQuery and more example applications using this library were recent priority. Now that BigQuery has launched (YAY!), I'd like to draw some more attention to the latter. Currently we have an Examples section in the README that has only 1 item in it  :neutral_face:. I'd like to suggest we add a couple more and vow to maintain them. Simple is better.

[stephenplusplus/gcloud-keystore](https://github.com/stephenplusplus/gcloud-keystore) seems promising. So, @stephenplusplus, can we add this to the list?

Please list ideas for more examples we can implement or other example repos!

#### Included so far:
- [gitnpm](https://github.com/stephenplusplus/gitnpm)
- [gcloud-keystore](https://github.com/stephenplusplus/gcloud-keystore)

**Comment by janesconference** [comment]
Hello there! Still unannounced (will be in a few days), but online, my project uses gcloud-node on the server side. Here's the url: https://wav.hya.io

**Comment by ryanseys** [comment]
@janesconference very cool application! Thanks for the addition. Once you launch, feel free to send a pull request to add your link to [the list](https://github.com/GoogleCloudPlatform/gcloud-node#example-applications) of sites using it if you'd like to include it! :)

**Comment by stephenplusplus** [comment]
Thanks for the feedback! This issue is pretty hard to find for newcomers now, so I'll just continue snooping on https://www.npmjs.com/browse/depended/gcloud to see who uses us :)
