### ISSUE TITLE
storage: Support for folders

### ISSUE THREAD

**Issue by pierre-b** [GoogleCloudPlatform/gcloud-node#337]
Hi, 

Is it possible to upload a file into a folder ?

Thanks

**Comment by stephenplusplus** [comment]
Going to close as all signs point to this working. If you still can't get it working, feel free to re-open with more details. If you have ideas for how we can improve the documentation or API to make a better experience for others, those are always welcome as well.

**Comment by Marak** [comment]
There is some issue either here or in github.com/pkgcloud/pkgcloud which is causing `encodeURIComponent` related issue on downloading files.

Seems that the outgoing URI isn't being encoded automatically?

Don't have much time to dig into it now, but solution was to use `encodeURIComponent` on outgoing path for downloading file inside folder. Uploading seemed to have encoding / decoding working correctly.

Will update if I ever get more information. Patch is holding here.

**Comment by stephenplusplus** [comment]
If the request is going through `pkgcloud`, that means it's using gcloud@0.10. We're currently on 0.32. Here's the issue which asks for gcloud to be updated: https://github.com/pkgcloud/pkgcloud/issues/452, but the maintainers have some issues with doing it.

In the past, we have missed a few `encodeURIComponent`s, and it's possible 0.10 was before we caught them.
