### ISSUE TITLE
Investigate Google Compute Engine

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#341]

**Comment by stephenplusplus** [comment]
Just an update: @ryanseys is (or might be?) working on a design doc to provide GCE methods to our library. In tandem with a public and collaborative Google Docs document, this issue can track the progress until a PR exists with an implementation.

**Comment by ryanseys** [comment]
Yep yep. It's currently in progress. Will update everyone at stand-up today. Working in a gist right now because it's better than gdoc at code.

**Comment by stephenplusplus** [comment]
Even better -- a code discussion in Arial 12pt is frustrating :)

**Comment by stephenplusplus** [comment]
@ryanseys can you link the gist here?

**Comment by ryanseys** [comment]
I've made it public considering this link is now public: https://gist.github.com/ryanseys/28c9a17fea00899f3ac7

**Comment by stephenplusplus** [comment]
Cool, thanks. @jgeewax are there any team members you know of with heavy Compute experience who could help review Ryan's proposal?

**Comment by ryanseys** [comment]
The most important points to read are the blocks of text at the top of the gist. This describes my thought-process when deciding on using a zone and region level of abstraction. The code and specific method names are up for interpretation and shorter or longer forms may be substituted without consequence. e.g. changing `vpnTunnel` to `vpn` doesn't really matter to me if it makes sense and makes it clear to the developer.

**Comment by bluecmd** [comment]
Any update on this?

**Comment by ryanseys** [comment]
This has been put this on the back-burner for now as we investigate more pressing APIs and features however we welcome contributions from the community if they wish to provide a prototype implementation to get the ball rolling. Take a look at the gist link above if you wish to help contribute to this effort.

**Comment by stephenplusplus** [comment]
Merged!
