### ISSUE TITLE
bug on create cloud

### ISSUE THREAD

**Issue by leibale** [GoogleCloudPlatform/gcloud-node#344]
```javascript
var cloud = require('gcloud').storage({
    projectId: config.get('google:cloud:id'),
    keyFilename: 'path/to/google/key.json'
});
```
and node throw this error:

```javascript
path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.<anonymous> (path/to/project/folder/node_modules/gcloud/node_modules/configstore/node_modules/xdg-basedir/index.js:6:42)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**in version 0.11.0 it's working**

thanks

**Comment by ryanseys** [comment]
Hi, thanks for the report. What is the `typeof config.get('google:cloud:id')`? Is it not a string?

**Comment by ryanseys** [comment]
Or how are you passing in the path to your key? The actual code snippet instead of a fake `path/to/google/key.json` might help us track down the issue.

**Comment by stephenplusplus** [comment]
It looks like a dependency ([user-home](https://github.com/sindresorhus/user-home)) of a dependency ([xdg-basedir](https://github.com/sindresorhus/xdg-basedir)) of a dependency ([configstore](https://github.com/yeoman/configstore)) of our library can't figure out your home directory: https://github.com/sindresorhus/user-home/blob/master/index.js

Is there any reason your system wouldn't be able to satisfy the search for a home directory here? https://github.com/sindresorhus/user-home/blob/master/index.js

If nothing else, it looks like setting the environment variable "HOME" with a path to your home directory will give Configstore a place to read and write files.

**Comment by sindresorhus** [comment]
Configstore should handle that gracefully though: https://github.com/yeoman/configstore/blob/b82690fc401318ad18dcd7d151a0003a4898a314/index.js#L15

**Comment by stephenplusplus** [comment]
I think it's crashing before it gets to that point. https://github.com/sindresorhus/user-home/blob/master/index.js#L13 -- that must be returning undefined to https://github.com/sindresorhus/xdg-basedir/blob/master/index.js#L6

**Comment by sindresorhus** [comment]
Fixed in https://github.com/sindresorhus/xdg-basedir/commit/ec772405e6197bc02d30910b67e2eb34119bc08b

**Comment by sindresorhus** [comment]
It's really annoying we don't have a reliable way to get the home directory in Node... (https://github.com/libuv/libuv/issues/11)

**Comment by stephenplusplus** [comment]
@sindresorhus thanks!

@leibale if you are still experiencing issues with gcloud, please re-open.
