### ISSUE TITLE
send object in cloud config

### ISSUE THREAD

**Issue by leibale** [GoogleCloudPlatform/gcloud-node#345]
now if i want to create cloud i need this code:
```javascript
var gcloud = require('gcloud'),
    myCloud = gcloud.storage({
        keyFilename: 'path/to/key/file.json'
    });
```
i want to send the file content
```javascript
var gcloud = require('gcloud'),
    myCloud = gcloud.storage({
        projectId: ...,
        key: ...
    });
```

thanks

**Comment by stephenplusplus** [comment]
I don't understand. Can you elaborate?

**Comment by leibale** [comment]
now your package know to get path and read it to get the google key, i want to send the google key
i want this because i have a config file and i want to merge the google key with my config

**Comment by stephenplusplus** [comment]
You can pass a `credentials` object: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.12.0?method=gcloud
