### ISSUE TITLE
Clarify what "generation" does in the File.acl method

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#349]
The docs mention that I *can* specify a generation property when adding an ACL, but doesn't give much background on how that works.

Could we add a real life example of when generation is used ? And a link to "learn more about object versioning" ?

References: 
- https://github.com/GoogleCloudPlatform/gcloud-node/blob/6904e1181c585e3e5042d124df6bc295da3e5c42/lib/storage/acl.js#L94
- https://cloud.google.com/storage/docs/object-versioning

**Comment by ryanseys** [comment]
Isn't a description of the generation parameter [seen here](https://github.com/GoogleCloudPlatform/gcloud-node/blob/6904e1181c585e3e5042d124df6bc295da3e5c42/lib/storage/acl.js#L81) sufficient?

Excerpt:

> `@param {int=} options.generation - **File Objects Only** Select a specific revision of this file (as opposed to the latest version, the default).`

 Or would you like a better-described code example?

**Comment by jgeewax** [comment]
I think that covers it if we're looking at the parameter, but since we're giving an example, we should include more detail:

```javascript
/*
 * For file ACL operations, you can also specify a `generation` property 
 * to control access on a specific revision of a file.
 */
```
