### ISSUE TITLE
Docstring for bucket.setMetadata has invalid argument

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-node#370]
From [the code][1]:

```javascript
bucket.setMetadata({
  contentType: 'application/x-font-ttf',
  metadata: {
    my: 'custom',
    properties: 'go here'
  }
}, function(err, metadata) {});
```

[1]: https://github.com/GoogleCloudPlatform/gcloud-node/blob/fcc6123ddb0678f29d9ccd606e81318f988b4fa8/lib/storage/bucket.js#L308

**Comment by ryanseys** [comment]
You're very right. In fact, I don't think buckets have arbitrary `metadata` field you can set on them so all of those are incorrect. I've created #371 in order to hopefully clear this up. Let me know what you think.
