### ISSUE TITLE
cannot perform query with parentheses

### ISSUE THREAD

**Issue by ef7475** [GoogleCloudPlatform/gcloud-node#372]
Hello,
We are using gcloud with NodeJS server to perform queries a Google BigQuery db.
Our server runs on Amazon Beanstalk.

We are running the following query:

```javascript
var bigquery = gcloud.bigquery({
  projectId: 'XXX',
  keyFilename: 'YYY'
});
var query = "SELECT COUNT(id) FROM AAA.BBB";
bigquery.query(query, function(err, rows) {
    if (err) {
      handleError(res,err);
    }
    else {
      res.send(200,rows);
    }
  });
```

it works fine on the development environment, but when installing on Beanstalk, we get the following error:

```
"errors": [
        {
            "domain": "global",
            "reason": "invalidQuery",
            "message": "Encountered \" \"%\" \"% \"\" at line 1, column 18.\nWas expecting:\n    <EOF> \n    ",
            "locationType": "other",
            "location": "query"
        }
    ],
    "code": 400,
    "message": "Encountered \" \"%\" \"% \"\" at line 1, column 18.\nWas expecting:\n    <EOF> \n    "
```

My guess is that somehow the parenthesis in the query are being escaped (because queries without parenthesis works ok). We cannot figure out how to solve this.

Your help will be appreciated.

**Comment by stephenplusplus** [comment]
I'm kind of lost on this one. The query is sent as a JSON payload in a POST request, so it's not being escaped. Since it's working locally but not in that environment, I'm not sure how to debug. Maybe @ryanseys has an idea.

**Comment by ryanseys** [comment]
I'll take a look at this.
