### ISSUE TITLE
Update the README to follow the new format

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#374]
See https://github.com/GoogleCloudPlatform/gcloud-meta/issues/3 for what we're hoping to be the shared (mostly) format.

- [x] builds/pypi/coveralls
- [x] services supported
- [x] quickstart
- [x] example applications
- [x] authorization
- [x] example of bigquery (longer)
- [x] example of datastore (longer)
- [x] example of storage (longer)
- [x] Example: datastore - Dataset#save
- [x] contributing
- [x] license

**Comment by ryanseys** [comment]
I've added a checkbox list based on the meta-link. Authorization could use some code snippets but how much longer do the examples need to be and what would we like to specifically show off that we aren't currently showing off?

**Comment by ryanseys** [comment]
Added authorization clarifications to README. I'd say we are done with this as our examples seem sufficient. @stephenplusplus thoughts?

**Comment by stephenplusplus** [comment]
I'd agree that it all looks good to me. I think the only thing that could be useful is showing `dataset.save`, as that seems to be the one "big" use missing.

**Comment by ryanseys** [comment]
I think we are good here. Feel free to re-open if you have more ideas for how we can improve the README.
