### ISSUE TITLE
Make sure we have all Google Cloud Storage API features covered

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#375]
*edit by @stephenplusplus*

Run a quick audit over the API between gcloud-node Google Cloud Storage to make sure we have all features covered

**Comment by stephenplusplus** [comment]
Missing:

- Channels: "A channel represents the means by which a notification message is sent to an application watching a bucket." https://cloud.google.com/storage/docs/json_api/v1/channels

- Objects -> compose: "Concatenates a list of existing objects into a new object in the same bucket." https://cloud.google.com/storage/docs/json_api/v1/objects/compose

- Objects -> watchAll: "Watch for changes on all objects in a bucket" https://cloud.google.com/storage/docs/json_api/v1/objects/watchAll

Everything else seems to be covered.

**Comment by stephenplusplus** [comment]
#401 is tracking file.compose and #403 for channels.

**Comment by ryanseys** [comment]
Closing this to delegate to respective issues.
