### ISSUE TITLE
Implement publishBatch and pullBatch methods

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#379]
RE: https://github.com/GoogleCloudPlatform/gcloud-node/issues/377#issuecomment-72664423

API specs:
- https://cloud.google.com/pubsub/v1beta1/topics/publishBatch
- https://cloud.google.com/pubsub/v1beta1/subscriptions/pullBatch

Ideally, `publishBatch` could accept messages in a raw or simple format.

**Comment by ryanseys** [comment]
According to https://github.com/GoogleCloudPlatform/gcloud-node/issues/377#issuecomment-72664423 the suggested way of publishing and pulling messages is now through these methods on top of our existing publish and pull methods. We can just rework `publish` to support an array of messages and always use `publishBatch` API call behind the scenes. Similarly, `pull` right now returns 1 message so we can either use `maxEvents: 1` by default to maintain backward compatibility or we can pull many messages, and document the new maxEvents option. Thoughts?

**Comment by stephenplusplus** [comment]
Just accepting an array to `publish` is a great idea. Same for `pull`; just accept an object with `maxCount` (instead of `maxEvents`?) that if absent, will default to 1/current behavior. :+1: 

I'd like to promote the priority of this one, since it breaks every build (which is now 3 builds for each supported platform) - https://travis-ci.org/GoogleCloudPlatform/gcloud-node/jobs/50067298

**Comment by ryanseys** [comment]
SGTM, if you'd like to jump at this one, be my guest. I'm a little occupied this morning.

**Comment by stephenplusplus** [comment]
On it :+1:
