### ISSUE TITLE
Is gcloud-node going to work with iojs?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#380]
Maybe we should add some tests to make sure our build passes using the iojs.org runtime? Not sure if it's worthwhile, but figured I'd toss this out.

**Comment by ryanseys** [comment]
Once travis lands with iojs support (which was [supposed to be today](http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/) but has been rolled back for now) then I say we set up travis to run tests on it, but under [allow_failures](http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail) this way we can phase it in without committing to it entirely.

**Comment by ryanseys** [comment]
For the record, right now 100% of unit tests and 100% of regression tests pass on io.js v1.0.4

**Comment by ryanseys** [comment]
npm install fails though due to a dependency build issue with `sse4_crc32` (issue filed [here](https://github.com/Voxer/sse4_crc32/issues/17))

**Comment by ryanseys** [comment]
Actually I am mistaken, it does not fail totally per se because `sse4_crc32` which is used by our dependency `fast-crc32c` is actually an optional dependency.

**Comment by mstade** [comment]
Travis just recently [announced iojs support][1]. I'd make a PR but it's too much of a hassle (and I'm weary of) signing your CLA so I won't, my apologies.

[1]: http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/#iojs_support

**Comment by ryanseys** [comment]
Added to #386
