### ISSUE TITLE
Release 0.13.0?

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#382]
We haven't shipped since before Christmas despite numerous changes. I propose we ship `0.13.0` sometime soon. I'd suggest we skip `0.13.0` for superstition but semver might be sad about that.

**Comment by stephenplusplus** [comment]
:+1:

**Comment by ryanseys** [comment]
Will wait for #381 then we can :ship:

**Comment by ryanseys** [comment]
Gonna wait some more for #379 which might introduce breaking changes and this is priority for getting the build working smoothly again.

**Comment by ryanseys** [comment]
How do we release anyway? @silvolu might hold the key.

**Comment by stephenplusplus** [comment]
We just `npm version __major|minor|patch__` and push it to github.

**Comment by ryanseys** [comment]
Oh does @selfiebot see the tag and handle it? It's been so long since a release I forget.

**Comment by stephenplusplus** [comment]
Yep, @selfiebot is king of npm publish and doc building.

**Comment by ryanseys** [comment]
PRAISE THE KING!

:crown:
@selfiebot

:bow::bow::bow: <-- gcloud team

**Comment by ryanseys** [comment]
@selfiebot appears to be dead because our docs are not building. Could someone please investigate? 

@jgeewax 
@silvolu 

And teach me how to do it if possible? :)

**Comment by stephenplusplus** [comment]
I believe we discovered selfie wasn't happy with our failing tests, so it aborted before building the docs. After #402, hopefully the flakiness will be eradicated.

**Comment by ryanseys** [comment]
![8eb6pr5](https://cloud.githubusercontent.com/assets/163873/6359567/2c7844d2-bc42-11e4-9db0-610bd7483ce1.jpg)

**Comment by stephenplusplus** [comment]
Not fixed, but too many issues for the same thing :$ Specific issue and discussion for solution:  https://github.com/GoogleCloudPlatform/gcloud-node/issues/411
