### ISSUE TITLE
Show the last-updated time in the generated gh-pages docs?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#385]
I know we have the version history, but it'd be really cool if we could see the date that the docs were last updated. Any chance we can put that into the travis deployment build?

**Comment by stephenplusplus** [comment]
The site displays docs for the latest tagged version by default, so the last built date will always be the date of the latest version's release. We could use the GitHub api to get information that should work. For example, we can filter through https://api.github.com/repos/googlecloudplatform/gcloud-node/releases for the matching version and get the date.

**Comment by ryanseys** [comment]
Yeah GitHub API should work. Last update would not necessarily be the last release though, so we are better off using something like https://api.github.com/repos/GoogleCloudPlatform/gcloud-node/commits?sha=gh-pages&per_page=1

**Comment by stephenplusplus** [comment]
I think the most useful date to show on our docs is the one that matches when the version was released. Unless you meant we can fish through the commits to gh-pages to find some kind of indicator of a release's build?

**Comment by ryanseys** [comment]
Nope I meant the latest commit as per @jgeewax request for "date that the docs were last updated" which would coincide with the last push, regardless of release. If this is not what @jgeewax meant, then release date works for me.

**Comment by jgeewax** [comment]
OK so -- two scenarios I see:

1. I'm using version x.y -- I want to see the docs for x.y (and honestly, the date doesn't really matter... the version is the important piece).

1. I'm using master -- I want to see the docs for master (at which point, the date and/or last commit ID matter a bunch, the version not so much...)

For the first case, I think we're covered. This issue is to cover the second case. Can we make "master" also include a commit ID and date of the commit? Or is that a stupid amount of work?

**Comment by stephenplusplus** [comment]
PR sent: #394
