### ISSUE TITLE
Support datastore on local development server

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#389]
https://cloud.google.com/datastore/docs/tools/devserver

**Comment by stephenplusplus** [comment]
Should we accept configuration to a Dataset's instantiation?

```js
var ds = gcloud.datastore.dataset({
  host: "localhost",
  port: "8080"
})
```

**Comment by stephenplusplus** [comment]
Just leaving a note for the future implementer of this, I needed to set the `Content-Length` header to avoid a 411.

```
authorizedReqOpts.headers['Content-Length'] = pbRequest.length;
```
