### ISSUE TITLE
How to get auto assigned id

### ISSUE THREAD

**Issue by Solido** [GoogleCloudPlatform/gcloud-node#410]
Using gcloud datastore save leave no indication about the generated ID for the cell.
Nothing in the call back or the key or the data.

**Comment by ryanseys** [comment]
The key will be automatically populated with the id in its `path` after the save call. See the [docs here](http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.12.0/datastore/dataset?method=save) for more information. 

Excerpt:

> If a key is incomplete, its associated object is inserted and the original Key object is updated to contain the generated ID.

**Comment by stephenplusplus** [comment]
What version of gcloud-node are you using, and can you paste what your call to `.save` looks like and the returned values to the callback supplied?

**Comment by Solido** [comment]
Thanks for the replies !

Based on the examples of Todo (source, best doc ever)  i've used the pop() method on the path to get the ID and now it's working.

Coming for Angular and others JS api i'm quite disturbed with this API paradigm.
I was expecting something like promise or a success and error callback method that send the new ID. 

Something like save ( ..., onSuccess(id), onFail()) and not save (..., cb(err)) if (!err) path.pop().

Have to said this API is quite powerful but sparse on docs. I got my main API running on a java GAE and using GCloud to control it from a nodejs front, it's really cool but it leaves me with a lot of questions on how to use it correctly !

Thanks for the job done :)

**Comment by ryanseys** [comment]
The idea is that you create a `key` object and then you use it to save an object, and later you can use that exact same key object to reference that specific object. 

Perhaps we should add some helper methods to the Key object such as `getId()` ? Would that help?

**Comment by stephenplusplus** [comment]
From an old discussion: https://github.com/GoogleCloudPlatform/gcloud-node/pull/175#discussion_r17145279

**Comment by ryanseys** [comment]
Is this resolved? I believe its relatively straightforward to get the auto-assigned id from the key but let me know if that's not the case.

**Comment by byrneciaran** [comment]
Is this a bug in the demo ? ... looking at the Todo app sample code the response doesn't return a key. It returns a mutation_result so key.path.pop(); doesn't work. The key should be initialised outside the save function and then the id can be retrieved.

ds.save({
      key: ds.key(['TodoList', LIST_NAME, 'Todo']),
      data: data
    }, function(err, key) {
      if (err) {
        callback(err);
        return;
      }
      data.id = key.path.pop();
      callback(null, data);
    });

**Comment by stephenplusplus** [comment]
I ran the example and `key.path` was correct: `[ 'TodoList', 'default-list', 'Todo', 5720605454237696 ]`

We do need a better way to get the key and various other helpers. We'll use #574 to track that.
