### ISSUE TITLE
The project exceeded the rate limit for creating and deleting buckets.

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#411]
Currently our regression tests, which run on three different travis instances simultaneously and hit real Google servers, are hitting the rate limit for creating and deleting buckets in a small period of time and thus causing the tests to fail. These are likely safety limits imposed to all projects. We can turn off two of the three travis instances and just run on `0.12.x` which should reduce our usage enough that we don't hit the rate limit or someone internal (@jgeewax) could attempt to win over the Google Cloud Storage Quota gods with chocolate and flowers.

**Comment by jgeewax** [comment]
/me buys flowers and chocolates.

Assigning to myself to see if we can change the rate limit. What are the project IDs? And where do the credentials live on the testing machine? (Google will want to know the answer to this...)

**Comment by ryanseys** [comment]
The credentials live in Travis, along with the project ID which I don't know. I don't believe I have access to see them. You might be able to see them here if you have the right authority: https://travis-ci.org/GoogleCloudPlatform/gcloud-node/settings/env_vars

**Comment by stephenplusplus** [comment]
Any updates? Blocking our release of 0.12.

I'm okay with removing iojs from Travis if you think that will fix it.

**Comment by jgeewax** [comment]
Do you guys know how many requests we make in a typical day or hour? This way I can make sure that if allowed, the respective teams can increase the quota correctly....

**Comment by ryanseys** [comment]
We're breaching the safety quotas for creating buckets and performing acl changes on buckets... there may be other quotas we are also hitting, I'm not sure. These quotas are per-minute... If we merge a couple commits or even run travis across different versions of node, it will hit these limits many times over so its hard to say how many we need, though a good place to start counting would be our storage regression test file(s). 

https://cloud.google.com/appengine/docs/quotas#Safety_Quotas_and_Billable_Quotas

**Comment by stephenplusplus** [comment]
Should we let this go now that we have "backed off" of the servers?

**Comment by ryanseys** [comment]
I believe JJ is still assigned to convince them to increase our rate limits. We should see if that's still required after backing off.

**Comment by ryanseys** [comment]
I think we're over this.
