### ISSUE TITLE
Update pubsub to v1beta2

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#414]
The following is a checklist for migrating over to the new v1beta2 pubsub API. It lists the incompatible changes that occurred between the two APIs.

- [x] All requests now using a new url scheme: `https://pubsub.googleapis.com/v1beta2/...`

### Subscriptions:
- [x] acknowledge: Move `subscription` to path parameter from request body.
- [x] acknowledge: `ackId` changes to `ackIds`.
- [x] create: No longer accepts a name in request body (subscription resource).
- [x] list: `pageSize` instead of `maxResults`.
- [x] list: project in path parameter.
- [x] list: no `query` parameter.
- [x] list: returns `subscriptions` instead of `subscription` in response.
- [x] pull: subscription moved to path parameter instead of request body.
- [x] pull: added `maxMessages` to set max number of messages to pull.
- [x] pull: response now contains top level `receivedMessages` and is drastically different response.
- [x] pullBatch: removed pullBatch.

### Topics:
- [x] create: name now a path parameter instead of in request body.
- [x] delete: different url scheme for topic name.
- [x] get: topic name now in path parameter instead of in request body.
- [x] list: require project in path parameter.
- [x] list: no `query` parameter.
- [x] list: `pageSize` instead of `maxResults`.
- [x] list: returns `topics` instead of `topic` in response.
- [x] publish: topic now a path parameter instead of in request body.
- [x] publish: request body now takes `messages` array of messages.
- [x] publish: response will now return list of `messageIds` rather than an empty response.
- [x] publishBatch: removed publishBatch.

### NEW:
- [x] [topics.subscriptions.list](https://cloud.google.com/pubsub/reference/rest/v1beta2/projects/topics/subscriptions/list) which results the name of the subscriptions for a particular topic.
- [x] [PubSubMessage description](https://cloud.google.com/pubsub/reference/rest/google/pubsub/v1beta2/PubsubMessage) which describes the pubsub message response for various requests.

**Comment by tmatsuo** [comment]
Great list! One addition.

labels renamed to attributes

**Comment by ryanseys** [comment]
@tmatsuo So `maxResults` changed to `pageSize`, which is documented as "Maximum number of topics to return." Is this the max number of results returned PER PAGE i.e. if I have more results, then it will still give me a page token, or does it mean that it will only show me that many ever? Did this functionality change from the previous API or is it just better (or worsely) documented now?

**Comment by tmatsuo** [comment]
> Is this the max number of results returned PER PAGE
yes, the name of the parameter strongly suggests that.

> if I have more results, then it will still give me a page token
yes.

Do you have any suggestions to improve things?

**Comment by ryanseys** [comment]
@tmatsuo I have some feedback. [topics/subscriptions/list](https://cloud.google.com/pubsub/reference/rest/v1beta2/projects/topics/subscriptions/list) returns a list of subscription names where as [subscriptions/list](https://cloud.google.com/pubsub/reference/rest/v1beta2/projects/subscriptions/list) returns a list of Subscription objects. It would be nice if they both returned Subscription objects if possible.

**Comment by tmatsuo** [comment]
Yes, good eye catching that discrepancy. I think however, this is because topics.subscriptions.list may return subscriptions in other project, and thus the API issuer may not have permission to access them.

**Comment by ryanseys** [comment]
It doesn't make sense that it will show me subscriptions for other projects because we specify a specific project on request. Also why would it show me the names of subscriptions if I don't have access to use them in the first place? This would seem like a violation of permissions. I don't want someone seeing my subscriptions on my project if they don't have access to it.

**Comment by tmatsuo** [comment]
> It doesn't make sense that it will show me subscriptions for other projects because we specify a specific project on request.

Not true. With the bare API, you can create a subscription in project1 attached to a topic in project2.

This would seem like a violation of permissions. I don't want someone seeing my subscriptions on my project if they don't have access to it.

When creating that subscription, the creator said explicitly "I subscribe to this topic". So I think seeing only the subscription name with the topic read permission seems OK to me.

You can't get the internal data of that subscription if you don't have a permission.
