### ISSUE TITLE
Custom metadata broken in 0.12.0

### ISSUE THREAD

**Issue by phw** [GoogleCloudPlatform/gcloud-node#419]
Providing custom metadata via the `metadata.metadata` property as documented at https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.10.0/storage/file?method=setMetadata is not working for me with gcloud 0.12, but works fine with 0.11. Standard metadata works fine, too.

Partial sample code:
```javascript
var metadata = {
  contentType: 'text/plain', // <- This works
  metadata: {
    customValue: 'MyValue' // <- This will not be set with gcloud 0.12
  }
};

inStream.pipe(file.createWriteStream(metadata));
```

**Comment by stephenplusplus** [comment]
Would you mind trying against master? I believe we realized this recently and it should be fixed for our next release.

**Comment by ryanseys** [comment]
Try the newest release! We just released [v0.13.1](https://github.com/GoogleCloudPlatform/gcloud-node/releases/tag/v0.13.1) today.

**Comment by stephenplusplus** [comment]
This will work:

```js
var options = {
  metadata: {
    contentType: 'text/plain',
    metadata: {
      customValue: 'MyValue'
    }
  }
};

inStream.pipe(file.createWriteStream(options));
```

So, createWriteStream takes an options object. That object can hold a metadata object with file metadata, such as contentType. Inside of that, you can have another metadata object to hold custom values. It's a bit of a mind warp.

**Comment by phw** [comment]
Sorry for my late response, I had this on my list but was unable to test it until now. I have now both upgraded to 1.13.2 and added the additional nesting in the options object, works as expected. Thanks for the fast reply and support.
