### ISSUE TITLE
Allow reading only n tail bytes from a file

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#420]
Carrying on from #415, a user can specify a `start` and `end` range to read from a remote file. The JSON API also allows reading *n* tail bytes from a file, e.g. `range=-100` would be the last 100 bytes. Our API currently looks like:

```js
file.createReadStream({ start: 0, end: 10 })
```

We could allow specifying a range in another way:

```js
file.createReadStream({ range: "0-10" })
```

Which would open the doors for:

```js
file.createReadStream({ range: "-100" })
```

Definitely open to other ideas of how we can support ranges of both types: "start and end" and "end offset".

Note: `start` and `end` was added to match the native `fs` module's createReadStream's arguments, which behaves the same was currently as ours.

**Comment by ryanseys** [comment]
Another idea I'm not too attached to but figured I'd throw it out. What about:

``` js
file.createReadStream({ tail: 10 })
```

This would override or be always overridden by `start`/`end`. Problems include introducing another parameter, parameters that void other parameters, but benefits are it's clear its purpose.

**Comment by stephenplusplus** [comment]
How about just allowing:

```js
file.createReadStream({ end: -10 })
```

and adding documentation to explain that's reading -10 tail bytes?

**Comment by jgeewax** [comment]
I'm :+1: to `end: -10` (the same way in CSS you can do `right: -10px` for example). Definitely would rather this than adding a new parameter... But you guys are the experts.

**Comment by stephenplusplus** [comment]
Cool cool. Let's try it out and if we find the community hates it, we can try again!
