### ISSUE TITLE
Total Rows in  job.getQueryResults()

### ISSUE THREAD

**Issue by sunnychow** [GoogleCloudPlatform/gcloud-node#427]
When we get make a pagination, we want to know the total number of page.

According to google, it could return the totalRows, such that, we could know the total number of page. 
https://cloud.google.com/bigquery/docs/reference/v2/jobs/getQueryResults

Unfortunately, in this project, job.getQueryResults() do not returns the total number of records, it's better to return the total rows.

**Comment by stephenplusplus** [comment]
Good find! If you come across anything else we're not passing back that would be useful, please continue to let us know.

**Comment by stephenplusplus** [comment]
This will be solved by #448.

**Comment by ryanseys** [comment]
#448 recently was merged into master. If you'd like to give it a shot now, feel free and let us know how it goes. Otherwise you may wait until we release the next version.
