### ISSUE TITLE
File write stream does not error when writing to a file in a non-existent bucket

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/gcloud-node#436]
When using file.createWriteStream when the file was created on a non-existent bucket, the stream does not error and essentially acts as if everything is fine. The only indication of error is the fact that no file is uploaded.

In the example below, one would expect the error event to trigger:
```javascript
var gcloud = require('gcloud');

var storage = gcloud.storage({
  keyFilename: process.env.GOOGLE_APPLICATION_CREDENTIALS,
  projectId: process.env.GCLOUD_PROJECT_ID
})

var bucket = storage.bucket('this-bucket-does-not-exist');

var file = bucket.file('file.ext');
var stream = file.createWriteStream();

stream.on('error', function(){ console.log('Error'); });
stream.on('finish', function(){ console.log('Done'); });

stream.write('data');
stream.end();
```

**Comment by ryanseys** [comment]
This is caused by [`handleError`](https://github.com/GoogleCloudPlatform/gcloud-node/blob/7fb3c1756cc3622bce6776ca00e77d4ea1e3687c/lib/storage/file.js#L1110) being used for **all the things** and the error is a 404 (bucket not found), which no amount of `startUpload` will solve.

**Comment by ryanseys** [comment]
@jonparrott Also you should use

**Comment by jonparrott** [comment]
Great, I'll switch over to the complete event. At the moment, modifying that sample to use the complete event just ends with node hanging indefinitely(?). I'm assuming PR #438 will fix that?
