### ISSUE TITLE
techdebt: Regression tests --> system tests

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#457]
Technically our "regression tests" are really ~~integration~~ system tests. Adding this issue as a technical debt so that maybe someday we will get around to renaming it in the various places.

**Comment by dhermes** [comment]
:+1: /cc @tseaver

**Comment by tseaver** [comment]
I'd really prefer "functional" or "system" to "integration" for the `gcloud-python` ones:  they are [end-to-end tests of the whole system](http://en.wikipedia.org/wiki/System_testing), rather than [tests of integrated assemblies of components](http://en.wikipedia.org/wiki/Integration_testing).

**Comment by ryanseys** [comment]
Agreed. +1 for system tests.
