### ISSUE TITLE
Automatic retry request for all rate limit responses

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#460]
We should have a global setting to automatically retry requests (with exponential back-off) that receive a rate limit response. It should be turned on by default, have a retry limit of 3-5 that is configurable and additionally be configured to be turned off altogether.

Something like:

```js
var gcloud = require('gcloud')({ retryLimit: 5 });
```

and

```js
var gcloud = require('gcloud')({ autoRetry: false });
```

We should be clear that this setting is only for responses related to rate limits being reached and not that it will retry every request regardless of response error.

**Comment by stephenplusplus** [comment]
Just look for error code 429: Too many requests?

> The Google Cloud Storage JSON API per-project usage limit was exceeded. If your application tries to use more than its limit, additional requests will fail. You can see API usage limits on the Quotas pane in the Google Developers Console.

**Comment by tmatsuo** [comment]
I think you may want to also look for 500.

There are inevitable non-zero intermittent 5xx errors with distributed systems like current APIs, I would like to retry in such cases, as well as rate limited errors.

**Comment by ryanseys** [comment]
Apparently it's there's no way for me to test this locally because I never get rate limited on my machine. I have no idea why that is. I literally just made 100 buckets in ~1 second, no rate limit.

![giphy](https://cloud.githubusercontent.com/assets/163873/6879435/6fd40c10-d4cb-11e4-817b-d35837423f6e.gif)

**Comment by tmatsuo** [comment]
Maybe you can explicitly configure the lower user limit on your project?

**Comment by ryanseys** [comment]
@tmatsuo Any idea what this error code is?  https://travis-ci.org/GoogleCloudPlatform/gcloud-node/builds/56411032

Excerpt:
> Error: The service was unable to fulfill your request. Please try again.

**Comment by tmatsuo** [comment]
Does it always happen?
If not, they are just intermittent errors, and they're not limited only to Pub/Sub.

**Comment by ryanseys** [comment]
No it doesn't always happen. Just trying to track down the code because this occurred with rate limiting PR merged (checking and retrying 500, 503 and 429)
