### ISSUE TITLE
Subscription dies when out of messages.

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/gcloud-node#461]
When using ``topic.subscription`` to listen to messages via pull, the subscription will (eventually) trigger an error when there are no messages. However, the desired behavior seems to be to just keep trying until messages come in. It appears it's sufficient to just ignore the error for this to continue to work as expected. See example:

```javascript
  var subscription = topic.subscription(subscriptionName);
  subscription.on('error', function(err) {
    /* This error occurs when there's no new messages.
    Since we want to listen forever, this is a non-error. */
    if (err.code == 400 && err.errors[0].reason == 'failedPrecondition') return;

    /* 404 means that the subscription hasn't been created. */
    if (err.code == 404) logging.error("Pub/sub subscription does not exist.");

    throw err;
  });
```

**Comment by jaredrhine** [comment]
Hi, @jonparrott . Are you using auto-ack? If so, a fix is available in #455.

**Comment by jonparrott** [comment]
Not using autoAck.

**Comment by tmatsuo** [comment]
This behavior should have been changed with the Cloud Pub/Sub API v1beta2. @jonparrott do you know which API version you're using?

**Comment by jonparrott** [comment]
I was using the version in npm, I tried this out with the master branch here and it doesn't seem to still be an issue. Closing.
