### ISSUE TITLE
Switch Protocol Buffers lib

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#474]
Just stumbled upon this: https://github.com/mafintosh/protocol-buffers - maybe worth integrating? Looks simple and fast.

**Comment by ryanseys** [comment]
Interesting. I'm all for speed and simplicity, especially when we have performance regressions or we are implementing with it. Not sure we have either of those scenarios so my comment is "why bother?" at least right now. I worry we'd see compatibility issues if not everything is implemented in this new library. Good to keep on the radar.

**Comment by stephenplusplus** [comment]
Fair enough, we'll just close this for now, and if we find the need for something new in the future, we can review this one again.
