### ISSUE TITLE
Overview of Authentication in docs

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#483]
Should have a Authentication section in docs to make it clear how to authenticate.

**Comment by ryanseys** [comment]
Assigning to Stephen as he knows the docs Angular thing inside and out. Also was responsible for the recently merged authome (pronounced: "awesome" but with a lisp) PR.

**Comment by stephenplusplus** [comment]
On it!

Also, `authome` would be a great name for a LISP library.

**Comment by ryanseys** [comment]
> Also, `authome` would be a great name for a LISP library.

Hahaha! This is brilliant. This was way over my head for longer than I'd like to admit.
