### ISSUE TITLE
Support Google DNS API

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#486]
API: https://cloud.google.com/dns/api/v1beta1/
RFC rrdata format: https://tools.ietf.org/html/rfc1034#section-3.6.1

**Comment by ryanseys** [comment]
Has support by the `gcloud` command line tool, so we should look at how it handles the API. https://cloud.google.com/dns/getting-started

**Comment by ryanseys** [comment]
Designing the API. https://gist.github.com/ryanseys/29d238d454fcdd3621c8

**Comment by ryanseys** [comment]
Pre-PR development for DNS happening in https://github.com/ryanseys/gcloud-node/tree/dns

**Comment by stephenplusplus** [comment]
@ryanseys booting you :mans_shoe: Thanks for getting this started!
