### ISSUE TITLE
Final review for PubSub by Google PubSub team

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#487]
Should we have this reviewed more?

**Comment by pierre-b** [comment]
Yes, the doc is quite a mess actually, looking at the code is essential.

Could you please update the doc, the message.id should be message.ackId https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.13.2/pubsub/subscription?method=ack

Thank you

**Comment by ryanseys** [comment]
@pierre-b Hi thanks for your concerns. Is there any other specific issues you would like us to address?

**Comment by pierre-b** [comment]
Hi @ryanseys , I noticed a 30sec average lag when I open a subscription and the first message arrives, then the others arrive directly. Is this an expected behavior ?

I also need to know how many messages are waiting in the subscription, to pop new workers or monitor the health of my system. Is it in the roadmap actually ?

Thank you

**Comment by jgeewax** [comment]
Hi @pierre-b: Can you put these in separate issues so we can track them individually?

**Comment by tmatsuo** [comment]
I will look at the code this week.

**Comment by pierre-b** [comment]
Hi @jgeewax , forgot to tell you Ive opened separate issues.

**Comment by tmatsuo** [comment]
Pubsub holds the project id, which prevents you from accessing resources in multiple projects.

https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/pubsub/index.js#L90

Is this expected?

**Comment by jgeewax** [comment]
Just to be clear, it seems to me that I could do:

```javascript
var gcloud = require('gcloud');
var pubsub1 = gcloud.pubsub({projectId: 'project1'});
var pubsub2 = gcloud.pubsub({projectId: 'project2'});
```

right?

This would allow us to access resources across projects, no?

**Comment by tmatsuo** [comment]
@jgeewax I hope you're right. I meant you can not access multiple projects unless creating multiple pubsub object.

However, I came up with a bad scenario.
I have 2 projects; projectA and projectB.
I have 1 topic; topic-a in projectA.
I have 1 subscription; subscription-b in projectB, which subscribes to the topic-a.

I don't think I can access to the subscription-b easily. It seems to me that the only way is to call pubsub.getSubscriptions() and iterate.

**Comment by tmatsuo** [comment]
Actually, I'm afraid that getSubscriptions() will give me

**Comment by tmatsuo** [comment]
This is the biggest concern from me.

Also little bit worried about the performance. I would like to do performance comparison with the google-api-js-client, but never get time to do that.

**Comment by tmatsuo** [comment]
Oh, maybe I can do the following?

```javascript
var pubsub2 = gcloud.pubsub({projectId: 'project2'});
var sub2 = pubsub2.subscription('subscription2');
```

**Comment by tmatsuo** [comment]
Apparently, Pubsub object doesn't have subscription method. Can you add it?

**Comment by ryanseys** [comment]
That would just create a reference to an existing subscription, we would also have to support `pubsub#subscribe` I believe that could take an optional topic object.

**Comment by jgeewax** [comment]
Re performance: that is actively not a goal for this right now. P(usability) >> P(performance). That isn't to say that performance will be ignored, but it's lower priority than usability.

---

> I have 2 projects; project1 and project2.
> I have 1 topic; topic1 in project1.
> I have 1 subscription; subscription2 in project2, which subscribes to the topic1.

Is it reasonable to create a subscription to a topic from a different project?

What I read in the docs (https://cloud.google.com/pubsub/reference/rest/v1beta2/projects/subscriptions/create) is that Subscription.create accepts:

- name=projects/*/subscriptions/* (ie, the name includes the product ID and the subscription name 
- "topic": string, (ie, you specify which topic to subscribe to)
- other config stuff

If that's the case, without topics being globally unique, is there any possible way to specify a topic from another project? Does "topic" (string) take the form /projects/project-id/topics/topic-name ?

**Comment by tmatsuo** [comment]
> Is it reasonable to create a subscription to a topic from a different project?
Yes, it's totally reasonable.

> Does "topic" (string) take the form /projects/project-id/topics/topic-name ?

To be precise, it's "projects/project-id/topics/topic-name". It's far better than a situation where resource names are in the global namespace.

**Comment by stephenplusplus** [comment]
Going to close this out, as I believe we have fixed everything addressed in this issue, and will continue to tackle things one at a time in other issues. Feel free to reopen if I missed something.
