### ISSUE TITLE
Crashing app just by requiring the gcloud module v0.13.2

### ISSUE THREAD

**Issue by markuso** [GoogleCloudPlatform/gcloud-node#489]
I have started to migrate our file storage strategy to use Google Cloud Storage. I have installed the module from npm into my project like so:

`npm install gcloud --save`

Then I only required it at the top of a file to use within like so:

`var gcloud = require('gcloud');`

When I start the app it crashes immediately with `...terminated by signal SIGILL (Illegal instruction)`

When I remove the require statement then my app goes back to operating as normal.

Any idea? Is it just this version (v0.13.2)?

EDIT: I am locally using OSX Yosemite 10.10.2 and Node.js v0.12.2 (tried it on v0.12.0 with same results)

**Comment by ryanseys** [comment]
Might be related to #425

**Comment by ryanseys** [comment]
Can you try to reproduce this on `master`? I believe we may have fixed it.

**Comment by markuso** [comment]
**Yes.** I confirm that the latest change on `master` fixed this issue on my environment as stated above.

**Comment by ryanseys** [comment]
Awesome! Thank you!
