### ISSUE TITLE
callback for bucket.getFiles doesn't return prefixes

### ISSUE THREAD

**Issue by javorosas** [GoogleCloudPlatform/gcloud-node#491]
From the docs;

storage > bucket.getFiles > query.delimiter

> [...] Objects whose names, aside from the prefix, contain delimiter will have their name truncated after the delimiter, **returned in prefixes**.

But then there is no reference anywhere to that "prefixes" array (?) that should contain the truncated objects.

This would be really useful if implemented, because as of today, there is not a simple way of making an object browser with folder hierarchy (like the storage explorer in the application console), which is able to list files and folders given a prefix (or inside a folder).

**Comment by ryanseys** [comment]
Related to #342

**Comment by stephenplusplus** [comment]
Thanks for catching this. The prefixes will be available from the apiResponse (*note* only will work on master, since #448 was merged):

```js
bucket.getFiles({ /*...*/ }, function (err, files, nextQuery, apiResponse) {
  // apiResponse.prefixes
})
```

**Comment by stephenplusplus** [comment]
We put a more helpful tip in the docs. If you feel we can do better, please re-open!

**Comment by conet** [comment]
In the latest version `3.2.1` prefixes can't be obtained because of the wrapping, the callback passed to the `getFiles` function looks like this:
```
cb:(err, results, nextQuery) => {
            if (err) {
                this.destroy(err);
                return;
            }
            this._nextQuery = nextQuery;
            if (this._resultsToSend !== Infinity) {
                results = results.splice(0, this._resultsToSend);
                this._resultsToSend -= results.length;
            }
            let more = true;
            for (const result of results) {
                if (this._ended) {
                    break;
                }
                more = this.push(result);
            }
            const isFinished = !this._nextQuery || this._resultsToSend < 1;
            const madeMaxCalls = ++this._requestsMade >= this._maxApiCalls;
            if (isFinished || madeMaxCalls) {
                this.end();
            }
            if (more && !this._ended) {
                setImmediate(() => this._read());
            }
            this._reading = false;
        }
```
So this would need a proper change, either a `getPrefixes` function or a different type of response.
