### ISSUE TITLE
Object versioning support

### ISSUE THREAD

**Issue by javorosas** [GoogleCloudPlatform/gcloud-node#498]
I don't see anything about object versioning on the docs. Is there support for listing/retrieving the revision history of a file?

**Comment by stephenplusplus** [comment]
I actually have a PR in progress for this: https://github.com/GoogleCloudPlatform/gcloud-node/pull/409

It would be great if you could take a look and see if it would cover your use cases.

**Comment by javorosas** [comment]
It looks great. Though I think it doesn't cover the case of listing the available generations (?) or versions of a file. Or I might have overlooked.

**Comment by stephenplusplus** [comment]
Good call. I'll try implementing something and ping you for your thoughts after.

**Comment by javorosas** [comment]
Awesome, thanks.
