### ISSUE TITLE
Upgrade jws to 3.0.0

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/gcloud-node#499]
On Apr 14, 2015, when I installed gcloud with npm, I got:

```
npm WARN deprecated jws@0.2.6: Security update: Versions below 3.0.0 are deprecated.
```

I think you should upgrade jws to 3.0.0.

**Comment by stephenplusplus** [comment]
@ryanseys I believe this is from gToken. Just upgrade, make a patch release, and it should be fixed for new installs.

**Comment by ryanseys** [comment]
Done. https://github.com/ryanseys/node-gtoken/commit/e4e613553a06c5ba71c4edaa5b795f7cef425534
