### ISSUE TITLE
Documentation does not render correctly in chrome

### ISSUE THREAD

**Issue by gotmikhail** [GoogleCloudPlatform/gcloud-node#503]
https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.13.2/storage/file

No examples show up in:

44.0.2372.0 canary (64-bit) - regular & incognito
42.0.2311.90 m - regular & incognito

Works in Firefox.

**Comment by ryanseys** [comment]
Can you post a screenshot of what you see? Also, what operating system are you running? I'm running 42.0.2311.90 and see all the examples on that page.

**Comment by gotmikhail** [comment]
Running Windows 7 Pro
![gcloud-nodejs](https://cloud.githubusercontent.com/assets/356867/7212214/a8fa4fec-e531-11e4-9534-5c7243422383.PNG)

**Comment by ryanseys** [comment]
Looks related to https://github.com/pc035860/angular-highlightjs/issues/26

**Comment by stephenplusplus** [comment]
:S I guess we can just keep a copy in the repo. I should really create a build process anyway to minify and concatenate.

**Comment by gotmikhail** [comment]
@stephenplusplus Thanks for the fix. It's working now in 42.0.2311.90 m and 44.0.2376.0 canary (64-bit).

Examples make the documentation much more useful :+1:

**Comment by stephenplusplus** [comment]
Great. Thanks for reporting, we never would have caught that one!
