### ISSUE TITLE
App default credentials do not work on App Engine Managed VMs.

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/gcloud-node#513]
When running locally or on Google Compute Engine, [app default credentials](https://developers.google.com/identity/protocols/application-default-credentials) are used to provide authentication without needed to provide a private key. However, this does not work when deployed to Managed VMs.

**Comment by stephenplusplus** [comment]
Have you tried against master? We just started using [google-auth-library](https://github.com/google/google-auth-library-nodejs), but haven't made a release yet.

**Comment by jonparrott** [comment]
Yes, this is against master. It's possible that managed VMs does not expose the service account from the underlying VM.

**Comment by ryanseys** [comment]
I think it should... I just came across [this library](https://github.com/GoogleCloudPlatform/appengine-nodejs#auth) which appears to provide that functionality (getting a token) from within Managed VMs.

**Comment by jonparrott** [comment]
This might be that the service account associated with the managed VM doesn't have the datastore scope. Investigating and will update.

**Comment by ryanseys** [comment]
Yeah they seem to be hitting [the same endpoint](https://github.com/GoogleCloudPlatform/appengine-nodejs/blob/431b733963bbadb42ce9545d2b5711bf1e8b7992/lib/index.js#L718) as long as it's working as it should.

**Comment by jonparrott** [comment]
Okay. That is exactly the problem.

* Managed VMs default service account doesn't include scopes to access datastore, pubsub, etc.
* The .yaml config to add the scope isn't current documented (it's a beta setting)

Once the settings are documented, we should add some documentation here around adding scopes to MVMs/GCE to allow access.

**Comment by ryanseys** [comment]
@jonparrott Thanks for investigating! Can you open a new issue and point to the docs that helped you resolve this issue so we know how to document it for our users?

**Comment by jonparrott** [comment]
It's not currently documented :( I'll create a new issue here once I get the docs published.

**Comment by ryanseys** [comment]
Okey doke! I'll reopen this to keep tracking the issue.

**Comment by stephenplusplus** [comment]
> The .yaml config to add the scope isn't current documented (it's a beta setting)

@jonparrott if that's documented now (?), that's probably good enough. Maybe a simple line could be added to https://github.com/GoogleCloudPlatform/gcloud-common/tree/master/authentication with something like "To enable the scopes on a managed VM, see [...]()"

**Comment by jonparrott** [comment]
This is a non-issue now, as all the requisite scopes for GCP APIs are now defaulted in MVMs. Users should never have to change the scopes. If they do, I consider that that's a bug on our end.

**Comment by stephenplusplus** [comment]
Oh, great. Thanks again!
