### ISSUE TITLE
Storage bucket.getFiles() not including sub-directories when specifying a prefix

### ISSUE THREAD

**Issue by drewbryant** [GoogleCloudPlatform/gcloud-node#514]
GCS supports also returning "sub-directories" (i.e., common object prefixes) when listing a bucket and specifying a prefix (e.g., "/") within the query.

The sub-directories are returned as `CommonPrefixes` within the response.

Could these be included as well in the `bucket.getFiles()` response? Or maybe add a flag to specify whether subdirectories should also be returned.

Currently, the only work-around I've come up with is listing all objects within the bucket (expensive) and then filtering the response.

**Comment by stephenplusplus** [comment]
Is this in the JSON API? https://cloud.google.com/storage/docs/json_api/v1/buckets/list doesn't seem to show it returning anything other than the objects that match the original prefix.

**Comment by drewbryant** [comment]
Looks like it's in the XML API, but not the JSON API currently:
https://cloud.google.com/storage/docs/reference-headers#delimiter

**Comment by ryanseys** [comment]
It might be the same thing as `prefixes` available through the JSON API (I'm not familiar with the XML API -- didn't even know one existed before today), in which case it's accessible through the apiResponse object provided in the 4th parameter in the `getFiles()` call: See [here for relevant code](https://github.com/GoogleCloudPlatform/gcloud-node/blob/cb65e347561c1cd243192852403df91929a47698/lib/storage/bucket.js#L370). We're sorry it's not directly accessible through the first array of files.

**Comment by ryanseys** [comment]
Yes, I believe that is the case. You can access the `CommonPrefixes` value like so:

```js
var query = {
  delimiter: '/'
};
bucket.getFiles(query, function(err, files, nextQuery, apiResponse) {
  // files is array of files
  // apiResponse.prefixes is the same as CommonPrefixes
});
```

**Comment by drewbryant** [comment]
Great to see that the common prefixes are already coming back in the fourth parameter. I think it's actually better that you keep the prefixes separated from the actual files/objects. Thanks Ryan/Stephen!

**Comment by ryanseys** [comment]
No problem, glad we could help!

**Comment by HadyZ** [comment]
Hello I tried to specify the delimiter but nothing change I cannot access a folder ref to read files from , I am using admin sdk 

any help
