### ISSUE TITLE
Add links to code from documentation?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#519]
When I link to http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.13.2/pubsub/subscription?method=ack I was wondering how to get from that method to reading the code for that method.

Is there any way we can add a link that brings us to the actual code on Github...?

**Comment by ryanseys** [comment]
Seems potentially doable with `line` and `codeStart` values in the json files generated by `dox`
