### ISSUE TITLE
Where is the code for Dataset.get() ...?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#537]
If I go to http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.14.0/datastore/dataset?method=get

And click the "view code" link (https://github.com/GoogleCloudPlatform/gcloud-node/blob/v0.14.0/lib/datastore/dataset.js#L102) I'm taken to an empty line...

Looking around in the file didn't send me to any code...

Is this method magically injected somehow?

**Comment by stephenplusplus** [comment]
Oh man, the complicated web that is JSDocs + the Docs -> MD + how we rig things up on the FE. A Dataset has a @&shy;mixin of the Transaction class, which is where `get` comes from. http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.14.0/datastore/transaction?method=get

Off the top of my head, I can't think of an easy way to solve for this, but will think on it.

**Comment by jgeewax** [comment]
Hmm -- that link seems to lead me astray as well... And I don't see a
method called "get" defined on the Transaction class either....?

**Comment by stephenplusplus** [comment]
Oops, the web gets webbier. Transaction itself has a @&shy;mixin on the DatastoreRequest class, which is finally where `get` lives: https://github.com/GoogleCloudPlatform/gcloud-node/blob/v0.14.0/lib/datastore/request.js#L102

**Comment by ryanseys** [comment]
So it got the line number right, but the file wrong. I don't know if that helps make things any easier?

**Comment by stephenplusplus** [comment]
That does, indeed. Let's see what we can do about this...

**Comment by stephenplusplus** [comment]
This was resolved by #584 - I tagged the wrong issue in the PR.
