### ISSUE TITLE
pubsub.Subscription docs page is ... different?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#546]
If I go to the pubsub.Topic page (http://googlecloudplatform.github.io/gcloud-node/#/docs/master/pubsub/topic) I see what I expect: a class called Topic ("Topic (code on GitHub)")

If I go to the same page for Subscription (http://googlecloudplatform.github.io/gcloud-node/#/docs/master/pubsub/subscription) I see something kind of weird and different: "pubsub/subscription (code on GitHub)".

Any idea why this doesn't have the proper naming?

**Comment by stephenplusplus** [comment]
Forgot the `module:` leader: https://github.com/GoogleCloudPlatform/gcloud-node/blob/bc2b57ce4e2d84a8d2ff722d677ddfe681fc8d00/lib/pubsub/subscription.js#L61

On it!

...I'm getting good at saying that!
