### ISSUE TITLE
datastore#dataset is ignored in documentation?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#547]
Looking at https://github.com/GoogleCloudPlatform/gcloud-node/blob/1f57dd607b4c52a48f88781cd185220d40683184/lib/datastore/index.js#L94

Looks like we chose to make this "Developer documentation"?

Seems weird that we'd have pubsub#topic documented but not datastore#dataset? (http://googlecloudplatform.github.io/gcloud-node/#/docs/master/pubsub?method=topic)

Was there a reason we chose to `!` ignore that docstring?

**Comment by stephenplusplus** [comment]
I think it may have been a mistake. Sometimes a Developer doc block is stacked on top of a public doc block, so maybe a sloppy delete left the `/*! Developer Documentation` heading instead of the other. Good find, will fix!
