### ISSUE TITLE
Left navigation keeps bringing back to the master version

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#548]
To reproduce:

1. Go to the docs: http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.14.0
1. Make note that you're looking at version 0.14.0
1. Click anything in the top section in the left nav bar (ie, PubSub)
1. Make note that you're now in the master branch version of the docs... (at least according to the URL)

Any ideas how we can avoid dropping into the master version?

**Comment by stephenplusplus** [comment]
On it!

**Comment by stephenplusplus** [comment]
Docs Day 2015.

**Comment by jgeewax** [comment]
:( Sorry! I'm just digging around in here trying to think what could be better ! You guys are awesome though -- thanks for getting on this stuff super quickly!

**Comment by stephenplusplus** [comment]
No, it's awesome, thank you! Docs are super important. :v:
