### ISSUE TITLE
Move <Service> Overview sections into only the top level

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#549]
Right now, the <Service> Overview sections appear on every page for the classes under that service:

- http://googlecloudplatform.github.io/gcloud-node/#/docs/master/datastore/dataset has the Datastore Overview
- http://googlecloudplatform.github.io/gcloud-node/#/docs/master/pubsub/subscription has the Pub/Sub overview
- etc.

Do you think it would make more sense to move these sections into the top levels only?

- http://googlecloudplatform.github.io/gcloud-node/#/docs/master/pubsub would have the pub/sub overview
- http://googlecloudplatform.github.io/gcloud-node/#/docs/master/pubsub/subscription (a sub page) would not

Thoughts?

**Comment by ryanseys** [comment]
I believe the reason for this is that they don't have to go to the overview page to get a general idea of what the API does. I think @stephenplusplus can speak more to this.

**Comment by stephenplusplus** [comment]
I'm down with this. Trying to be too helpful can sometimes be less helpful.

**Comment by jgeewax** [comment]
Seems to me that it's also taking up some pretty valuable screen real-estate...

Do you guys have any ideas on how we could document the Getting Started (expandable thing) and the <Service> Overview in a way that:

1. doesnt take up tons of screen real estate
1. still is visible on all the pages

?

**Comment by stephenplusplus** [comment]
I think limiting to the top level page will help. It just makes sense that if someone is in the Datastore -> Transaction docs, they would think to go up a level to Datastore to learn more about Datastore.

Doing this could even let us get rid of the "Overview" section, and just move its content to the JSdoc blocks for the modules.

Using [BigQuery's page](http://googlecloudplatform.github.io/gcloud-node/#/docs/master/bigquery) as an example, it would look like:

![screen shot 2015-05-08 at 12 26 11 pm](https://cloud.githubusercontent.com/assets/723048/7540675/738f3438-f57d-11e4-93e6-13831bb87550.png)

**Comment by jgeewax** [comment]
:+1:

**Comment by ryanseys** [comment]
Yeah I agree, for a page like http://googlecloudplatform.github.io/gcloud-node/#/docs/master/datastore/dataset?method=save we don't really need all the overview. Distracts from the method-specific docs.
