### ISSUE TITLE
Walk through the "Saving data" in gcloud.datastore's Docs?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#554]
Looks like it's not 100% clear to people how they can save data of different types. Maybe we should write some better documentation in the overview page explaining common tasks you want to do with Datastore? (Reference: #553)

/cc @ryanseys

**Comment by ryanseys** [comment]
Assigning to myself to take a look at making these better.

**Comment by ryanseys** [comment]
@jgeewax Does this suffice or would you like something more?

**Comment by jgeewax** [comment]
LGTM
