### ISSUE TITLE
Permalink link in the docs is... pretty small. Could we make it a larger click target?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#555]
To permalink, I need to hover, which makes a # appear, and then click that... Might be easier if the heading itself was a link...

**Comment by stephenplusplus** [comment]
That was actually my first implementation, but see @ryanseys comments: https://github.com/GoogleCloudPlatform/gcloud-node/pull/188#issuecomment-54697990

I think his issue was seeing a clickable link for a method made him think clicking it would show more information, but instead it just took him to a page with the same information.

Ryan can of course clear this up if I was confused :)

**Comment by jgeewax** [comment]
Maybe a compromise is to always have the # visible? That way I don't have two steps (hover -> click). I can just click? @ryanseys, thoughts?

**Comment by ryanseys** [comment]
Oh yeah we ended up putting the information on both pages anyway, so making all the blue a link is okay with me. Maybe just keep the # visible the whole time too? I'm really indifferent, but maybe I've been pre-conditioned from using the docs for a while.

**Comment by jgeewax** [comment]
OK, so plan is:

- Make # always visible.
- Make the whole thing clickable as the permalink

Does that sound right? @ryanseys @stephenplusplus

**Comment by stephenplusplus** [comment]
Sounds good to me.
