### ISSUE TITLE
Code snippets on authorization page aren't highlighted

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#561]
See https://googlecloudplatform.github.io/gcloud-node/#/authorization -- the snippets with `var config = ...` don't seem to be using syntax highlighting.

**Comment by stephenplusplus** [comment]
I'll take a look at this again.

Related: https://github.com/GoogleCloudPlatform/gcloud-node/pull/507#issuecomment-96672814
