### ISSUE TITLE
Add breadcrumbs when you're "zoomed in" to a specific method?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#563]
When we're zoomed in on a specific method (ie, https://googlecloudplatform.github.io/gcloud-node/#/docs/master/datastore/transaction?method=allocateIds)

We lose track of which module and class we're looking at (the sidebar is there, sure, but it's not really obvious).

I'm thinking it might be worthwhile to add headings, ie, for this example:

- h1: Datastore
- h2: Transaction
- h3: allocateIds

Thoughts?

**Comment by stephenplusplus** [comment]
Definitely :+1:
