### ISSUE TITLE
Datastore querying by multiple kinds supported in gcloud-node, but not by Datastore.

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#572]
When running the following code:

```javascript
var gcloud = require('gcloud');
var dataset = gcloud.datastore.dataset({
  projectId: 'my-project-id'
});

var query = dataset.createQuery(['Kind1', 'Kind2']);
dataset.runQuery(query, function(err, entities) {
  console.log(err);
  console.log(entities); // null
});
```

I get the following error returned: `message: 'multiple kinds not supported'`

According to https://cloud.google.com/datastore/docs/concepts/queries, Datastore allows querying over a single kind, not multiple.

Maybe we should remove the ability to construct a query with multiple kinds?

**Comment by tmatsuo** [comment]
FYI there is kindless ancestor queries:
https://cloud.google.com/datastore/docs/concepts/queries#Datastore_Kindless_ancestor_queries

**Comment by jgeewax** [comment]
Yes, you can provide 0 or 1 Kinds, but not N.

**Comment by ryanseys** [comment]
Agreed, this should be addressed.

**Comment by jgeewax** [comment]
OK so the question then becomes, how do we sort this out? Some options:

1. Change `dataset.createQuery()` to accept only one kind as a string
1. Change `dataset.createQuery()` to still accept a list (or a string), but raise an exception if the list is more than one item long
1. Change `dataset.runQuery()` to raise an exception if multiple kinds are there
1. Change `dataset.runQuery()` to recognize the "multiple kinds not supported" error response and raise a more helpful error.

@GoogleCloudPlatform/cloud-datastore : Is there any chance at all that Datastore will support queries of multiple kinds (not Kindless queries, but queries for Kind1, Kind2, ..., KindN) ?

If the answer above is yes, we should probably go with the option that recognizes the error and raises it in a friendly way rather than trying to prevent people from doing this in client code.

**Comment by pcostell** [comment]
Yes there is a plan to support queries on multiple kinds in the future, but I don't believe it is on our short-term roadmap.

**Comment by ryanseys** [comment]
Strange that the API is `kinds` that accepts an array of objects with `{ name: 'kind' }`. Our code will remain the exact same but the documentation will change. They may provide an array of 1 kind and that will work still but it won't be documented as such.

**Comment by pcostell** [comment]
Do you mean it's strange that it's an array of objects and not strings? If so, it's so we can support aliases (important if you want to select from the same kind multiple times).

**Comment by ryanseys** [comment]
I meant it's just strange that it accepts an array, and the property is `kinds` as opposed to `kind` (singular) which would more suggest that it only accepts one.

**Comment by Alfus** [comment]
It is that way to potentially support queries like "SELECT * FROM Kind1 as
A, Kind1 as B, Kind2 WHERE A.b = B.a AND Kind2.b = A.b" in the future.
