### ISSUE TITLE
Show the latest version on the landing page?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#577]
Would it be useful to show the latest version number on the landing page? And maybe the last push date?

**Comment by ryanseys** [comment]
Latest npm version and date of that version push seems like a good idea. Any idea where on the landing page it seems most appropriate?

**Comment by jgeewax** [comment]
I think it might look best somewhere at the top in the blue area?

Maybe small text after `gcloud`? Or below the `npm install --save gcloud` ?

@chriscalo any thoughts?
