### ISSUE TITLE
migrate the existing datastore node samples to gcloud

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/gcloud-node#6]
* Node.js samples from https://github.com/GoogleCloudPlatform/google-cloud-datastore
* Quickstart from https://developers.google.com/datastore/docs/getstarted/start_nodejs/

**Comment by stephenplusplus** [comment]
I think somewhere along the way, it was decided to let the `google-cloud-datastore` project continue using the more barebones APIs to talk to Datastore. If that's incorrect, feel free to re-open with an update.
