### ISSUE TITLE
storage: a way to abort a request

### ISSUE THREAD

**Issue by laggyluke** [GoogleCloudPlatform/gcloud-node#600]
It seems there is no way to abort an upload or download request created by `file.createWriteStream()` and `file.createReadStream()` respectively.

Node's native HTTP client has [request.abort()](https://nodejs.org/api/http.html#http_request_abort), but as far as I can tell the above methods return simple through2 streams and keep the raw HTTP requests / responses hidden.

So is there a way to abort a request in progress?

**Comment by ryanseys** [comment]
You should be able to destroy the stream with `stream.destroy()` and assuming that validation is turned on (on by default), the upload/download will fail. Can you try that and let us know how that works?

**Comment by laggyluke** [comment]
`stream.destroy()` seems to work great, thanks!

**Comment by ryanseys** [comment]
Perfect! Glad we could help! :smile:
