### ISSUE TITLE
Add pubsub#subscription, pubsub#subscribe and pubsub#getSubscriptions

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#605]
Add `pubsub#subscription` and `pubsub#subscribe` and `pubsub#getSubscriptions`.

All the logic I feel should move to these requests and then `topic#subscription` and `topic#subscribe` and `topic#getSubscriptions` should either be removed or rely on the pubsub version with an optional `topic` field automatically passed in.

How's this sound @stephenplusplus?

Reference: #487 

/cc @tmatsuo

**Comment by jgeewax** [comment]
Can we clarify the use case on this ? #487 is long, so it'd be nice if the description said "why" we're doing this.

I have one outstanding question, which if answered, makes me OK with these new pubsub-level methods. I also would agree that if we do add these, the topic-level ones simply wrap the pubsub-level ones. That is:

```javascript
Topic.prototype.subscribe = function(...) {
  return this.path.to.pubsubInstance.subscribe(...);
};
```

**Comment by ryanseys** [comment]
The use case is for creating a subscription in one project that subscribes to a topic in another project.

**Comment by stephenplusplus** [comment]
@ryanseys SGTM. In fact, I can start working on this now, but feel free to stop me if you already had this in the works.

**Comment by ryanseys** [comment]
@stephenplusplus You can go for it!
