### ISSUE TITLE
Rename Storage examples from "var storage" to "var gcs"

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#619]
Continues https://github.com/GoogleCloudPlatform/gcloud-node/pull/617#discussion-diff-30792128...

It seems a lot of people refer to "Cloud Storage" as "GCS" as opposed to "Storage". In userland, I've seen [`var gcs = gcloud.storage(/*...*/);`](https://github.com/GoogleCloudPlatform/gcloud-node/issues/522) more than once, and tend to prefer that name over the more generic "var storage;" naming.

Any thoughts on changing our Storage examples to use `var gcs = gcloud.storage();` in place of `var storage = gcloud.storage();`? The term "storage" feels vague to me, instead of implying that it offers functionality that sits above a bucket.

**Comment by jgeewax** [comment]
I'm a fan of using `gcs` in our examples.

**Comment by ryanseys** [comment]
I'm ok with this idea.
