### ISSUE TITLE
Transaction Documentation

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#623]
Related: #621 

Should we privatize `transaction#begin` and `transaction#commit`, removing them from the public docs and their usage in other Transaction examples?

A user goes through their Dataset instance to get a Transaction:

```js
dataset.runInTransaction(transaction, done) {});
```

This calls `transaction.begin` immediately, and the `done` function returned to their callback is actually `transaction.commit`.

Having these methods appear in the docs is probably quite confusing, as the user shouldn't need (or be able to) begin a transaction that already began, or commit the transaction before calling `done` (commit) again.

**Comment by abelino** [comment]
Ohhh snap, this clears things up a lot!!! Thanks!!!

**Comment by ryanseys** [comment]
Yeah these should be private.

**Comment by ryanseys** [comment]
Oooh I'll address these in #627
