### ISSUE TITLE
Make "Report issue" button fit the style of the rest of the docs

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#630]
Something looks off about the button -- it doesn't really fit the style we have. The button style that we had from the original mocks was:

![button](https://cloud.githubusercontent.com/assets/112928/7818599/cf3e7696-03aa-11e5-82b7-a4cd46c375f4.png)

Might be worth sticking with that?

**Comment by stephenplusplus** [comment]
I personally find the hard edge/single pixel border of that button to contribute to its ugliness.

I think these all fit together:

![screen shot 2015-05-26 at 1 29 10 pm](https://cloud.githubusercontent.com/assets/723048/7818703/413ee172-03ab-11e5-830e-9d5e7f595c3c.png)
![screen shot 2015-05-26 at 1 29 29 pm](https://cloud.githubusercontent.com/assets/723048/7818704/4143596e-03ab-11e5-9352-0044dc976af3.png)
![screen shot 2015-05-26 at 1 29 18 pm](https://cloud.githubusercontent.com/assets/723048/7818705/4143e208-03ab-11e5-99e4-7f920351c3de.png)

But it's easy to make the switch, just make the call.

**Comment by jgeewax** [comment]
I think the first has a drop-shadow the others don't. Could we make it fit more with the middle one ?

**Comment by jgeewax** [comment]
And with the same background-color ?

**Comment by stephenplusplus** [comment]
I snapped a pic of the middle button in its hover state. It goes from white to that light gray. PR and preview at #631
