### ISSUE TITLE
Start thinking about Cloud Search API?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#632]
Looks like we'll have a search API exposed soon. I drafted up some Python code to cover a bunch of the use cases. Working on getting the developers here access to the internal docs (it's not released yet, and not announced yet).

Here's the draft of the code if you're interested in exploring...

https://github.com/GoogleCloudPlatform/gcloud-python/pull/892/files#diff-056d3999e591db310404f19fbf639531

**Comment by ryanseys** [comment]
Initial DRAFT Design Doc for `gcloud-node` support for Cloud Search available here: 

https://docs.google.com/document/d/1jblFpy8-St-r2MNwt0IWXVwWdsy0IyQrIC2myvyY3Mk/edit

We'll plan to move the design doc to GitHub once it's been more scoped out. Please feel free to post any feedback you have on the document itself (I've given the public comment access) or here on this issue.

**Comment by ryanseys** [comment]
Question: Should we aim to support Cloud Search through the RPC (protobuf) or REST endpoint? 

RPC is more complex to implement but using it results in smaller payloads so potential for higher throughput. REST is easier to implement in node.js but results in larger payloads.

**Comment by jgeewax** [comment]
That's a good question. For now, I think the answer is "whatever gets us moving fastest". Once we have some usage, we can explore swapping out the lower-level code that does the transport + serialization stuff. Seem reasonable ?

**Comment by ryanseys** [comment]
That seems reasonable.

**Comment by stephenplusplus** [comment]
Seems reasonable.

**Comment by stephenplusplus** [comment]
Search implementation is underway: #648
