### ISSUE TITLE
resumable upload url for browser upload

### ISSUE THREAD

**Issue by aschmid** [GoogleCloudPlatform/gcloud-node#635]
hey guys,

i need to upload files to the same bucket from different urls and i would like to avoid creating an actual oauth token for each url. all urls are in the format http://<tenant>.myapp.com.

right now i am streaming the files through the server and uploading them with the gcloud-node library but its killing my server because the files are too big and its just too much. what i want to achieve now is make the app request an upload url which the server generates and return it to the browser so the javascript app can do the upload without bothering the server and contact the endpoint once the uplaod is done.

my question now is is there a way to request this uplaod url like described here with an actual json keyfile rather than the oauth token?

if this is not an option, will it be possible to request a single oauth token and use that one for all app subdomains i use?

thank you, andreas

**Comment by stephenplusplus** [comment]
Can you can persist an authorized gcloud "session" (to reuse the same authorized connection) on your server, that will generate URLs on demand?

```js
var gcloud = require('gcloud');
var gcs = gcloud.storage({
  projectId: 'project-id',
  keyFilename: 'keyfile.json'
});
var bucket = gcs.bucket('my-bucket');

var app = require('express')();

app.get('/url/:fileName', function(req, res) {
  bucket.file(req.params.fileName).getSignedUrl({
    action: 'write'
  }, function(err, url) {
    res.end(url);
  });
});

app.listen(3001);
```

**Comment by stephenplusplus** [comment]
And I'm really sorry for the super long time to respond :( I hope your summer's been well!

**Comment by stephenplusplus** [comment]
Hey @aschmid, I'm going to close this one out. Hopefully the above solution will work or one from #641.
