### ISSUE TITLE
Make the links in the README for the specific services point to *our* docs

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#637]
If I click on Cloud Storage in the README, it sends me to the cloud storage landing page... I watched someone do this today, but they expected it to take them to the docs for cloud storage in node, not some marketing site......

Can we make our README point to the docs rather than the product pages? (Or add both so the main one is the docs, and in parens we have the link to the service overview?)

**Comment by stephenplusplus** [comment]
Do you mean the top section under "This client supports the following Google Cloud Platform services:"? This is a style we're following across gcloud-* I believe. Given that these links look like a table of contents for the current document, I think it would be best to link to the matching section in the readme.

So, if you click "Google BigQuery" it will scroll you down to the BigQuery section which links to all possible interesting endpoints (cloud landing page, cloud docs, our docs).

**Comment by jgeewax** [comment]
I'm fine with that. I definitely don't want these linking off to cloud.google.com/<service> as it's ... basically a dead end for most people.

**Comment by stephenplusplus** [comment]
Cool. I can send a PR to the other repos as well.

**Comment by jgeewax** [comment]
+1
