### ISSUE TITLE
BigQuery job body included in many requests that don't need it

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#647]
Filed internally at [b/21557935](http://b/21557935), moving to public here:

> Ryan, looking at some of our API logs for an unrelated issue, I see gcloud-node is including a giant query string of an entire job configuration for BigQuery API methods that do not require it, such as getQueryResults(). Is there any reason for this? Looking at the gcloud-node code, it seems like simply removing it from all the GET call request options should greatly reduce request size.

I'm guessing the issue starts [here](https://github.com/GoogleCloudPlatform/gcloud-node/blob/01ec51f5b37becccdc20130c6389e8201cc1f389/lib/bigquery/job.js#L141).

**Comment by stephenplusplus** [comment]
Thanks for posting here!

We will just need to filter what we pass to the API, example: https://github.com/GoogleCloudPlatform/gcloud-node/blob/01ec51f5b37becccdc20130c6389e8201cc1f389/lib/bigquery/index.js#L374

**Comment by weslem** [comment]
Your linked code is exactly what confused me to write the bug. The call to `makeReq_()` for an existing query passes the entire `options` as a query string, substantially growing the size of the request. I *think* you can just null out the query string instead, but I'm concerned I've missed some important context.

**Comment by stephenplusplus** [comment]
@weslem I sent #652 to fix the issue with `getQueryResults`. Which other API calls did you find that were passing the object?

**Comment by weslem** [comment]
#652 LGTM; that was the only place I found.

**Comment by stephenplusplus** [comment]
Awesome, thanks for catching this bug for us! I'm going to create an issue to make sure we plug any leaks that may exist in our other methods.

Oh, and feel free to report right to us here on the repo next time :)
