### ISSUE TITLE
Not access data from Google Play

### ISSUE THREAD

**Issue by beshkenadze** [GoogleCloudPlatform/gcloud-node#651]
When requesting files from the bucket "pubsite_prod_rev_ххххх" answer is always "Forbidden" (status code 403).
Example code:
```javascript
var gcloud = require('gcloud');
var storage = gcloud.storage({
    projectId: '1xxxxxxxx',
    keyFilename: './json_api_key.json'
});
 
var bucket = storage.bucket("pubsite_prod_rev_1xxxxxxxxx");
 
bucket.getFiles({
    prefix: "reviews"
}, function (err, files, nextQuery, apiResponse) {
    if (nextQuery) {
        // nextQuery will be non-null if there are more results.
        bucket.getFiles(nextQuery, function (err, files, nextQ, apiResponse) {
        });
    }
    if(files == null) { // always Forbidden
        console.log(err.message); 
    }else{
        console.log(files);
    }
});
```

**Comment by jgeewax** [comment]
Is that bucket owned by you? If so, are you sure that particular service account (specified in `keyFilename`) has access to the bucket?

**Comment by beshkenadze** [comment]
Yep, the bucket and the app owned by one account. 
Using gsutil everything works as expected.

**Comment by jgeewax** [comment]
Hmm. Are you able to list buckets ?

```javascript
var gcloud = require('gcloud');
var storage = gcloud.storage({
    projectId: '1xxxxxxxx',
    keyFilename: './json_api_key.json'
});

storage.getBuckets(function(err, buckets, next) {
  console.log('Buckets were: ', buckets);
});
```

**Comment by beshkenadze** [comment]
The list is empty, the response status of 200.
```javascript
{
  response: {
    debugId: 1,
    headers: {
      expires: 'Wed, 10 Jun 2015 13:28:33 GMT',
      date: 'Wed, 10 Jun 2015 13:28:33 GMT',
      'cache-control': 'private, max-age=0, must-revalidate, no-transform',
      vary: 'Origin, X-Origin',
      'content-type': 'application/json; charset=UTF-8',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '1; mode=block',
      'content-length': '31',
      server: 'GSE',
      'alternate-protocol': '443:quic,p=1',
      connection: 'close'
    },
    statusCode: 200,
    body: '{\n "kind": "storage#buckets"\n}\n'
  }
}
```

btw, APIs Explorer (https://cloud.google.com/storage/docs/json_api/v1/buckets/list) shows the same response, the request (https://cloud.google.com/storage/docs/json_api/v1/objects/list) generates a list of files.

**Comment by jgeewax** [comment]
This really seems like an access problem for that specific service account... You're 100% certain that the project ID is correct (and owns that bucket)? And that the service account is in that project? 

What happens if you run `gcloud auth login` locally and comment out the `keyFilename` property? (This tells gcloud-node to pull credentials from whatever the cloud SDK is using.)

**Comment by beshkenadze** [comment]
After using the command "gcloud auth login" and comment out the keyFilename property, request responded with 200 status and brought the list of files. 

It turns out that is not authenticated through a "service_account".

I doubled checked and even created another json key, but still won't work.

**Comment by jgeewax** [comment]
Gotcha. Do you see the service account in the list on the permissions page? (https://console.developers.google.com/project/_/permissions)

**Comment by beshkenadze** [comment]
Of course.
![2015-06-10 at 17 30 2x](https://cloud.githubusercontent.com/assets/167288/8084974/87e39964-0f96-11e5-94df-48da941103c1.png)

**Comment by jgeewax** [comment]
Err, that should probably look more like:

![perms](https://cloud.githubusercontent.com/assets/112928/8085018/12d656dc-0f5c-11e5-853b-59086a6d1b0f.png)

**Comment by jgeewax** [comment]
I just ran a quick test to double check this:

1. Create a bucket
1. Upload a file to that bucket
1. Create a new set of credentials (service account, with JSON keyfile)
1. Check whether the new credentials could see the bucket listing

The hope was to see if there was some bug on Google's side where *maybe* they weren't granting access to the bucket if you created the credentials *after* the fact.

It looks like this did exactly what it was supposed to do: I was able to see the bucket listing using the service account.

Any other info you can provide to help us track down whether this was a bug or not would be super useful... but I'm out of ideas (outside of simple mistakes like using the wrong `.json` file).

**Comment by beshkenadze** [comment]
Oh, I have a new version of the console.
Here is the correct screenshot:
![2015-06-10 at 18 19 2x](https://cloud.githubusercontent.com/assets/167288/8086334/8ef25090-0f9d-11e5-8262-f32e0a7d3d6d.png)

**Comment by beshkenadze** [comment]
We don't have account in Google Cloud Storage and we can't create a bucket :(
We have another account for a android application.

**Comment by ryanseys** [comment]
This is weird. Just throwing out a couple ideas:

1. The project id is different than the project number. Typically it starts with a letter, so it's strange yours starts with a number unless you changed it. For example `purple-spaceman-123` is a good example of what a default project id looks like.

2. Try going to `https://console.developers.google.com/project/{{projectID}}/apiui/credential`

You should see a screen like:

![image](https://cloud.githubusercontent.com/assets/163873/8086894/9f3c7d78-0f4c-11e5-9cdc-02870a39de70.png)

Click the "Generate new JSON key" button and set `keyFilename` to point to that file. The file should contain the line: `"type": "service_account"`.

> We don't have account in Google Cloud Storage and we can't create a bucket :(

What do you mean you don't have an account in Google Cloud Storage? There is no such thing as a Google Cloud Storage account. There are Google accounts and Google Service Accounts. With those two things, and the right credentials, you should be all set to use this library.

**Comment by ryanseys** [comment]
FWIW Cloud Storage did see a blip of 500's yesterday on https://status.cloud.google.com/ but, despite the overall vague-ness of the status report, it seems unrelated to the issue presented here.

**Comment by beshkenadze** [comment]
I re-generated the key:
``` json
{
  "private_key_id": "2xxxxxxxxxxxxxa",
  "private_key": "-----BEGIN PRIVATE KEY-----\nBODY\n-----END PRIVATE KEY-----\n",
  "client_email": "1xxxxxx-xxxxxx@developer.gserviceaccount.com",
  "client_id": "1xxxxxx-xxxxxx.apps.googleusercontent.com",
  "type": "service_account"
}
```
And nothing has changed.

All developers have a personal bucket (like pubsite_prod_rev_*) in the Cloud Storage, but do not have a full account if not buy it.
![2015-06-10 at 19 02](https://cloud.githubusercontent.com/assets/167288/8087434/7d6967d6-0fa3-11e5-9a00-158644e890e0.png)

**Comment by jgeewax** [comment]
Is the Cloud Storage API turned on ? https://console.developers.google.com/project/_/apiui/apis/library -> choose your project, then search for "Cloud Storage API"

**Comment by ryanseys** [comment]
Have you enabled billing or started a free trial? You cannot use Google Cloud Storage if you don't start the trial, have a credit on your account, or add a credit card to your account for billing.

**Comment by beshkenadze** [comment]
@jgeewax Of course.
![2015-06-10 at 19 09](https://cloud.githubusercontent.com/assets/167288/8087567/5d735742-0fa4-11e5-81df-a8e068a82368.png)

**Comment by beshkenadze** [comment]
@ryanseys Yes, but I can use Google Cloud, if I'm Android Developer.
![2015-06-10 at 19 14](https://cloud.githubusercontent.com/assets/167288/8087680/10b8276a-0fa5-11e5-98e8-cc5cb4850528.png)
Details here: https://support.google.com/googleplay/android-developer/answer/138230?hl=en

**Comment by jgeewax** [comment]
That's interesting. So you didn't create the bucket yourself... In that case, can you look at the permissions on the bucket?

- https://console.developers.google.com/project/_/storage/browser
- See the 3 dots on the far right side next to your bucket, click it and choose Edit bucket permissions

If you didn't create it yourself it's possible that your project doesn't have all the right access... You want to make sure your project is listed as an owner and reader in this screen:

![perms2](https://cloud.githubusercontent.com/assets/112928/8087845/48f86318-0f6b-11e5-8942-2065f17f4052.png)

**Comment by ryanseys** [comment]
Ahhh... You're given restricted access to that bucket, i.e. cannot create files in it and it's owned by Google and shared with you to get your ratings csv etc. Additionally, you have access to Google Cloud Storage but you cannot do anything with that project because its sole purpose is to provide you your ratings. Try to enable billing or start a trial and [create a new project](https://console.developers.google.com/project) with Google Cloud, then you should be free to create as many buckets and files as you wish.

**Comment by jgeewax** [comment]
That's fair, but still... shouldn't downloads not throw a content mismatch?

**Comment by ryanseys** [comment]
That is a separate issue that should be addressed separately.

**Comment by beshkenadze** [comment]
@jgeewax I can't access the browser did not accept a trial.

But I can read and download files through the browser: https://console.developers.google.com/storage/browser/pubsite_prod_rev_*

I don't want to create an cloud storage account, but i want to get the files via gcloud-node, not using gsutil. :)

**Comment by jgeewax** [comment]
OK wait... The issue is his service account does not have access. We're saying that that is expected because the bucket is shared with a specific Google account, not a project?

**Comment by jgeewax** [comment]
@beshkenadze : If my previous comment is accurate, then it seems that Android is specifically limiting how you can access that data (that is, Android is saying "we'll put stuff here, and you can access it, and we won't make you pay, but that means you don't get all the features of Cloud Storage")

**Comment by beshkenadze** [comment]
@jgeewax If I don't have access to the bucket, then why login using gsutil or gcloud (console) authorization works?
I mean, I can't even login through json_key, but works through the console authorization.

**Comment by beshkenadze** [comment]
Well, I can login via the console and save the token.
I guess we can close the issue.

**Comment by jgeewax** [comment]
That's exactly my point. I think Android is sharing the bucket with **you** (ie, you@gmail.com) -- not **your project**.

So you'd need a way to tell Android to share either with your entire project (described above) or with your specific service account (in the e-mail address field for your service account, ie `606734090113-sjdpv266j56ffhlugjhuatb2nhfan8j9@developer.gserviceaccount.com`).

If you want a service account to have access (which, again, I'm not even sure how you'd do that), you likely can't do this for free. I'm asking around to see what I can find, but I don't think this is going to result in the answer you want :(

**Comment by beshkenadze** [comment]
A developer account and account Google API's the same.
The question is, why can't login through the server (json key), but it works via oauth.

**Comment by jgeewax** [comment]
@beshkenadze 

I think you're missing something important. A developer account is different from a service account which is different from a "project".

It seems that you have a bucket that is *owned* by someone else, and officially lives in *another* project, but it is shared with you. That is, that bucket has the following permissions:

- `you@gmail.com` can read from this bucket

When you create a service account, it's effectively creating a separate login (say, `your-service-account@accounts.google.com`). When you try to use the JSON key, it is **not** authenticating as `you@gmail.com`, it's authenticating as `your-service-account@accounts.google.com`

So officially, it's like `someone-else@gmail.com` trying to access YOUR bucket -- and Cloud Storage (correctly) says "sorry! we don't know who you are! you don't have access!".

Are you able to edit the permissions on this bucket? If so, you should add your service account's e-mail as a reader, which would fix your problem. If you can't, then you won't be able to use a service account and will always need to use your individual account for this.

**Comment by beshkenadze** [comment]
I checked on another account and connected Cloud Storage. Working.
Apparently, does not work in Android Developer Cloud Storage.

Yes, my account in Google Android Developer (beshkenadze) and a Cloud Storage account (beshkenadze) is not the same.

I'll use Python gsutil, which somehow works.

**Comment by jgeewax** [comment]
Just so you know, I'm asking around internally at Google to get you a definitive answer. Once I get that I'll update this thread, so I'm going to leave this open until then, assigned to me.

**Comment by beshkenadze** [comment]
@jgeewax Thanks!

**Comment by beshkenadze** [comment]
@jgeewax any news?

**Comment by jgeewax** [comment]
I think that gsutil uses your *user* credentials (not your service account). Right now, it seems we can't give service account access to this bucket as you're not the owner (it's owned by Google Play).

- Option 1: Use gsutil or user-account access (gcloud auth login + gcloud-node with those credentials)

- Option 2: Use gsutil to copy logs into a new bucket that you own, and use gcloud-node with a service account to access them.

**Comment by beshkenadze** [comment]
Hey @jgeewax,

Yes, you're right.
I am using JSON file created using gcloud auth login.
{
"client_id": "111111111.apps.googleusercontent.com",
"client_secret": "xxxxhxxhxxh
"refresh_token": "1/xxxxxx",
"type": "authorized_user"
}

Set this key file using: process.env['GOOGLE_APPLICATION_CREDENTIALS'] = 'path_to_file';
And it works.

Is it possible to create a key file using gcloud-node, not through binary gcloud?

**Comment by jgeewax** [comment]
Nope -- gcloud-node doesn't create keys. The gcloud command-line tool does this using the Oauth2 flow (and this creates **user** credentials, not service account credentials), and the Cloud Console will let you create keys as well (and this creates **service account** credentials).

gcloud-node only uses the keys you tell it to use.

The problem here ultimately is that Play created a bucket which it owns, and then shares with your **user**. As far as GCS is concerned, service accounts you create are completely separate "people" -- and they shouldn't have access to that bucket...

If you want to access these logs with a service account, you need to move the logs into a bucket that you own (as you don't own the bucket that Play puts logs into).

**Comment by beshkenadze** [comment]
@jgeewax Okay, I don't think Google Play can change a bucket to put the logs. :(

**Comment by jgeewax** [comment]
I don't think they can, but you can. If you use gsutil to move the files to another bucket, you can then do whatever you want.

I'm going to close out this issue (sadly, this is something that we'll have to think through on the Google Play side), feel free to re-open if you think that there's more we can do.

I'm also going to ping the Google Play team folks once again, and ask that at the very least they allow customers to supply their own GCS bucket so that this becomes much simpler. (The only downside for you would be that you would have to pay for the bucket, which is different from what happens now.)

**Comment by beshkenadze** [comment]
@jgeewax Of course I can manually transfer the files, but it doesn't make sense because they are automatically updated.

Yes, I agree that this is not a problem in gcloud-node, the problem in Google Play.
Thanks for the help .

**Comment by jgeewax** [comment]
No problem -- I just sent an e-mail to someone working on this. I requested:

1. Give users like you the ability to specify the bucket in which to put files (this would solve your problem, at the cost of you paying for the bucket)
1. Give users the ability to add access for a service account (this solves programmatic access)
1. Give users the ability to add notifications (harder, not what you asked for, but related to http://stackoverflow.com/questions/28855617/enable-notifications-watch-a-google-play-bucket-to-programatically-download-re)

I'll try my best to remember to update this thread when I hear back.

**Comment by beshkenadze** [comment]
4. To increase the frequency of data updates; now every 3(!) days, reviews time to become obsolete :)

Thx!

**Comment by jgeewax** [comment]
Haha :) I'll see if they can make it more frequent -- I suspect that will be a totally separate thing for them though. Sorry about that though!

**Comment by jgeewax** [comment]
@beshkenadze : Any chance you can try adding your service account as a user in the Play Devconsole? That is, in the JSON keyfile you'll see an e-mail address... Can you try adding that e-mail to the list of users authorized to your Play account?

**Comment by beshkenadze** [comment]
@jgeewax Interesting idea, will definitely try!

**Comment by beshkenadze** [comment]
I'm afraid to jinx it, but seems it works. 
Why I didn't think about that? :)

**Comment by jgeewax** [comment]
Cool -- Glad to hear it. This means your SA will have the same read-only access that you have. You still won't be able to configure notifications, but you can write your gcloud-node scripts in the normal way :)

**Comment by beshkenadze** [comment]
Yep :+1:

**Comment by jgeewax** [comment]
Are you sure that you're not accidentally using the wrong credentials? The Play folks mentioned they're only syncing credentials once per day, so it's unlikely that the service account would have access yet.

**Comment by beshkenadze** [comment]
Folder with configs is empty, nowhere to take the keys:
```bash
akira@akira-mbp ~/P/M/R/src> ls -l ~/.config/
total 0
drwxr-xr-x  5 akira  staff  170 Aug 10  2014 Transmission Remote GUI
drwx------  7 akira  staff  238 May 26 13:11 configstore
drwx------  6 akira  staff  204 Jul 20 16:30 fish
drwxr-xr-x  3 akira  staff  102 Jan  9  2015 robomongo
```

**Comment by jgeewax** [comment]
Double check that your gcloud-node code (`var gcloud = require('gcloud')({ ... })`) explicitly uses the service account key file? (I just want to be 100% certain that it's working the right way so we can add it to the documentation ! :)

**Comment by beshkenadze** [comment]
Without the key file:
![image](https://cloud.githubusercontent.com/assets/167288/8780246/724a5478-2f10-11e5-858b-f43b88250cb1.png)

With the key file: 
![image](https://cloud.githubusercontent.com/assets/167288/8780259/897409fa-2f10-11e5-890c-6431be122906.png)

Now, I will remove the account from Google Play and check it again.
![image](https://cloud.githubusercontent.com/assets/167288/8780324/e9930840-2f10-11e5-80a6-2e3ad95f2c7e.png)

**Comment by jgeewax** [comment]
Ha -- maybe they are .... misinformed about how often permissions get sync'd ? :-/ I'll ask around.. Thanks @beshkenadze !

**Comment by beshkenadze** [comment]
If anything, I can give access to the personal account on GP during the test.

**Comment by beshkenadze** [comment]
Just give me the email of the service account and I will add it to itself with read access.

**Comment by hugoduraes** [comment]
Hi @beshkenadze,

I'm getting the same issues as you got before. I'm trying to authenticate with gcloud auth login and use the generated json file on gcloud-node. In this case, what projectId have you used? Should I create a new project for this?

Thanks in advance.

**Comment by beshkenadze** [comment]
@hugoduraes hey! You need to use the project_id for which you created the service account.

**Comment by hugoduraes** [comment]
@beshkenadze So, I create a service account, add its email address to the google play developer account with permissions to view reports, generate a JSON keyfile and use it to access the API? Is this correct?

**Comment by beshkenadze** [comment]
@hugoduraes Sounds right :)

**Comment by hugoduraes** [comment]
@beshkenadze Was able to fetch files for a specific bucket. Are you able to get all buckets for the service account?

**Comment by beshkenadze** [comment]
@hugoduraes I used a particular bucket, it was 'reviews'.

**Comment by hugoduraes** [comment]
Ok. 
Thank you very much for your help. 👍
