### ISSUE TITLE
how thumbnail images

### ISSUE THREAD

**Issue by nvcken** [GoogleCloudPlatform/gcloud-node#657]
I see python, java lib support thumbnail images, how can I do that with node
Thanks

**Comment by jgeewax** [comment]
Can you point to the stuff in Python / Java that you're referring to?

**Comment by nvcken** [comment]
There is python
https://cloud.google.com/appengine/docs/python/images/

**Comment by jgeewax** [comment]
OK Gotcha.

Unfortunately there currently isn't a Google Cloud API for image processing, so this library (which is just a client library that depends on the different cloud services) can't do anything about that :(

Closing out -- sorry to be the bearer of less-than-ideal news !

**Comment by nvcken** [comment]
One more question please.
My node app host on App Engine, If I do thumb image manually by following 
```
download file from Google cloud storage to my app server (host on App Engine)
then generate thumbs , finally upload them back to Google cloud storage
```

So question is, has any different between above flow and python lib support API for image processing ?

**Comment by jgeewax** [comment]
Hm, that might be a question better answered over on StackOverflow -- I think if I tackled it here it might get lost (and it's probably useful for others in the future).

**Comment by nvcken** [comment]
@jgeewax 
http://stackoverflow.com/questions/30839820/what-is-different-between-manually-process-image-vs-app-engine-api-support-lib.
need help
