### ISSUE TITLE
README docs for GCS has piping instead of using upload/download?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#668]
Seems liek this should use `bucket.upload` and `file.download` right ?

**Comment by stephenplusplus** [comment]
The point of showing the piping is to say "Look how Node we are!" By showing we use regular read/write streams lets developers see how they can integrate it with other libraries/architectures they may already be using.

**Comment by jgeewax** [comment]
Got it... Can we add the upload/download pieces though also? Maybe put them first, then also have the piping example?

Seems like people aren't discovering those methods like they should be.

**Comment by stephenplusplus** [comment]
Definitely. Good idea!
