### ISSUE TITLE
createTopic vs topic can be confusing?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#669]
Right now, to "create a topic", people jump immediately to `createTopic` -- which gives them back a topic, but then the second time they try to create a topic, it'll cause problems, right? What people typically want in their code is `topic()` with `{autoCreate: true}` ...

So... a couple options

1. Remove / privatize `createTopic` (why create a topic to not use it...?)
1. Document in `createTopic` that you *probably* want `topic()`
  1. *and* update `topic()`'s options to auto-create by default

Thoughts?

**Comment by stephenplusplus** [comment]
I like privatizing createTopic and autocreating by default. RE: "(why create a topic to not use it...?)", should we loop in a Pub/Sub-er to see if we should continue to support that?

**Comment by jgeewax** [comment]
Hmm -- I think we're still pretty early, so it's not crazy to deprecate the method, and the "full deprecation" being that it's not longer in the docs. Thoughts?

**Comment by stephenplusplus** [comment]
SGTM.
