### ISSUE TITLE
Fix auth performance degradation in >= v0.14.0 / cache Google auth client per config

### ISSUE THREAD

**Issue by robertdimarco** [GoogleCloudPlatform/gcloud-node#674]
The v0.14.0 release of this module included a change in the underlying dependency used for Google authentication, from the `google-service-account` module to `google-auth-library` (see eae1b7d9ee3269219a5231eb341292c62e8aa092). During routine service benchmarking as part of our upgrade to v0.15.0, I noticed a 50% decrease in throughput for our proxy server when asked to serve 10k small files.

A super-simple example is shown below, which directly calls into `utils.makeAuthorizedRequest(...)`. This script makes 100 requests to GCS for file metadata, serially, and exits on completion. On v0.13.2, this script successfully completes in ~20-25 seconds, while in v0.14.0 and v0.15.0 it completes in ~45-50 seconds.

```javascript
var util = require('./node_modules/gcloud/lib/common/util.js')

var config = {
  keyFile: "[redacted]",
  projectId: "[redacted]",
  scopes: [ 'https://www.googleapis.com/auth/devstorage.full_control' ]
};

var reqOpts = { method: 'GET', qs: null, uri: '[redacted]', json: true };

var makeAuthorizedRequest;
if (util.makeAuthorizedRequestFactory) { // >= v0.14.0
  makeAuthorizedRequest = util.makeAuthorizedRequestFactory(config)
} else { // v0.13.2
  makeAuthorizedRequest = util.makeAuthorizedRequest(config)
}

var n = 100;
function next() {
  if (n > 0) {
    run(function() {
      setTimeout(next, 0);
    });
  } else {
    process.exit();
  }
}
function run(cb) {
  if (n > 0) {
    makeAuthorizedRequest(reqOpts, function(err, resp, req) {
      if (err) {
        console.error(err);
        process.exit(1);
      }
      cb();
    })
  }
}
next();
```

This difference is fully accounted for through additional time spent in `util.authorizeRequest(...)`. On v0.13.2, the call to `authorize(...)` is essentially a no-op if you are using a service account credential, and network I/O is not required.

This is caused by creating a new instance of `GoogleAuth` in `util.getAuthClient(...)`, effectively blowing away the cached bearer token and causing a new one to be generated for each request.

I'll follow-up with a PR addressing this issue in the next 24 hours.

**Comment by ryanseys** [comment]
Take a look at https://github.com/GoogleCloudPlatform/gcloud-node/pull/661. It might be what you're referring to. Let us know if/if not that's the case.

**Comment by robertdimarco** [comment]
@ryanseys Ah yes, that's it! Apologies for not seeing it. I'll close this out as a dupe.
