### ISSUE TITLE
Make left-side navigation collapsable?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#675]
Some people are having trouble finding the method listings at the top level when the overviews exist, so my first thought was to push the overviews lower on the page so the method listing was there, however that doesn't really fix the problem.

Not to mention, as we add support for more services, we're going to need that left-nav to be able to collapse and only show what's interesting...

Any ideas on how we could make the left-side navigation:

1. Show all the services
1. Expand when you click into one of the services
1. Expand to show the different methods when you click on one of the types

?

Some examples of navigation:

- Angular: https://angular.io/docs/js/latest/api/change_detection/AstTransformer-class.html
- Google Cloud: https://cloud.google.com/storage/docs/json_api/v1/buckets/get
- ArrangoDB: https://docs.arangodb.com/HttpEdge/AddressAndEtag.html
- MongoDB: https://docs.mongodb.org/manual/tutorial/backup-with-filesystem-snapshots/

**Comment by stephenplusplus** [comment]
How about the active class (say Datastore -> Dataset) will display the methods in the nav bar.

Basically: unchanged from how it is now, with the addition of methods below the active class, if one is selected.

**Comment by jgeewax** [comment]
Sorry - this wasn't really about adding methods to the left nav (though that is cool...) it was about "what happens when we add 5 more services, each with 2-3 more sub-items always exposed?"

I think requiring a boatload of scrolling no matter what is not exactly the best option -- and was hoping we could come up with some reasonable way of collapsing things so that people don't have to scroll to find the services they want.
