### ISSUE TITLE
Left navigation moves to the bottom when the page gets narrower?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#676]
Seems like this is a bit counter-intuitive. Could we maybe have it be something that appears when you click on the 3-horizontal-lined-link at the top right?

People in half-screen mode got super confused when the navigation disappeared, and were surprised to find it at the absolute bottom of the page... :(

**Comment by stephenplusplus** [comment]
Yeah, that's always what I expected would happen when clicking the hamburger.
