### ISSUE TITLE
Document cloud storage getSignedUrl

### ISSUE THREAD

**Issue by ruffrey** [GoogleCloudPlatform/gcloud-node#695]
https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/storage/file.js#L1065

This is an awesome feature enabling client-side uploads and downloads, and I nearly switched to AWS s3 because there was no easy way to figure out how to do it with google cloud storage and Node.

A couple of examples would probably go a long way.

If I get a chance I'll do a PR to the readme, but didn't want to forget to indicate how important this is, in the meantime.

Thanks.

**Comment by stephenplusplus** [comment]
Awesome, thanks for calling this out!
