### ISSUE TITLE
storage- when return status 503 (backend error) auto retry.

### ISSUE THREAD

**Issue by leibale** [GoogleCloudPlatform/gcloud-node#701]
add option in storage (by parameter) to auto retry when google return status 503.

**Comment by stephenplusplus** [comment]
We have a universal response handler we use on all of our requests that do this using exponential backoff, but it's possible we have some places that don't use it. Where did you notice it happening?

**Comment by leibale** [comment]
it's error in worker so i don't know exactly where is it, but it's or in upload image (file.createWriteStream) or in getFiles or in get file (file.createReadStream).

thanks

**Comment by stephenplusplus** [comment]
Ok thanks for reporting. I'll check into it tomorrow.

**Comment by stephenplusplus** [comment]
@leibale I took a shot at solving this in #705. Feel free to give it a look :)

**Comment by leibale** [comment]
@stephenplusplus i will try it tomorrow, thanks

**Comment by leibale** [comment]
@stephenplusplus i can't try it- i need the maxInProgress option (i am using my fork)
