### ISSUE TITLE
Make dropdown inside the docs to link to "inside the docs" for other languages

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#702]
The dropdown you see here: http://googlecloudplatform.github.io/gcloud-node/#/docs, when switching, links to the other-language-equivalent of http://googlecloudplatform.github.io/gcloud-node/

Could we have it link inside the docs of those other languages? 

ie:

- [x] Python: http://googlecloudplatform.github.io/gcloud-python/latest/
- [ ] Ruby: (we don't have this link yet, see https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/183)

**Comment by stephenplusplus** [comment]
Updated the Python link for now.

**Comment by blowmage** [comment]
The Ruby URL should be http://googlecloudplatform.github.io/gcloud-ruby/docs/latest

**Comment by stephenplusplus** [comment]
Thanks! Updated in a3e8aadfd8c0a16f9d03aa227f12c6354a1ca236.
