### ISSUE TITLE
Overview versus "API overview" in docs is all combined into a single navigation item

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#708]
Looking at https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.16.0/storage for example.

Because we have the overview first, the method listings for the top level API are easy to miss.

Is there any way we can split this apart so that there are two navigation items? The top level showing the docs overview and a walkthrough of common use cases (ie, https://raw.githubusercontent.com/jgeewax/gcloud-python/resource-manager/docs/resource-manager-api.rst) and some sub-level showing you the API methods (ie, `storage.bucket()`)?

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/gcloud-common#41
