### ISSUE TITLE
Small tweak to bucket names in Cloud Storage API code snippet (readme.md)

### ISSUE THREAD

**Issue by macvean** [GoogleCloudPlatform/gcloud-node#709]
In the following code, there is potential for slight confusion, due to the similarity in bucket names:

// Create a new bucket.
gcs.createBucket('my-new-bucket', function(err, bucket) {});

// Reference an existing bucket.
var bucket = gcs.bucket('my-bucket');

I would suggest updating the snippet to something like:

gcs.createBucket('my-new-bucket', function(err, bucket) {
    //do something with your bucket, or deal with the error
});

// Reference an existing bucket.
var bucket = gcs.bucket('an-existing-bucket');

**Comment by stephenplusplus** [comment]
:+1:
