### ISSUE TITLE
Clarify API Enablement instructions in the Authorization section of readme.md

### ISSUE THREAD

**Issue by macvean** [GoogleCloudPlatform/gcloud-node#710]
In the Authorization -> Elsewhere section of the readme, readers are instructed to:

Navigate to APIs & auth > APIs section and turn on the following APIs (you may need to enable billing in order to use these services):
1. Google Cloud Datastore API
2. Google Cloud Storage
3. Google Cloud Storage JSON API

Given this description is API agnostic, it is slightly confusing why these three APIs are chose. I would recommend either:

1. Adding clear instruction to 'Enable the APIs you intend to use, for example, for Cloud Storage you will need to enable Cloud Storage API and Cloud Storage JSON API"

or

2. Including all APIs supported by gcloud-node, with a note that if they do not intend to use all services, you only need to enable those you do need.

As a small nit, lets use the language 'enable' and 'disable' for consistency with the experience when they get to the GUI.

**Comment by stephenplusplus** [comment]
Great ideas! I think it would be best to show the services supported by this library and the matching APIs that must be enabled. Along with that, we can leave a reminder to only enable the ones you need.

**Comment by jgeewax** [comment]
This is also something that would benefit all the gcloud-* projects...

Maybe it's time to create gcloud-common, push some Markdown and screenshots to that library, and submodule them in...?

**Comment by stephenplusplus** [comment]
Sounds good to me; are we renaming meta or starting new?

**Comment by jgeewax** [comment]
I think we still need a place to have private conversations, so this would
be gcloud-common, a new repo. Thoughts?

**Comment by stephenplusplus** [comment]
Private roadmap stuff does come up now and then, so that makes sense.

Opened https://github.com/GoogleCloudPlatform/gcloud-common

**Comment by jgeewax** [comment]
Sweet :-D

**Comment by stephenplusplus** [comment]
This was fixed over in gcloud-common, but will wait for #734 to merge before calling this resolved.
