### ISSUE TITLE
Example for GCE in authorization documentation seems wrong

### ISSUE THREAD

**Issue by jacobsa** [GoogleCloudPlatform/gcloud-node#712]
In the section called "On Google Compute Engine", [this](https://googlecloudplatform.github.io/gcloud-node/#/authorization) page says that authorization is handled for me with no configuration. But the example directly below shows using an explicit JSON key file:

```javascript
var config = {
  projectId: 'grape-spaceship-123',
  keyFilename: '/path/to/keyfile.json'
};

var gcloud = require('gcloud')(config);
```

In fact, this is identical to the example used in the "Elsewhere" section.

**Comment by stephenplusplus** [comment]
Great catch, thank you! PR is very welcome if you're up for it :)

**Comment by jacobsa** [comment]
Okay, will do.

**Comment by jacobsa** [comment]
@stephenplusplus: Actually, this already looks correct [here](https://github.com/jacobsa/gcloud-node/blob/79a525aa64b98b541dd7537afc58ff42580abb52/docs/authorization.md) (modulo incorrect Markdown syntax, which I've sent a pull request for). How is that page generated?
