### ISSUE TITLE
Adding Google Compute Engine support

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-node#718]
This is just for discussion purpose. I am not reporting a bug nor an issue. 
I was wondering whether we could add support to Google Compute Engine. I think we can all benefit of a more node-oriented library for managing instances, disks, networks and so on. Personally I needed Compute Engine features in a project and I suspect there might be other people out there. However, I don't know if this fits somehow into your timeline :)  

I started adding some of Compute Engine features to gcloud-node in a branch of my fork (https://github.com/mziccard/gcloud-node/tree/compute-support). So far what I did is:
-  list/create/delete/start/stop/reset instances
-  list/create/delete disks
-  list/create/update firewall rules
-  attach/detach disks to/from instances

I haven't made any pull request yet as the code lacks tests and I wanted your opinion on adding these features first. Any thoughts?

**Comment by stephenplusplus** [comment]
Whoa! Thanks for doing this :) @jgeewax for comments on if we're ready for it or not.

**Comment by jgeewax** [comment]
Wow ! Awesome @mziccard !

That sounds great -- I have zero issue with pulling in support for GCE. Want to turn this into a pull request and @stephenplusplus can do the code review (for consistent style, etc) ?

**Comment by stephenplusplus** [comment]
Merged!
