### ISSUE TITLE
Use a code style linter

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#727]
Now that we are seeing more contributions, it would be a good time to remove the guesswork from matching our library's style rules. https://github.com/jscs-dev/node-jscs can integrate with our `npm run lint` command, so PRs will catch any issues.

@callmehiphop do you know of a better one than jscs?

**Comment by callmehiphop** [comment]
@stephenplusplus I like jscs personally, has there ever been any documented conversations around general dos and don'ts?

**Comment by stephenplusplus** [comment]
Laced all throughout PRs and issues history. We should try the `--auto-configure` option: http://jscs.info/overview.html#options.

**Comment by callmehiphop** [comment]
`--auto-configure` tests your code against several pre-made style guides and tells you how many times you violate it. It looks like you can then use those style guides as a base and make adjustments if you want to turn on/off additional rules.

**Comment by callmehiphop** [comment]
Preset | Errors | Rules
--- | --- | ---
airbnb | 224 | 11
crockford | 4279 | 6
google | 117 | 7
grunt | 47 | 6
jquery | 4815 | 10
mdcs | 5256 | 8
node-style-guide | 296 | 10
wikimedia | 8401 | 11
wordpress | 3869 | 11
yandex | 3825 | 8

**Comment by stephenplusplus** [comment]
Ah okay, probably want to find the closest match and make adjustments then. Here are some things:

```js
// good
function fn() {}

// bad
var fn = function() {};

// good
aMethod(function(err) {
});

// bad
aMethod(function (err) {
});
 
// good
if (something) {
} else if (somethingElse) {
}

// bad
// any other way of spacing if clauses
```

Let me know if I can answer any "this" or "that"s!

**Comment by stephenplusplus** [comment]
I don't know if these could be covered, but:

```js
// good
var self = this;

// bad
var that = this;

// good
var self = this;
aMethod(function() {
  self.anotherMethod();
});

// bad
aMethod(function() {
  this.anotherMethod();
}.bind(this));
```
