### ISSUE TITLE
Upgrade ConfigStore to 1.0

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#729]
It's just JSON now (formerly YAML), so we will save some processing power by upgrading.

**Comment by callmehiphop** [comment]
This would be a breaking change wouldn't it?

**Comment by stephenplusplus** [comment]
Kinda sorta. It's unique because it's a dependency for a feature the user doesn't realize exists, resumable uploads. If a resumable upload goes well, the information we cache is destroyed. So, ideally, the cache file is only non-empty for a brief amount of time.

But, it will be something to document for our next release. And since we're pre-1.0, each minor bump lets us go as yolo as we need to.

**Comment by callmehiphop** [comment]
Is there a centralized location where we would document breaking changes?

**Comment by stephenplusplus** [comment]
We use the GitHub releases page as a changelog.
