### ISSUE TITLE
Is the Datastore Query object supposed to be immutable?

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/gcloud-node#731]
At first glance I assumed that the `Query` class was supposed to be immutable -- each method creates a new query instance, copies all of the properties from the previous instance and then returns it. 

However, I noticed that for methods that can be called multiple times (`filter()` and `order()`) it holds a reference to the previous instance.

e.g.

```javascript
var query1 = new Query(['kind1']);
var query2 = query1.filter('count >', 5);

query1.filters.length; // => 1
```

Is this the desired functionality?

**Comment by stephenplusplus** [comment]
No! If you have a chance to write those methods better, please do!
