### ISSUE TITLE
Bigquery docs have a link that isn't click-able

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#733]
On http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.16.0/bigquery

> In the following examples from this page and the other modules (Dataset, Table, etc.), we are going to be using a dataset from data.gov (http://goo.gl/f2SXcb) of higher education institutions.

The link isn't actually click-able.

**Comment by stephenplusplus** [comment]
Worst link ever! Fixed.
