### ISSUE TITLE
support resumable upload - or documenting it

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/gcloud-node#736]
is the resumable upload function implemented natively?  if not, it'd be great to provide such support.  if it is, we should call it out in the doc.

**Comment by jgeewax** [comment]
What do we mean by "natively" here?

**Comment by stephenplusplus** [comment]
If you mean "enabled by default," it is for files over 5 MB when using bucket.upload. The docs explain that a "resumable" property exists as well as how it behaves: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.16.0/storage/bucket?method=upload. Maybe we should we add an example below explaining "how to start a resumable upload"?
