### ISSUE TITLE
Link to upstream JSON API from our docs

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#740]
Introduced in https://github.com/GoogleCloudPlatform/gcloud-node/pull/721#discussion_r35438977

Our APIs will generally try to make the upstream API a little more user-friendly by using more logical names or trimming some of the verbosity. And then we document the things we handle (things like `maxResults`, `pageSize`, `pageToken`, etc). But, most of our APIs are also a pass-through to the upstream API, which will have many more options that we don't document.

I don't think we should document everything, as there's already a place for that. And I don't think we have to limit the user's input to include only the things "we approve". We should just link to the upstream API's docs to show the full list of options and their official descriptions.

Example:

Link https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.16.0/bigquery/dataset?method=createTable to https://cloud.google.com/bigquery/docs/reference/v2/tables/insert

**Comment by callmehiphop** [comment]
Is this something you only want to do where we don't provide a complete list of the available options or should we just link every method to it's upstream counterpart?

**Comment by stephenplusplus** [comment]
Always link. I don't know if any of our method docs are actually 1:1 with the upstream. But yeah, either way, it will still be helpful for the user to see exactly what's going on from the official docs. It also will help them see exactly what our apiResponse argument will hold.

**Comment by callmehiphop** [comment]
Is search documented anywhere? I saw a few links scattered throughout the JSDoc but they're all dead now.
