### ISSUE TITLE
Take a look at model-thin? Submit any feedback?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#750]
Found https://github.com/davidrekow/model-thin-gcloud-datastore and thought it was cool. Might be helpful to give the owner a bit of feedback if there are any issues?

/cc @pcostell @stephenplusplus @callmehiphop

**Comment by stephenplusplus** [comment]
@davidrekow it's like we're stalking you :)

It looks good to me after a quick look. You know you're always welcome to open an issue here with ideas or feedback, or just ping any of us with questions.

**Comment by davidrekow** [comment]
Thanks for taking a look, I'm flattered :) In all fairness I started the stalking, by fanboying so hard over node on gce.

Super excited about the streaming API, will be adding support for that pronto - is that also available for `dataset.get()?`.

**Comment by stephenplusplus** [comment]
Go ahead and open an issue for it, that's a great idea. The conditions for which `resp.deferred` will be populated is unknown; the server decides at the time how much it can handle, then gives us that back if it was too stressed to continue. I think we could definitely support streaming by making `get` follow the traditional `nextQuery` format our other APIs use, which gives us the same behavior as now by default, but also enable streams.

**Comment by stephenplusplus** [comment]
@davidrekow I'm going to close this for now, but as you already know, ping us at any time with issues or ideas. Thanks for the help so far!
