### ISSUE TITLE
Start implementing setIamPolicy, getIamPolicy, and testIamPermissions

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/gcloud-node#758]
There is no documentations yet, but [discovery doc](https://www.googleapis.com/discovery/v1/apis/pubsub/v1/rest) already has these definitions. There is [a related question](http://stackoverflow.com/questions/31711813/gcloud-pubsub-on-node-js-how-to-set-iam-policy) on StackOverflow.

**Comment by stephenplusplus** [comment]
Thanks for the heads up!

**Comment by dhermes** [comment]
Is there some context for the addition of IAM policy?

**Comment by tmatsuo** [comment]
We published a new page for access control at:
https://cloud.google.com/pubsub/access_control

IAM methods will allow developers use finer grained ACL.
