### ISSUE TITLE
Consider providing a warning for an invalid keyfile

### ISSUE THREAD

**Issue by robertdimarco** [GoogleCloudPlatform/gcloud-node#768]
When creating a keyfile for a service account according to [GoogleCloudPlatform/gcloud-node#elsewhere](https://github.com/GoogleCloudPlatform/gcloud-node#elsewhere), it seems that the `client_email` and `client_id` fields are sometimes empty, even though (I think) they are both required to be the email address of the service account. Trying to use that credential with this module and Cloud Datastore or Cloud Storage will return an 'Invalid Grant' error when making requests.

This is just a suggestion (feel free to close-out as wont-fix) but it might be worth adding a warning from this module when those fields are missing / empty strings.

**Comment by stephenplusplus** [comment]
Thanks for the idea, and sorry for the delay in addressing it. Our auth goes through a few layers in many directions depending on the input received (keyfile vs credentials object/JSON key vs p12 key vs pem key, etc...), but after merging https://github.com/ryanseys/node-gtoken/issues/3, I think all of the holes are covered. If something is missing from any given auth input type, it should now be reported when something isn't provided before a Google API request is made.

**Comment by robertdimarco** [comment]
:+1:
