### ISSUE TITLE
Travis npm deploy failed

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#773]
@jgeewax 

https://travis-ci.org/GoogleCloudPlatform/gcloud-node/builds/73223799#L2964-L2966

Looks like we need to do something different with regards to the api_key in our [.travis.yml](https://github.com/GoogleCloudPlatform/gcloud-node/blob/b18e5e2ddfc51ea7b58a6a242a1f275670adfcba/.travis.yml#L8-L10). Here's a guide http://docs.travis-ci.com/user/deployment/npm/

**Comment by jgeewax** [comment]
Any links you can send over ?

**Comment by stephenplusplus** [comment]
Sorry, I prematurely submitted the issue. Refresh :)

**Comment by stephenplusplus** [comment]
Looks like we just need to re-generate the key: https://github.com/npm/npm/issues/8970#issuecomment-122854271

**Comment by silvolu** [comment]
@jgeewax it's probably better if you do it adding your key?

**Comment by jgeewax** [comment]
See PR #778

**Comment by stephenplusplus** [comment]
Cool, do you mind adding @callmehiphop and myself as owners?

```sh
$ npm owner add stephenplusplus gcloud
$ npm owner add callmehiphop gcloud
```

We have to manually publish the 0.17 tag. Travis will continue to fail since our 0.17.0 tag has the outdated `.travis.yml`.

**Comment by stephenplusplus** [comment]
We're live on npm with 0.17.0!

**Comment by stephenplusplus** [comment]
@jgeewax We're stuck again -- https://travis-ci.org/GoogleCloudPlatform/gcloud-node/builds/74461152#L3393 Could it be your session expired? We'll need another PR with updated credentials or handle it like last time with a manual `npm publish` in the terminal.

**Comment by jgeewax** [comment]
@stephenplusplus : Added you as an owner. Not sure what would have happened to my session.....

@silvolu , were you following the steps here (https://github.com/npm/npm/issues/8970#issuecomment-122854271) to get this working?

**Comment by stephenplusplus** [comment]
@jgeewax thanks. Published :+1:

**Comment by silvolu** [comment]
@jgeewax I followed [this travis guide](http://docs.travis-ci.com/user/deployment/npm/) at the time.
