### ISSUE TITLE
Investigate system test failures

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/gcloud-node#775]
We're green now, but the previous build choked on this

```
3) datastore querying the datastore should run a query as a stream:
Error: done() called multiple times
at Suite.<anonymous> (system-test/datastore.js:355:5)
at Suite.<anonymous> (system-test/datastore.js:236:3)
at Object.<anonymous> (system-test/datastore.js:29:1)
at Array.forEach (native)
at LOOP (fs.js:1474:14)
```

**Comment by stephenplusplus** [comment]
Just going to log anomaly system test failures here:

```
1) pubsub Topic should be listed:
      Uncaught AssertionError: 2 == 3
      + expected - actual
      -2
      +3
      
      at system-test/pubsub.js:75:16
      at lib/common/stream-router.js:9:4454
```

**Comment by callmehiphop** [comment]
good plan!

**Comment by stephenplusplus** [comment]
```
  1) Search listing documents "before all" hook:
     Uncaught TypeError: Cannot read property 'statusCode' of undefined
      at Object.parseApiResp (lib/common/util.js:166:11)
      at Object.handleResp (lib/common/util.js:139:25)
      at lib/common/util.js:572:12
      at TLSSocket.socketOnEnd (_http_client.js:300:9)
      at _stream_readable.js:908:16
```

**Comment by stephenplusplus** [comment]
(running in a Docker container)

```
2) storage "before all" hook:
     Uncaught TypeError: Cannot read property 'statusCode' of undefined
      at Object.parseApiResp (lib/common/util.js:166:11)
      at Object.handleResp (lib/common/util.js:139:25)
      at lib/common/util.js:572:12
      at TLSSocket.socketOnEnd (_http_client.js:300:9)
      at _stream_readable.js:908:16
```

**Comment by stephenplusplus** [comment]
Fact: I've just learned that if a test times out, whatever code hasn't completed yet won't be aborted. It continues processing in the background, and in our case, is possibly making many API requests.

Theory: This could cause any future test to randomly fail or produce unexpected results, as the upstream API could be feeling overwhelmed or suspicious of our requests.

**Comment by callmehiphop** [comment]
When doing a release Travis will run to jobs at once - one for the release commit and one for the tag. Both will fail and you'll get some really weird looking errors. Has this always been an issue..? We should see if it's possible to stagger the jobs.

**Comment by stephenplusplus** [comment]
I think in the future we can just push the tag commit, let Travis run, then push the tag to GH.

(Marking for inclusion in #725)

**Comment by stephenplusplus** [comment]
@callmehiphop have you noticed any test failures popping up lately? Wondering if we can call this resolved.

**Comment by callmehiphop** [comment]
A couple of timeouts here and there, but I’d say otherwise we’ve been looking pretty good.

**Comment by stephenplusplus** [comment]
Cool. For releases, I think we just need to push in two steps. One for master, then another for the tags. We can revisit if more weirdness pops up.

**Comment by stephenplusplus** [comment]
Just enabled 1 build at a time:

![Uploading Screen Shot 2015-09-02 at 7.00.55 PM.png…]()

http://docs.travis-ci.com/user/customizing-the-build/#Limiting-Concurrent-Builds

**Comment by dhermes** [comment]
:+1:
