### ISSUE TITLE
How do I create a Nearline bucket in gcloud.storage ?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#779]
Is there a storage class parameter? Do we have an example of changing it? 

https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.17.0/storage?method=createBucket seems to have a DRA example, but not a nearline example.

This is one of those things that is unlikely to change all that frequently... can we maybe have an enum-like thing for the storage classes to avoid typos?

**Comment by stephenplusplus** [comment]
Related: #773 

To do this now, it would look like:

```js
gcs.createBucket('new-bucket', { storageClass: 'NEARLINE' }, callback);
```

We could special-case the property and allow 'nearline' and 'DRA'/'dra' that we'll expand to 'NEARLINE' and 'DURABLE_REDUCED_AVAILABILITY'?

**Comment by jgeewax** [comment]
What about:

```javascript
gcs.createBucket('new-bucket', {storageClass: gcs.Nearline}, cb);
```

?

**Comment by stephenplusplus** [comment]
Sure, but I hope you don't mind if I lowercase nearline.

**Comment by jgeewax** [comment]
Sure, what do you think @callmehiphop ?

**Comment by callmehiphop** [comment]
That looks good to me
