### ISSUE TITLE
Datastrore.transaction.select & Datastore.transaction.filter not working properly in GCloud v0.14+ 

### ISSUE THREAD

**Issue by jiminikiz** [GoogleCloudPlatform/gcloud-node#806]
I have tried the following code snippets in `v-0.[14,15,16,17,18]`

```javascript
transaction.filter("email = ", email);
```
`.filter` works for `v[14,15,16]` but not `v[17,18]` with no changes to my code base. In `[17,18]` the full amount of rows from the table is returned.

```javascript
transaction.select(["date","account"]);
```
`.select` just hasn't worked for any version `[14+]`; the full amount of columns is always returned. I have not tested `.select` with any version before `[14]`.

**Comment by stephenplusplus** [comment]
Thanks for reporting the bug. We'll look into it asap.

**Comment by stephenplusplus** [comment]
I'm not able to reproduce either failure. We have a suite of tests that run against a real Datastore backend. Here's one that tests [filter](https://github.com/GoogleCloudPlatform/gcloud-node/blob/14523d3494611ea67c6c33794859b986252a2f3e/system-test/datastore.js#L383) and another that tests [select](https://github.com/GoogleCloudPlatform/gcloud-node/blob/14523d3494611ea67c6c33794859b986252a2f3e/system-test/datastore.js#L425). Are we not catching a use case similar to yours?

Pinging @pcostell in case there is a deeper reason a filter or select query might not produce the expected results.

**Comment by pcostell** [comment]
There are requirements around filters / what can be selected, however the Datastore backend will fail if these requirements are not met.

**Comment by pcostell** [comment]
@jiminikiz could you provide a test case that puts some data, then shows this failure when queryingn that data? It would be useful since it seems @stephenplusplus is not able to reproduce.

**Comment by jiminikiz** [comment]
We wrote a function that we use to run queries, it gets exported in node as a module. Here is a snippet: 

```javascript
var DataSet = require('gcloud').datastore.dataset(<ourConfig>);

module.exports = {
    ...
    query: function ( query, callback ) {
        var parameter, filter = query.filter,
            transaction = DataSet.createQuery( query.namespace, query.path );

        if ( filter !== undefined ) {
            for ( parameter in filter ) {
                transaction.filter( parameter, filter[ parameter ] );
            }
        }
        if ( query.sort !== undefined  ) {
            transaction.order( query.sort );
        }
        if ( query.select !== undefined ) {
            transaction.select( query.select );
        }
        if ( query.limit !== undefined ) {
            transaction.limit( query.limit );
        }

        DataSet.runQuery( transaction, callback );
    }
    ...
```
We usually name the export `Datastore`. Here is an example running a query:

```javascript
Datastore.query({
    namespace: 'accounts',
    path: ['account'],
    filter: { "email =": email }
}, function ( error, accounts ) {
    // do stuff
});
```

With the above snippet, accounts will be a single item array in GCloud 16 and previous. 16+, accounts is an array of every account in the `namespace > path`.

```javascript
Datastore.query({
    namespace: 'accounts',
    path: ['account'],
    filter: { "email =": email },
    select: ['name','email']
}, function ( error, accounts ) {
    // do stuff
});
```

The above query like this will return all of the columns no matter what version of Datastore I am using.

**Comment by jiminikiz** [comment]
Would you like to see the resulting payloads for each version?

**Comment by stephenplusplus** [comment]
I think I have spotted the problem. Any modification to a Query object (which is the object returned from `createQuery()` or what your snippet calls `transaction`) doesn't alter the state of the original query. Each change returns a new Query object.

Having each query be immutable was always our goal. Even though we did [refactor](https://github.com/GoogleCloudPlatform/gcloud-node/commit/7b722ac9814a480e34d0c434c0e4fa3c4f9ee2f2) the class and tests recently, we must not have noticed it wasn't working as intended before, and therefore didn't make any notes about breaking changes in the release.

The fix will be overwriting transaction with the result of the modification:

```js
module.exports = {
    ...
    query: function ( query, callback ) {
        var parameter, filter = query.filter,
            transaction = DataSet.createQuery( query.namespace, query.path );

        if ( filter !== undefined ) {
            for ( parameter in filter ) {
                transaction = transaction.filter( parameter, filter[ parameter ] );
            }
        }
        if ( query.sort !== undefined  ) {
            transaction = transaction.order( query.sort );
        }
        if ( query.select !== undefined ) {
           transaction =  transaction.select( query.select );
        }
        if ( query.limit !== undefined ) {
            transaction = transaction.limit( query.limit );
        }

        DataSet.runQuery( transaction, callback );
    }
    ...
}
```

I'm really sorry that we missed this.

**Comment by callmehiphop** [comment]
> Having each query be immutable was always our goal.

Do you think we should provide an option for creating mutable queries? It seems like @jiminikiz's case, it being immutable is pretty inconvenient, not to mention I don't know if that's a pattern we enforce throughout gcloud-node.

**Comment by stephenplusplus** [comment]
I think we should pick one or the other, and I would prefer mutable. It has historically been immutable... not sure I remember why exactly, but maybe having to do with when we call `start` while running a query, it alters the user's provided query. Definitely open to going mutable like any other object.

**Comment by callmehiphop** [comment]
Cool, I think I'd prefer it mutable as well. I'll try and put together a PR for that today or tomorrow.

**Comment by jiminikiz** [comment]
Thanks guys, the work around @stephenplusplus posted  (*overwriting transaction*) works great for now.   I'll be on the look out for when query objects do become mutable in a future version.

**Comment by stephenplusplus** [comment]
Thanks for coming by and reporting, I'm glad we figured this out. We'll have a release out today.
