### ISSUE TITLE
Enable Compute Engine API for system tests project

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#816]
@jgeewax I merged support for Compute Engine, but didn't realize our tests project would have to enable it:

> Uncaught Error: Access Not Configured. The API (Compute Engine API) is not enabled for your project. Please use the Google Developers Console to update your configuration.
> \- https://travis-ci.org/GoogleCloudPlatform/gcloud-node/#L4192

I know leaving extra resources lying around isn't a good idea with GCE. Here's the philosophy of how our system tests work: https://github.com/GoogleCloudPlatform/gcloud-node/blob/f10000f44cb8646558ea5e255db88720a595af70/system-test/compute.js#L11

If you don't want to enable it, I can come up with a way to shut off the tests conditionally. Otherwise, just let me know when it's flipped on and I'll do a release to get the GCE greatness out to the masses.

**Comment by jgeewax** [comment]
Enabled. Check if that worked and close out if so @stephenplusplus ?

**Comment by stephenplusplus** [comment]
We're green :+1: Thanks!
