### ISSUE TITLE
Authorization: Bearer your_auth_token (how to get auth_token)

### ISSUE THREAD

**Issue by navicore** [GoogleCloudPlatform/gcloud-node#818]
question: will the API give me the bearer token it is using?

I'm able to create signed urls with gcloud-node but I'm trying to follow the [resumable download docs](https://cloud.google.com/storage/docs/access-control?hl=en#signing-resumable).  they suggest starting an upload on the server and passing the session to the client.  looks easy except for the header:

```
Authorization: Bearer your_auth_token
```

can i do something like gcs.getAuth after some kind of init?

thx for any help.

**Comment by stephenplusplus** [comment]
We don't have this officially supported, but there's an opening if you go through some private properties.

With your Storage instance, try:

```js
var reqOpts = { uri: '...' }; // what you would pass to the request module

storage.makeAuthorizedRequest_(reqOpts, {
  onAuthorized: function(err, authorizedReqOpts) {
    // authorizedReqOpts.headers.Authorization = 'bearer token'
  }
});
```

I also made a module for exactly this which uses the same authorization settings as this library: https://github.com/stephenplusplus/google-auto-auth

I think our library could eventually add support for just starting a resumable upload, handing off the responsibility to the user to see it through. We currently support resumable uploads, but wrap the whole thing and hide away the details.

**Comment by jgeewax** [comment]
Can we maybe create a ticket to allow this...?

Resumable upload seems like a pretty reasonable thing to build... no?

**Comment by stephenplusplus** [comment]
Sure, new ticket it is.

**Comment by navicore** [comment]
awesome help, thanks!

**Comment by stephenplusplus** [comment]
@navicore Since this issue, I moved all of our resumable logic into [gcs-resumable-upload](https://github.com/stephenplusplus/gcs-resumable-upload). You can use it to just get a resumable URI: 

```js
var upload = require('gcs-resumable-upload');
upload.createURI({
  bucket: 'bucket-name',
  file: 'file-name',
  authConfig: {
    // how you normally auth to gcloud, ex:
    keyFilename: 'keyfile.json'
  }
}, function (err, uri) {});
```

**Comment by gotmikhail** [comment]
Is there the option to set the origin with this method? We're trying to use our API to generate a resumable uri, but the client is running on a different subdomain.

**Comment by stephenplusplus** [comment]
I think @janesconference was going to help us implement that in gcs-resumable-upload. I opened an issue about it here: https://github.com/stephenplusplus/gcs-resumable-upload/issues/6. Feel free to subscribe to that one to track the progress.

**Comment by gotmikhail** [comment]
@stephenplusplus Any other options? Ie., createWriteStream? Or, is it that setting the `origin` option isn't available right now at all?

**Comment by stephenplusplus** [comment]
I don't believe any other options exist, sadly. I'll work on adding support asap.
