### ISSUE TITLE
Support starting a resumable upload

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#819]
We should break apart the steps to start and create a resumable upload, supporting use cases like #818.

**Comment by stephenplusplus** [comment]
I added a `createURI` function to gcs-resumable-upload: https://github.com/stephenplusplus/gcs-resumable-upload#uploadcreateuriconfig-callback

@jgeewax should we still add a method in gcloud-node to call out to that, or just let users use gcs-resumable-upload for that functionality?

**Comment by winduptoy** [comment]
@stephenplusplus I see that gcs-resumable-upload is a dependency of gcloud-node. After initializing gcloud, how do I call `createURI` without requiring gcs-resumable-upload separately?

**Comment by stephenplusplus** [comment]
That's what I was wondering if we should support, and based on you asking, I think it's fair to say we should! As of now, a release with gcs-resumable-upload hasn't been made, so I will try to get that in before we get out 0.21.0. For now, you can use the module directly to get the uri.

**Comment by stephenplusplus** [comment]
Added in #852 - @winduptoy feel free to pull down my branch and give it a shot. Feedback is very welcome!

```sh
$ npm install --save stephenplusplus/gcloud-node#spp--storage-allow-starting-resumable-uploads
```
