### ISSUE TITLE
Caching of auth client regressed by #705

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/gcloud-node#822]
I believe that PR #705 regressed the earlier fix to cache the auth client I contributed in #661. This means that a new cache client is created on each API request we make, adding an unnecessary performance overhead. Here's some Cloud Trace output I get:

![image](https://cloud.githubusercontent.com/assets/79017/9483584/e645893a-4b56-11e5-911a-279a3481eb41.png)

Note the extra 141ms added to this request, and every other request.

The cause is that the function [`makeAuthorizedRequest`](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/common/util.js#L465) now passes a brand new object to `util.makeRequest` each time. We cache the authClient on that object, which is temporary and not available the next time through.

Would it be possible add a test for this to make sure this doesn't get regressed?

**Comment by stephenplusplus** [comment]
Good catch, sorry to introduce the regression. This is a good time to incorporate https://github.com/stephenplusplus/google-auto-auth into gcloud, which will cache the client for us.

**Comment by ofrobots** [comment]
Ooh, google-auto-auth looks interesting. Let me see if we can use it in [@google/cloud-trace](https://www.npmjs.com/package/@google/cloud-trace).
