### ISSUE TITLE
How are the examples and code snippets mastered and processed?

### ISSUE THREAD

**Issue by vsubramani** [GoogleCloudPlatform/gcloud-node#826]
I am looking into understanding how gcloud-node handles documentation and code examples, to learn more about where the doc example snippets are mastered and how they are automatically validated etc. 

JJ mentioned that the best way to reach the team was to open a github issue. Would one of the owners be able to reach me so that we can a quick 30 min sync?

(JJ: removing confidential content)

**Comment by jgeewax** [comment]
How about we just answer here.... Do you have specific questions that you want answered?

(I also removed confidential stuff -- sorry for editing your comment out from under you)

**Comment by jgeewax** [comment]
Also -- what do you mean by "mastered"?

**Comment by callmehiphop** [comment]
Our example code is tested when we run `npm run test`, this does the following:

* Transforms JSDoc into JSON using [`dox`](https://github.com/tj/dox) (via [shell script](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/scripts/docs.sh))
* Runs all unit tests via Mocha.

There is a [documentation spec file](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/test/docs.js) that then parses all the JSON generated via `dox` and proceeds to run all of the `@example` sections within a sandboxed environment using Node's [vm](https://nodejs.org/api/vm.html) module and [mitm](https://www.npmjs.com/package/mitm).

**Comment by jgeewax** [comment]
@vsubramani : Does this answer your question ?

**Comment by stephenplusplus** [comment]
Feel free to continue discussing if you have more questions @vsubramani. Thanks for asking!

**Comment by vsubramani** [comment]
This answers my question. Thanks folks.
