### ISSUE TITLE
Add link to gcloud-java from landing page

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-node#827]
gcloud-java needs to be added to the Node.js landing page language-switcher menu (in the top left corner).  Here's the associated logo:
![icon-lang-java-duke](https://cloud.githubusercontent.com/assets/5316886/9506169/4ac8fff0-4bfb-11e5-9ff6-8a8413312793.png)

**Comment by callmehiphop** [comment]
Currently all the logos within the language switcher are flat white svgs. I think we're going to want the gcloud-java logo to fit those same specifications.

**Comment by ajkannan** [comment]
That's a valid point.  I chose that logo because I didn't find any white svgs icons for duke on https://duke.kenai.com/ (they all have the red nose and none were svgs).  The duke icon was chosen in https://github.com/GoogleCloudPlatform/gcloud-java/issues/127, and my rudimentary attempt to convert it into an svg didn't turn out well.  Any thoughts @jgeewax?

**Comment by callmehiphop** [comment]
Decided to take a crack at it! Thoughts?

![duke](https://cloud.githubusercontent.com/assets/1707267/9508527/2f6f2058-4c24-11e5-8a7c-18aff7e0cf7b.png)

**Comment by ajkannan** [comment]
I like them, especially the one on the left since the icon will be small.

**Comment by jgeewax** [comment]
+1

**Comment by ajkannan** [comment]
Do you mind attaching a 24x24 svg of the left one so I can update the other landing pages?  Thanks for making it!

**Comment by stephenplusplus** [comment]
Nice work, Dave!

**Comment by callmehiphop** [comment]
@ajkannan doesn't look like Github allows you to attach SVGs :<

Here's a link to the source code instead!
https://raw.githubusercontent.com/callmehiphop/gcloud-node/duke/docs/site/img/icon-lang-java.svg

Let me know if that works and stuff
