### ISSUE TITLE
Time unit mismatch in File.prototype.getSignedPolicy

### ISSUE THREAD

**Issue by lastid** [GoogleCloudPlatform/gcloud-node#834]
In the [documentation](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/storage/file.js#L905) *expiration* is in seconds, but in [code](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/storage/file.js#L950), it's expected to be in milliseconds.
The given example use seconds.

**Comment by stephenplusplus** [comment]
Thanks for reporting!
