### ISSUE TITLE
Link on landing page to Python sends you to the inner page

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#836]
1. Go to https://googlecloudplatform.github.io/gcloud-node/#/
1. Click the language switcher
1. Click Python

Expected:
- end up at http://googlecloudplatform.github.io/gcloud-python/

Actual:
- http://googlecloudplatform.github.io/gcloud-python/latest/

(I think even the switcher inside should probably send you to http://googlecloudplatform.github.io/gcloud-python/stable/ (not /latest)

**Comment by callmehiphop** [comment]
Looks like we do this for Ruby as well.
