### ISSUE TITLE
metadata property types

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/gcloud-node#85]
Right now the metadata describes a property type (string, int, etc) as a kind. This is a little overloaded with the concept of a Kind in datastore. Perhaps these could all be called `type` instead? Then metadata would look like:

```
registerKind('namespace', 'Author', {
    name: { type: STRING, indexed: false },
    tags: { type: STRING, multi: true }, // an array of string elements.
    favArticles: { type: KEY, multi: true }
    contact: {
        kind: {
          telephone: { type: STRING },
          email: { type: STRING }
        }
    }
});
```

**Comment by stephenplusplus** [comment]
@pcostell obviously, a lot has changed over the last 15 months. Is there anything for me to do here?

**Comment by pcostell** [comment]
I don't think so. Did this metadata registration ever make it into the project?

**Comment by stephenplusplus** [comment]
Nope. In general, our library is pretty relaxed when it comes to types and validation and such. Beyond common utilities, we leave it to the user to create helpers where they make sense given their own projects and workflows. Then, where applicable, we let the API catch any errors from input mismatches.

Datastore is arguably the most complex API we support, so I can see how it could be valuable in this case, however. What do you think? Would the majority of codebases using Datastore benefit from this concept?

**Comment by pcostell** [comment]
I think that would be more beneficial for a higher level, maybe 3rd party library. Or even some sort of adapter to an existing framework. I think keeping the gcloud API relatively simple is better.
