### ISSUE TITLE
Support Resource Manager API

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#851]
Let's add support for the Resource Manager API to gcloud. I'm pretty excited about this one!

[What is Resource Manager?](https://cloud.google.com/resource-manager/)

[Resource Manager API](https://cloud.google.com/resource-manager/reference/rest/)

**Comment by stephenplusplus** [comment]
Given that Resource Manager is a lengthy term... and the concept is really just "projects"... and a project is so close to the core concept of using a gcp client library... I'm wondering if this is the first thing we should put directly onto the `gcloud` instance:

```js
var gcloud = require('gcloud');

gcloud.createProject('new-project-123', function(err, project) {});

gcloud.getProjects(function(err, projects) {});

var project = gcloud.project('grape-spaceship-123');

project.delete(function(err) {});
project.restore(function(err) {});

project.getMetadata(function(err, metadata) {});
project.setMetadata({/*...*/}, function(err) {});
```

// @jgeewax @callmehiphop thoughts?

**Comment by callmehiphop** [comment]
Is it likely that the resource manager api will ever do more than just projects?

**Comment by stephenplusplus** [comment]
It looks like there are Organizations as well (https://developers.google.com/apis-explorer/?hl=en_US#p/cloudresourcemanager/v1beta1/)

Maybe it's best to just keep resources:

```js
var gcloud = require('gcloud');
var resources = gcloud.resources({...});

resources.getProjects();
var project = resources.project('grape-spaceship-123');
```

**Comment by callmehiphop** [comment]
I like that, `projects.getProjects(...)` read kinda funny to me.

**Comment by stephenplusplus** [comment]
Vote!

```js
// a
var resources = gcloud.resources();
resources.getProjects();
resources.project('grape-spaceship-123');

// b
var resourceManager = gcloud.resourcemanager();
resourceManager.getProjects();
resources.project('grape-spaceship-123');

// c
var resource = gcloud.resource();
resource.getProjects();
resource.project('grape-spaceship-123');

// d
??
```

**Comment by callmehiphop** [comment]
I like `c`.

`a` sounds kinda funny to me with back to back plural nouns
`b` is maybe a little too lengthy for my tastes

**Comment by stephenplusplus** [comment]
C it is!

@jgeewax My project (that has resource manager API enabled) can list my projects and get their metadata. However, I get a 403 when I try to create one:

```
REQUEST
  method: 'POST'
  uri: 'https://cloudresourcemanager.googleapis.com/v1beta1/projects/'
  json: { projectId: 'gcloud-tests-1441915137564' }
  headers
   { Authorization: 'Bearer /*token*/',
     'User-Agent': 'gcloud-node/0.21.0' }

RESPONSE
  vary: 'X-Origin, Referer, Origin,Accept-Encoding'
  'content-type': 'application/json; charset=UTF-8'
  date: 'Thu, 10 Sep 2015 20:02:52 GMT'
  server: 'ESF'
  'cache-control': 'private'
  'x-xss-protection': '1; mode=block'
  'x-frame-options': 'SAMEORIGIN'
  'x-content-type-options': 'nosniff'
  'alternate-protocol': '443:quic,p=1'
  'alt-svc': 'quic=":443"; p="1"; ma=604800'
  'accept-ranges': 'none'
  connection: 'close'
```

I'm not sure how to auth this one; so far, gcloud lets users control *one* project's sub-services using a service account for it. What do we need to get to have control over all of their projects?

**Comment by jgeewax** [comment]
Yea, creating right now can only be done by a "person". In Python, this works by first running `gcloud auth login` on the command-line.

Does gcloud-node pick up the Cloud SDK's credentials in the same way? If so, these will work nicely.

Eventually, service accounts will be able to create projects, but that isn't the case yet.

**Comment by stephenplusplus** [comment]
Replied over at #864

**Comment by stephenplusplus** [comment]
Is it possible falling back to the gcloud sdk token doesn't work here because it doesn't request the scopes needed for this API? (nothing about Logging or the all encompassing `auth/cloud-platform` scope).

![Uploading Screen Shot 2015-09-21 at 3.07.38 PM.png…]()
