### ISSUE TITLE
Support for Node v4

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#854]
`master` works already with 4, but not 0.20. We need to release a new version.

We should also update our `travis.yml` to include v4.

**Comment by jgeewax** [comment]
+1 to this -- let's try to get this out sometime this week?

**Comment by jokesterfr** [comment]
I confirm this, cannot build gcloud npm dependencies with node v4

**Comment by stephenplusplus** [comment]
@jokesterfr shortcut:
```sh
npm install --save googlecloudplatform/gcloud-node
```

But, v0.21.0 should release today after #856 merges.

**Comment by stephenplusplus** [comment]
Released and supported!

**Comment by jokesterfr** [comment]
@stephenplusplus thanks a lot for the release!

**Comment by stephenplusplus** [comment]
Thanks for testing for us! Keep in touch :)
