### ISSUE TITLE
Implement custom errors

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/gcloud-node#859]
Related to https://github.com/GoogleCloudPlatform/gcloud-node/pull/857#discussion_r39123168

It would be nice to have custom error types in certain places to improve the error messages we provide to the user - instructing the user to access non standard properties to get the full error message seems painful, IMO errors should be obvious and in the users face.

**Comment by stephenplusplus** [comment]
That's a wrapped error. We don't know what the underlying error is, so instead of giving them something potentially cryptic, we wrap it to at least let the user know what failed. How could a custom error type solve that?

**Comment by callmehiphop** [comment]
I think if the error name was descriptive enough then the user should be able to deduce what happened without having to access additional properties for more info.

e.g.

`SigningError: Cryptic error message`

vs.

`Error: Signing failed, see error property for more info`
err.error // => Cryptic error message

**Comment by stephenplusplus** [comment]
I'd have to say, that makes a lot of sense!
