### ISSUE TITLE
Make it clear in examples that bucket names must be globally unique

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#863]
https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.21.0/storage?method=createBucket

We don't clarify anywhere that buckets (unlike almost everything else in Google Cloud) must have unique names across the global namespace. Can we clarify this in our docs and samples?

Ie, `// The name of your bucket must be globally unique`

6/7 of participants in a UX study hit a naming error not realizing that names have to be unique for the whole world, not just inside their project.

**Comment by stephenplusplus** [comment]
+1!

**Comment by callmehiphop** [comment]
Nice, are the UX studies available for us to peruse?
