### ISSUE TITLE
Resource Manager can't be used on a global basis

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#864]
Resource Manager support was integrated in #860, but with [many limitations](https://github.com/GoogleCloudPlatform/gcloud-node/pull/860#issuecomment-140187895):

> these methods [are] currently implemented and unit tested, but not exposed to our docs:

> - `resource.createProject`
> - `project.delete`
> - `project.restore`
> - `project.setMetadata`

Right now, Resource Manager can only get a list of projects from a user and the metadata for them. Other operations (the ones above) return a 403.

**Comment by stephenplusplus** [comment]
Carrying this over from #851:

> Yea, creating right now can only be done by a "person". In Python, this works by first running `gcloud auth login` on the command-line.

> Does gcloud-node pick up the Cloud SDK's credentials in the same way? If so, these will work nicely.

> Eventually, service accounts will be able to create projects, but that isn't the case yet.

> \- @jgeewax

We do support the gcloud sdk's credentials (thanks to google-auth-library), but it still returns "The caller does not have permission" when trying to create a project. To confirm the credentials are being picked up, after doing `gcloud auth revoke`, the same API call returns "invalid_grant" instead.

**Comment by stephenplusplus** [comment]
@jgeewax maybe a whitelisting issue? Project ID is nth-circlet-705.

**Comment by jgeewax** [comment]
Give it a try now?

**Comment by stephenplusplus** [comment]
It works! So, I guess since this is just an issue of the API being officially released, there's nothing left to do with the codebase.

**Comment by jgeewax** [comment]
Yep -- it's just a whitelist only API apparently... the docs are public,
but the API itself is 'by request'
