### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by swilly22** [GoogleCloudPlatform/gcloud-node#868]
roilipman:bq-node roilipmangmailcom$ npm install gcloud
npm WARN package.json bq-node@1.0.0 No description
npm WARN package.json bq-node@1.0.0 No repository field.
npm WARN package.json bq-node@1.0.0 No README data

> sse4_crc32@4.1.0 install /Users/roilipmangmailcom/Dev/bq-node/node_modules/gcloud/node_modules/hash-stream-validation/node_modules/sse4_crc32
> node-gyp rebuild

  CXX(target) Release/obj.target/crc32c_sse42/src/crc32c_sse42.o
  LIBTOOL-STATIC Release/crc32c_sse42.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/crc32c_sse42.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/roilipmangmailcom/Dev/bq-node/node_modules/gcloud/node_modules/hash-stream-validation/node_modules/sse4_crc32
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN engine hoek@2.16.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine hoek@2.16.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine hoek@2.16.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm ERR! sse4_crc32@4.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sse4_crc32@4.1.0 install script.
npm ERR! This is most likely a problem with the sse4_crc32 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sse4_crc32
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "gcloud"
npm ERR! cwd /Users/roilipmangmailcom/Dev/bq-node
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by stephenplusplus** [comment]
This is an issue with one of our dependencies. Please open an issue on their repository: https://github.com/Voxer/sse4_crc32/issues/new

**Comment by jgeewax** [comment]
Yet another install fail :(

Any new thoughts on dealing w this?

**Comment by stephenplusplus** [comment]
See https://github.com/stephenplusplus/hash-stream-validation/pull/2. Waiting for an upstream PR to be merged, which will let us fallback to a software solution if the install fails.

**Comment by anandsuresh** [comment]
This has been resolved on https://github.com/Voxer/sse4_crc32/issues/45. The issue was the version of `libtool` was incorrect on @swilly22's machine.

**Comment by stephenplusplus** [comment]
Thanks @anandsuresh!

**Comment by sectore** [comment]
Have had a similar issue on my local machine. `ls -la $(which libtool)` as mentioned [here](https://github.com/Voxer/sse4_crc32/issues/45) pointed to a deprecated version of `libtool` installed by `MAMP`. Switching to `/usr/bin/libtool` solved this issue.
