### ISSUE TITLE
Upgrade Datastore to use v1beta3

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#872]
/cc @pcostell @stephenplusplus

**Comment by dhermes** [comment]
Is `v1beta3` launched officially?

**Comment by jgeewax** [comment]
Nope, but we can have a fork to get things moving. (Search isn't launched officially either, and it's here :P)

**Comment by dhermes** [comment]
Gotcher.

**Comment by JustinBeckwith** [comment]
Thanks folks.  This will really help not only improve perf, but consistency in the documentation.  Appreciated!

**Comment by stephenplusplus** [comment]
Is there a place to see what's changed?

**Comment by pcostell** [comment]
@stephenplusplus I've emailed you the (WIP) release notes. Eventually they'll be available on cloud.google.com/datastore/docs.

**Comment by stephenplusplus** [comment]
Thanks @pcostell! I haven't received anything yet; did you use sawchuk@gmail.com?

**Comment by stephenplusplus** [comment]
Just for an update, I've begun implementing this, and have been receiving help from @pcostell along the way with various protobuf issues/questions. If all goes well, a PR should be available before the end of the week.

Also worth noting, to test the implementation, your project will have to be whitelisted. @JustinBeckwith + @pcostell: Is there an estimated release date available? If it's not anytime too soon, we should be sure to add @callmehiphop's project (what is it? :))

**Comment by callmehiphop** [comment]
`boreal-physics-911`

**Comment by pcostell** [comment]
Done. No update yet on the release date, but we are getting close.

**Comment by stephenplusplus** [comment]
Having an issue with the protobuf parser (or something else, not sure yet) https://github.com/dcodeIO/ProtoBuf.js/issues/329

**Comment by stephenplusplus** [comment]
Problem resolved!

Note to self for my upcoming PR: include the "proto" directory in package.json#files.
