### ISSUE TITLE
Possibly memory leak

### ISSUE THREAD

**Issue by jakeorr** [GoogleCloudPlatform/gcloud-node#873]
I'm running gcloud in an express app along with memwatch. As soon as I `require('gcloud')` I get a leak reported. Is anyone else seeing this?

`gcloud-node` version: 0.21.0
`node` version: 0.10.26
`express` version: 4.13.3
`memwatch` version: 0.2.2

**Comment by jgeewax** [comment]
Woah! Thanks for reporting! We should definitely dig into this one.....

**Comment by stephenplusplus** [comment]
Thanks for reporting. Would you mind sharing the code you're using to test with?

**Comment by jakeorr** [comment]
Oh, I should also mention that I am running this outside of the Google Compute Engine.

Before the express app starts listening, memwatch is started up with:

```
var memwatch = require('memwatch');
memwatch.on('leak', reportLeak);
```

If I include `require('gcloud');` anywhere after that memwatch code, I see a leak immediately after startup.

**Comment by jakeorr** [comment]
I don't know how much help that small amount of code will be. I will see if I can reproduce the problem in a simple express app.

**Comment by stephenplusplus** [comment]
Thanks, that would be great. I tried with:

```js
'use strict';

var memwatch = require('memwatch');
memwatch.on('leak', console.log);

var express = require('express');
var app = express();

app.get('/', function(req, res) {
  require('gcloud');
  res.end('Hi');
});

app.listen(8080);
```

... then visited http://localhost:8080 in the browser, but nothing was reported. A more simple version was tested as well, with just requiring gcloud directly after subscribing to the leak event.

**Comment by jakeorr** [comment]
Thanks for your quick response! I can get the leak to occur by requiring both `gcloud` and `googleapis`:

`index.js`:
```
'use strict';

var memwatch = require('memwatch');
memwatch.on('leak', console.log);

require('gcloud');
require('googleapis');
```

Running this directly with `node index` gives the leak I have been seeing:

```
{ start: Fri Sep 18 2015 17:24:00 GMT-0700 (PDT),
  end: Fri Sep 18 2015 17:24:00 GMT-0700 (PDT),
  growth: 35780008,
  reason: 'heap growth over 5 consecutive GCs (0s) - -2147483648 bytes/hr' }
```

**Comment by stephenplusplus** [comment]
Hmm, I haven't been able to reproduce. @callmehiphop can you?

Are you able to update to a newer version of Node? The latest stable release is 4.0 and before that, 0.12, so 0.10.26 is quite a few behind. The only downer is `memwatch` doesn't work with > 0.10, so testing for the leak this way wouldn't be possible.

**Comment by callmehiphop** [comment]
I ran this in the repl and successfully reproduced it, but only after I
required `googleapis`

**Comment by jakeorr** [comment]
I'm seeing the same behaviour. It's only when I require both `googleapis` and `gcloud` that I see the leak reported.

I am going to upgrade Node today. Too bad about `memwatch` not supporting 4, but I will see if I can test the leak some other way. Thanks for the input.

**Comment by jakeorr** [comment]
I updated to Node v4 (which felt good btw), and found an [updated version](https://github.com/marcominetti/node-memwatch) of `memwatch`. I am no longer seeing the memory leak so I think this can be closed. Thanks for the response on this, everyone!

**Comment by stephenplusplus** [comment]
Thanks for reporting! It's curious that there was a leak reported originally. As much as I want to use the new features of ES6, we're trapped with supporting .10 and .12 for a little longer, yet. Considering that, I wonder if the folks at the googleapis repo would be interested. Would you mind opening an issue over there just to give them a heads up they may want to dig into it? (https://github.com/google/google-api-nodejs-client)

**Comment by jakeorr** [comment]
Posted! https://github.com/google/google-api-nodejs-client/issues/470

**Comment by stephenplusplus** [comment]
Thanks :)
