### ISSUE TITLE
[BUG] Sometimes, Key element in Datastore is parsed as id 

### ISSUE THREAD

**Issue by dg3feiko** [GoogleCloudPlatform/gcloud-node#874]
### Env
Node: 2.3.3
gcloud: 0.21.0

### Problem
dataset.key(['Tracking2', "556ba07cbeb676ba7e9458e8"]) => key path: `name =556ba07cbeb676ba7e9458e8`
but 
`dataset.key(['Tracking2', "55479506996815820615e988"])` => key path: `id=-9204792730274402000`

### Root cause
https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/datastore/entity.js#L227
```
> isNaN("556ba07cbeb676ba7e9458e8")
true
> isNaN("55479506996815820615e988")
false
```
explain: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Description

**Comment by jgeewax** [comment]
Woah-- tricky. Nice catch.

**Comment by stephenplusplus** [comment]
Very nice! A PR is welcome to use `is.number` instead, otherwise someone will jump on this soon. Thanks for reporting!
