### ISSUE TITLE
cant make signed url

### ISSUE THREAD

**Issue by stellanhaglund** [GoogleCloudPlatform/gcloud-node#877]
I get this

/home/server/node_modules/gcloud/node_modules/google-auto-auth/index.js:47
    client.authorize(function (err) {
           ^
TypeError: undefined is not a function
    at /home/server/node_modules/gcloud/node_modules/google-auto-auth/index.js:47:12
    at addScope (/home/server/node_modules/gcloud/node_modules/google-auto-auth/index.js:113:5)
    at callback (/home/server/node_modules/gcloud/node_modules/google-auto-auth/node_modules/goo
gle-auth-library/lib/auth/googleauth.js:41:5)
    at /home/server/node_modules/gcloud/node_modules/google-auto-auth/node_modules/google-auth-l
ibrary/lib/auth/googleauth.js:124:9
    at process._tickCallback (node.js:355:11)

when running this

    app.get('/file/:fileId', function(req, res){

    var remoteFile = bucket.file(req.params.fileId);

    remoteFile.getSignedUrl({
        action: 'read',
        expires: '2025'
    }, function(err, url) {
        if (err) {
            console.log('err');
            return;
        }

        console.log(url)

    });

    });

**Comment by stephenplusplus** [comment]
Can you show where gave auth configuration to gcloud?

**Comment by stellanhaglund** [comment]
var projectId = 'idid'; // E.g. 'grape-spaceship-123' 

var gcloud = require('gcloud')({
	projectId: projectId
});

**Comment by stephenplusplus** [comment]
Thanks, I was able to reproduce. Will keep you posted!

**Comment by stephenplusplus** [comment]
I published a new version of `google-auto-auth` that will return a more helpful error. The problem here is in order to sign URLs, we need two properties that can't be detected in an auto-auth'd environment (like on GCE): `client_email` and `private_key`.

To enable this method to work, you'll have to authenticate with a keyfile (JSON, pem, or p12).

Related issue: #211

**Comment by andreasgrimm** [comment]
I'm able to download a file with the `.download()` method, but using `getSignedURL()` results in the error 

`TypeError: bucket.file(...).getSignedURL is not a function`

I'm using a firebase-storage bucket, I have a json key file including `client_email` and `private_key`.
Is this still a ACL / rights issue ?

**Comment by stephenplusplus** [comment]
Try calling `getSignedUrl` (note the casing). It probably should have been `getSignedURL`, shouldn't it have?

**Comment by andreasgrimm** [comment]
That works!

and it's what the offical API docs say as well: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.36.0/storage/file?method=getSignedUrl

... but not this post: https://stackoverflow.com/questions/37824361/generate-download-url-after-successful-upload

... and not this post: https://stackoverflow.com/questions/37868485/secure-external-links-for-firebase-storage-on-nodejs-server-side

Thanks a ton !!

**Comment by stephenplusplus** [comment]
No problem! Thanks for sending the edits in to those posts!
