### ISSUE TITLE
Travis release jobs fail on second pass

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/gcloud-node#882]
Now that we're supporting multiple node versions via CI, we need to update our release scripts. When and if the second pass finishes (0.12), it will fail at creating a new folder for the documentation JSON, because it already exists from the previous pass (4.x).

**Comment by stephenplusplus** [comment]
It would be great to run our after hook only after all tests pass, since technically, we don't know if our code is good until they do. I found something a week or so ago that could help. Do you remember the link by chance?

**Comment by callmehiphop** [comment]
I think it was https://github.com/alrra/travis-after-all ?

**Comment by stephenplusplus** [comment]
Fixed by #893
