### ISSUE TITLE
'auto_insert_id' in documentation should be 'insert_auto_id'

### ISSUE THREAD

**Issue by MMMMasterM** [GoogleCloudPlatform/gcloud-node#883]
The documentation as well as a comment in the source files list 'auto_insert_id' as last insert method for the datastore, however checking the source revealed that it should be 'insert_auto_id'. 
Also specifying an invalid method (e.g. 'auto_insert_id') does not report any error in the callback and doesn't throw which made finding the error harder than necessary. 

Please fix the documentation and change the lib to report an error or throw when an invalid datastore insert/save method is specified.

**Comment by stephenplusplus** [comment]
You got it. Thanks for catching this!
