### ISSUE TITLE
"invalid ELF header" thrown by sse4_crc32

### ISSUE THREAD

**Issue by tylerbrandt** [GoogleCloudPlatform/gcloud-node#888]
I'm having the same issue as #781 on the latest release (0.22.0), only with the following error:
```
Error: /app/node_modules/gcloud/node_modules/hash-stream-validation/node_modules/sse4_crc32/build/Release/sse4_crc32.node: invalid ELF header
```
The workaround in that issue to `cd` into the `sse4_crc32` directory and run `make` doesn't work for me either because `node-gyp` is in `devDependencies` in that package and therefore not included, resulting in `make clean` failing:
```
Step 5 : RUN cd node_modules/gcloud/node_modules/hash-stream-validation/node_modules/sse4_crc32/ && make clean && make && /nodejs/bin/npm run-script debug
---> Running in 4f2698893437
./node_modules/.bin/node-gyp clean
make:
./node_modules/.bin/node-gyp: Command not found


make:
[clean] Error 127 (ignored)


./node_modules/.bin/node-gyp clean
make:
./node_modules/.bin/node-gyp: Command not found
```
Dockerfile:
```
# note that the standard docker image is: https://registry.hub.docker.com/u/google/nodejs-runtime/
# I modified it to skip the npm install step as that will require some more work to deal with private
# github hosted npm packages.

FROM google/nodejs

WORKDIR /app
ADD package.json /app/
ADD . /app/
ENV NODE_ENV=production

# Workaround for https://github.com/GoogleCloudPlatform/gcloud-node/issues/781
RUN cd node_modules/gcloud/node_modules/hash-stream-validation/node_modules/sse4_crc32/ && make clean && make && /nodejs/bin/npm run-script debug

EXPOSE 8080
CMD []
ENTRYPOINT ["/nodejs/bin/npm", "start"]
```
(note that we are running `npm install --production` prior to deploying in order to include some private dependencies)

Is there a way around this?

**Comment by stephenplusplus** [comment]
Sorry to hear this is happening. We get a lot of reports of issues with the native dependency here, but we can't be as helpful as the module creators themselves. Would you mind opening the issue over at their repo? https://github.com/Voxer/sse4_crc32/issues/new

Please link back to this issue so others who may come upon this issue can stay up to date.
