### ISSUE TITLE
No way to pin to subheadings on Authentication page?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#899]
I wanted to send a reference to the "With gcloud-node" section on http://googlecloudplatform.github.io/gcloud-node/#/authentication but it looks like there's no paragraph anchor link...

Any chance we can add one of those?

**Comment by callmehiphop** [comment]
It doesn't look like any of the markdown content has anchor tags.. was it always like this? Regardless, I'm not sure if showdown offers this as an option so we may have to write an extension.

**Comment by jgeewax** [comment]
I'm not sure if we ever had this working -- I suspect not... however maybe h2 and higher should have anchors? Or all headings?

Not the most important thing, but definitely something in the "nice to have" category.

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/gcloud-common#40
