### ISSUE TITLE
`runQuery` doesn't run inside transaction

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/gcloud-node#905]
Sorry if this isn't right, I only noticed it through inspection.

It looks like Transaction extends from DatastoreRequest, which means it gets a `runQuery` method. However, it doesn't look like it overrides it. This means a user who *thinks* they are running a query in the transaction is actually going to get inconsistent results.

**Comment by stephenplusplus** [comment]
I think it will work as intended. When the API request is made, it goes through this method: https://github.com/GoogleCloudPlatform/gcloud-node/blob/69046d383af6bf67a316739c66650601228abc8a/lib/datastore/request.js#L759:

```js
DatastoreRequest.prototype.makeReq_ = function(method, body, callback) {
  // ...

  if (method === 'lookup' && this.id) {
    body.read_options = body.read_options || {};
    body.read_options.transaction = this.id;
  }

  // ...
```

`this.id` is set to the transaction ID when using a Transaction object.

**Comment by pcostell** [comment]
That's if the method is 'lookup'. But what if the method is 'runQuery'?

**Comment by stephenplusplus** [comment]
Ah, woops. So I think we just need `this.id && (method === 'lookup' || method === 'runQuery')`.
