### ISSUE TITLE
Embed the bug filing form in our docs?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#906]
Looks like the GH guys make this pretty easy, where we could just fire off an AJAX request for issues...

This might be something to look into more ... 

https://developer.github.com/v3/issues/#create-an-issue

+ screenshot

<img width="455" alt="screen shot 2015-10-06 at 10 39 32 am" src="https://cloud.githubusercontent.com/assets/112928/10314020/964b7ff8-6c20-11e5-8b72-73e995c643eb.png">

don't know if we can make it that pretty... but... :)

**Comment by stephenplusplus** [comment]
This could be cool, but I think it only works for repo owners, probably after going through an oauth GH signin process:

> Any user with pull access to a repository can create an issue.

**Comment by jgeewax** [comment]
I think most users should have pull access -- but not push access (ie,
editing requires push access
https://developer.github.com/v3/issues/#edit-an-issue)

**Comment by callmehiphop** [comment]
I like it! 

Should we make a repo for docs? I only ask because I know python and ruby (and maybe php?) are probably going to want this functionality as well, not to mention we may eventually move to a templated site for docs.

**Comment by jgeewax** [comment]
I think the plan is:

- put most work into gcloud-node docs angular app
- get other repos spitting out JSON consumable by that app
- split gcloud-node app into a separate repository
- make the "update docs" task clone that repository, and ship it (+ the
JSON generated) to gh-pages

seem reasonable?

**Comment by callmehiphop** [comment]
yep!

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/gcloud-common#39
