### ISSUE TITLE
New Google Cloud Platform icon for docs site

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/gcloud-node#908]
I noticed [your site](https://googlecloudplatform.github.io/gcloud-node/#/) is still using the old Google logo in the header. Below I have attached the new logo to replace it.

![new-gcp-logo](https://cloud.githubusercontent.com/assets/163873/10439205/3b2b1aee-70ed-11e5-9e0d-d3a8e6a924d9.png)

**Comment by dhermes** [comment]
Ohhhh fancy

**Comment by stephenplusplus** [comment]
I think we need this in higher quality and SVG. Know of any asset stashes?

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/gcloud-common#38
