### ISSUE TITLE
Failing build? Docs problem?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-node#912]
https://travis-ci.org/GoogleCloudPlatform/gcloud-node/jobs/84518538

**Comment by stephenplusplus** [comment]
I don't know what happened there, but restarted it and green again. Travis.

**Comment by stephenplusplus** [comment]
Oh, that test was run from my "don't merge" datastore v1beta3 upgrade PR, which at the time was not unit tested.
