### ISSUE TITLE
`exists` method for storage/bucket#file ?

### ISSUE THREAD

**Issue by wong2** [GoogleCloudPlatform/gcloud-node#914]
Currently I can't find a method to check if a file is already existed in the bucket.

**Comment by stephenplusplus** [comment]
We don't have this method (yet/something like it/maybe) but this is what it would do:

file.getMetadata(function(err) {
  if (err.code === 404) {
    // doesn't exist
  }
});

**Comment by wong2** [comment]
@stephenplusplus thanks! btw I think this should be added to the document.

**Comment by jgeewax** [comment]
I'm +1 for adding this as a method.....

**Comment by stephenplusplus** [comment]
The last discussion (#862) ended up (#904) with:

- File.create
- File.get
- File.getOrCreate

Do you want `exists` in addition to those?

**Comment by jgeewax** [comment]
I think `exists` is a super simple shortcut around `get` -- so yea, I'd be :+1: to adding it to the list.

**Comment by stephenplusplus** [comment]
`exists` exists! It will be released this week across all of our APIs (except Datastore for now).

**Comment by wong2** [comment]
great!

发送自 Outlook




On Tue, Nov 17, 2015 at 11:16 AM -0800, "Stephen Sawchuk" <notifications@github.com> wrote:












Closed #914.
