### ISSUE TITLE
Add API to create preemptible VMs

### ISSUE THREAD

**Issue by gabipetrovay** [GoogleCloudPlatform/gcloud-node#925]
The [createVM](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.24.1/compute/zone?method=createVM) API method does not seem to expose the `--preemptible` option of the command line tool:

```
gcloud compute instances create --preemptible ...
```

Is this achieved in another way or is it missing?

**Comment by stephenplusplus** [comment]
Give this a shot:

```js
zone.createVM('new-vm-name', {
  // ... options ...
  scheduling: {
    preemptible: true
  }
}, function(err, vm, operation, apiResponse) {});
```

The second argument to `createVM` is the same object that is outlined here: https://cloud.google.com/compute/docs/reference/latest/instances -- so in theory, if that supports what you need, so do we :)

**Comment by stephenplusplus** [comment]
Going to close. Thanks for asking. Please re-open if this didn't resolve the issue.

**Comment by gabipetrovay** [comment]
Yes, with the `preemptible: true` option it works. Thanks!
