### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by MKHenson** [GoogleCloudPlatform/gcloud-node#937]
Hi guys

Is there a way for us to set the CORS properties of the buckets via the node API? If so, are there any examples?

Thanks

**Comment by stephenplusplus** [comment]
You can! See [`bucket#setMetadata`](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.24.1/storage/bucket?method=setMetadata). The `metadata` argument accepts everything documented [here](https://cloud.google.com/storage/docs/json_api/v1/buckets/patch).

```js
bucket.setMetadata({
  cors: [
    {
      origin: ['http://example.appspot.com'],
      responseHeader: ['Content-Type'],
      method: ['GET', 'HEAD', 'DELETE'],
      maxAgeSeconds: 3600
    }
  ]
}, function(err) {});
```

Let me know if you run into any issues.

**Comment by daslicht** [comment]
I get the same error even tho I have set the Metadata:
```
            bucket.setMetadata({
                cors: [
                    {
                    origin: ['//storage.googleapis.com/'],
                    responseHeader: ['Content-Type'],
                    method: ['GET', 'HEAD', 'DELETE'],
                    maxAgeSeconds: 3600
                    }
                ]
            }, err => {});
```

I am trying to create a Thumbnail from a video using canvas, as far as I call:
```		var dataURL = canvas.toDataURL("image/jpeg", 1.0);```
I get: 

```
"Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
```

idea?

**Comment by bedeoverend** [comment]
@daslicht don't know if you already solved this one. But on the `image` you're loading into the canvas, are you setting `crossOrigin = 'Anonymous'`? That might help. See https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

**Comment by daslicht** [comment]
@bedeoverend yeah , already solved :) Thank you very much !
