### ISSUE TITLE
pubsub.subscribe doesn't pass on options properly

### ISSUE THREAD

**Issue by mpj** [GoogleCloudPlatform/gcloud-node#949]
Looking at the implementation of pubsub.subscribe, it seems like it doesn't pass on any options except ackDeadlineSeconds in the request. 
https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/pubsub/index.js#L413

This also means that I cannot specify an pushEndpoint in the subscription.

**Comment by stephenplusplus** [comment]
Hmm, yes. Good catch, thank you! I'll try to get this fixed and released today.

**Comment by stephenplusplus** [comment]
Released! https://github.com/GoogleCloudPlatform/gcloud-node/releases/tag/v0.25.0

**Comment by mpj** [comment]
HOLY TURNROUND TIME BATMAN
