### ISSUE TITLE
No external ip for created VM

### ISSUE THREAD

**Issue by Omberone** [GoogleCloudPlatform/gcloud-node#953]
Hello,
We don't get an external IP assigned for our newly created VM. We create a VM with the following script;
```javascript
var zone = gce.zone('europe-west1-b');
var name = 'testing';
var BUILDER_MACHINE_CONFIG = {
    machineType: "n1-standard-1",
    disks: [{
        autoDelete: true,
        boot: true,
        initializeParams: {
            sourceImage: 'https://www.googleapis.com/compute/v1/projects/PROJECT/global/images/custom-img'
        }
    }]
};
zone.createVM(name, BUILDER_MACHINE_CONFIG, function(err, vm, operation, apiResponse) {
        console.log(err);
        operation.on('complete', function(metadata) {
                console.log('completed');
        });
});
```
And it does create an instance successfully, but no IP is assigned and there is no option to SSH into it. Anyone able to shed some light on this?

**Comment by Omberone** [comment]
So the IP is not ephemeral by default, and we don't know how to set it to be ephemeral when we create the instance.

**Comment by Omberone** [comment]
Turns out I didn't have an accessConfig set, which prompted the instance to not be created with an ephemeral IP. Here's the functioning code;

´´´javascript
var zone = gce.zone('europe-west1-b');
var name = 'testing';
var BUILDER_MACHINE_CONFIG = {
    machineType: "n1-standard-1",
    disks: [{
        autoDelete: true,
        boot: true,
        initializeParams: {
            sourceImage: 'https://www.googleapis.com/compute/v1/projects/PROJECT/global/images/custom-img'
        }
    }],
    networkInterfaces: [{
        network: 'global/networks/default',
        accessConfigs: [
        {
            kind: 'compute#accessConfig'
        }]
    }]
};
zone.createVM(name, BUILDER_MACHINE_CONFIG, function(err, vm, operation, apiResponse) {
        console.log(err);
        operation.on('complete', function(metadata) {
                console.log('completed');
        });
});
´´´

Hope this helps someone else in the same situation!

**Comment by NickZ** [comment]
thanks, this helped me out.
