### ISSUE TITLE
need example of how to store unindexed,binary data in datastore

### ISSUE THREAD

**Issue by bradabrams** [GoogleCloudPlatform/gcloud-node#971]
I can't figure out how to store an entity in datastore that has this field...  Any idea? Any example would be great

filecontents: {blobValue: filecontents, indexed: false},

**Comment by jgeewax** [comment]
I think the answer is to use a [Buffer](https://nodejs.org/api/buffer.html) which we'll then notice is a buffer, and set the value as the `blob_value` in the proto, which shouldn't be indexed... (code is [here](https://github.com/GoogleCloudPlatform/gcloud-node/blob/69046d383af6bf67a316739c66650601228abc8a/lib/datastore/entity.js#L411))

So the example would look like:

```javascript
var gcloud = require('gcloud')({ keyFilename: '/path/to/keyfile.json' });
var datastore = gcloud.datastore;
var dataset = datastore.dataset({projectId: 'your-dataset-id'});

var yourBuffer = new Buffer([0x0000, 0x0001, 0x0002]);

/* or you can set this to a file's contents:
var yourBuffer = fs.readFileSync('/path/to/yourfile');
*/

dataset.save({
  key: dataset.key('YourKind'),
  data: {
    yourBlobProperty: yourBuffer
  }, function(err) {
  if (!err) {
    console.log('Just saved', key.path);
  }
});
```

**Comment by jgeewax** [comment]
Going to mark this as closed, but feel free to re-open if you think this is wrong. 

If you have an idea for how to improve the docs, feel free to open a PR. The examples for [`dataset.save`](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.25.1/datastore/dataset?method=save) have demos of the types we try to support:

```js
var key = dataset.key('Company');

dataset.save({
  key: key,
  data: {
    name: 'DonutShack', // strings
    rating: gcloud.datastore.int(8), // ints
    worth: gcloud.datastore.double(123456.78), // doubles
    numDonutsServed: 45, // detect number type (int or double)
    founded: new Date('Tue May 12 2015 15:30:00 GMT-0400 (EDT)'), // dates
    isStartup: true, // booleans
    donutEmoji: new Buffer('\uD83C\uDF69'), // buffers
    keywords: [ 'donut', 'coffee', 'yum' ] // lists of objects
  }
}, function(err) {});
```
