### ISSUE TITLE
Example of using GeoPt

### ISSUE THREAD

**Issue by bradabrams** [GoogleCloudPlatform/gcloud-node#972]
I can't figure out how to use GeoPt... is there an example I can look at?
https://cloud.google.com/appengine/docs/java/datastore/geosearch

**Comment by jgeewax** [comment]
I think GeoPt is client-side creation with a special "meaning" attached and not explicitly exposed via the JSON API. 

See https://github.com/GoogleCloudPlatform/gcloud-python/issues/1065#issuecomment-131845565 for more info.

The `meaning` field in the protobufs is not super well defined.

@stephenplusplus : Is there anywhere we use `meaning=9` ? 

@pcostell : Is there any chance we're making "meaning" a first-class citizen on the API for the next versions of the Cloud Datastore API?

**Comment by pcostell** [comment]
No we should not expose GeoPt using meaning. V1beta3 will have a separate
geopoint value that can be used.

We intentionally do not document meaning and you should not rely on it. We
make no guarantees about what the values actually refer to and may change,
remove, or add values in the future.

/cc @alfus

**Comment by bradabrams** [comment]
ok -- great, how can I find out when V1Beta3 is out so I can give it a try

..brad

**Comment by pcostell** [comment]
Hi Brad --
We are working on it now. Part of our new version is a completely new serving stack to make Cloud Datastore more reliable and have lower latencies. As a gcloud-node user you shouldn't have to worry about the new Datastore version -- gcloud will upgrade to the new version and you shouldn't see much change (except for a new minor version that includes GeoPt support).

The v1beta3 release will not include geosearch support (which is still in [Alpha in App Engine](https://cloud.google.com/appengine/docs/java/datastore/geosearch)). We are making sure we iron out the usage of geosearch in GAE first.

-Patrick

**Comment by stephenplusplus** [comment]
Using geo point values will be shown in our docs once v1beta3 is released. Until then, it sounds like we don't plan to support them, so I'm going to close the issue. Thanks for getting this conversation started!

**Comment by bradabrams** [comment]
when is v1beta3?

**Comment by pcostell** [comment]
Brad --

As I mentioned above we are working on it now. I'm hoping we'll be able to launch soon but I'm not able to give a more definite timeline.

-Patrick

**Comment by bradabrams** [comment]
ok -- I guess I just check back in a few weeks or months?
