### ISSUE TITLE
Error Response:[400] Invalid character in file name.

### ISSUE THREAD

**Issue by LeeKyungMoon** [GoogleCloudPlatform/gcloud-node#973]
When I try to deploy my app with the command : "gcloud preview app deploy app.yaml --promote"
I got an error below :
ERROR: (gcloud.preview.app.deploy) Error Response: [400] Invalid character in filename: node_modules/gcloud/node_modules/gce-images/node_modules/google-auto-auth/node_modules/google-auth-library/node_modules/jws/node_modules/base64url/node_modules/meow/node_modules/indent-string/node_modules/repeating/node_modules/is-finite/node_modules/number-is-nan/index.js Deleted [https://www.googleapis.com/compute/v1/projects/photozzlewithnodejs-1136/zones/us-central1-f/instances/gae-builder-vm-20151129t162546].

Anyone having the same error and the solution for this?

**Comment by stephenplusplus** [comment]
@LeeKyungMoon You might have some luck posting this over on StackOverflow: http://stackoverflow.com/questions/tagged/gcloud.

@jonparrott -- any ideas for this one?

**Comment by stephenplusplus** [comment]
Just realized you already posted on SO: http://stackoverflow.com/questions/33980536/google-app-engine-error-with-gcloud

**Comment by LeeKyungMoon** [comment]
How could you do that? ... it's not solved... how could you close this
because i posted on SO... It's not solved... how... I totally do not
understand

2015-12-01 1:56 GMT+09:00 Stephen Sawchuk <notifications@github.com>:

**Comment by stephenplusplus** [comment]
Sorry, I should have mentioned I closed it because it was not just asked on SO, but answered. Did you see it?:

> This is a known issue in the Cloud SDK. See [this tracking bug] (https://code.google.com/p/google-cloud-sdk/issues/detail?id=392) for a workaround and updates on status. – Zachary Newman [yesterday] (http://stackoverflow.com/questions/33980536/google-app-engine-error-with-gcloud#comment55725516_33980536)
