### ISSUE TITLE
Pub/Sub set timeout of pull()

### ISSUE THREAD

**Issue by mattraby** [GoogleCloudPlatform/gcloud-node#980]
It would be nice to be able to set the timeout of a pull(). Right now it can either ```returnImmediately=true``` or it will long poll for ~90sec. Is it possible to configure the pull to timeout after a specific amount of time? See http://stackoverflow.com/questions/33976227/google-pub-sub-how-to-set-read-timeout-on-pull

**Comment by stephenplusplus** [comment]
After reading the answer on the SO issue (thanks for linking that), it seems the broken connection from the server is effectively a forceful "timeout". So, I think what you're after from this library is a more convenient way to set a timeout on each pull's HTTP request. (Let me know if I'm misunderstanding)

I put together a PR that allows a timeout to be set on the Subscription object (#981):

```js
var subscription = pubsub.subscription('name', { timeout: 30000 });
```

**Comment by mattraby** [comment]
Thanks! Being able to set the request's timeout may be helpful. But now I'm not sure it solves the problem I'm seeing. The issue seems to be more with the pubsub service than the client implementation. Maybe you can confirm what I'm seeing. If you look at the UPDATE section from my sof question, it looks like pubsub will still try to deliver messages to the connection that has been forcefully timed out, at least up until the server side timeout occurs (~90sec). If the server side (pubsub) timeout is not configurable, then setting the request timeout may lead to undesirable results.

**Comment by stephenplusplus** [comment]
I was going from this answer: http://stackoverflow.com/a/33988327/776934

> Setting the request timeout as you have is the correct way to timeout the pull after 30 seconds.

The answerer then describes a scenario which may explain the behavior you're seeing. It looks like he's exactly the person to talk to for this kind of issue, so he'll definitely be more help than I will as far as the upstream API goes. Please continue the discussion with him, and then report back if the PR I put together is still a proper way to disconnect a pull.

**Comment by stephenplusplus** [comment]
Sorry, just caught this part from your update:

> What I would like to do is be able to send a timeout param in the pull request to tell subpub to send back a response after a 30000ms if no messages are published during that time.

That's definitely a feature request for the upstream folks to handle. The only thing we can do in our library is disconnect the pull request if nothing comes back in the desired wait time. If that *is* a proper way to break a pull request, I don't think exposing the timeout setting could hurt. But, it still wouldn't give the results you're looking for, where some type of response is guaranteed after a configurable timeout.

**Comment by mattraby** [comment]
Thanks for your help @stephenplusplus. Hopefully this feature is added to the pubsub service at some point.
