### ISSUE TITLE
cant subscribe with maxInProgress option

### ISSUE THREAD

**Issue by leibale** [GoogleCloudPlatform/gcloud-node#985]
it's return ApiError to callback
```javascript
Invalid JSON payload received. Unknown name "max_in_progress": Cannot find field.
```

**Comment by stephenplusplus** [comment]
Where is that field hiding? I'll find it unless @callmehiphop beats me to it.

**Comment by leibale** [comment]
https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/pubsub/subscription.js#L56

**Comment by callmehiphop** [comment]
I wasn't able to reproduce this locally - @leibale would you mind sharing some example code to help reproduce this error? I believe `maxInProgress` is a convenience option for the client only, so I'm a little confused on how it's getting sent to the upstream API.

**Comment by leibale** [comment]
when you create a subscription you can set the interval and stuff like this, but you can't set the maximum of messages your worker will work on.
at version 24 (I think) wee (I create a pull request) add option to set the 
`maxInProgress` and the subscription not pull more messages if your worker not call to message.ack or message.skip

I'm sorry for the English..
