### ISSUE TITLE
BigQuery return timestamp field as exponential

### ISSUE THREAD

**Issue by debopamsengupta** [GoogleCloudPlatform/gcloud-node#990]
![image](https://cloud.githubusercontent.com/assets/9649659/11584091/c6d1b634-9a9b-11e5-9339-3f7c57dd5397.png)
This is the result from the ```time``` field in the BigQuery dataset instead of some thing like this 

![image](https://cloud.githubusercontent.com/assets/9649659/11584125/1c8cdbb2-9a9c-11e5-9e09-ca6050b7d96a.png)

Is there something I'm missing ?

**Comment by stephenplusplus** [comment]
@debopamsengupta did you mean to close?

**Comment by debopamsengupta** [comment]
Well, found a workaround as the exponential can be converted into a Unix timestamp.
But it would be good to just receive the string from BigQuery

**Comment by stephenplusplus** [comment]
I agree! Which API call is the time field returned in?

**Comment by debopamsengupta** [comment]
https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.25.1/bigquery?method=query returns the time field

**Comment by stephenplusplus** [comment]
I can't find that property being returned in the raw API response (https://cloud.google.com/bigquery/docs/reference/v2/jobs/query)

Is this your own data? It looks like we could convert to a Date object if we see the matching schema type for a returned property is "TIMESTAMP".

**Comment by debopamsengupta** [comment]
![image](https://cloud.githubusercontent.com/assets/9649659/11590411/0737f8d0-9acb-11e5-8168-9ac804948076.png)
Well this is the schema for the table, and the schema type for the field ```time`` is ```TIMESTAMP```

**Comment by stephenplusplus** [comment]
Got it, thanks. Sorry for all the questions, just wanted to make sure I understood. I think we can sniff out when we are returning these types and convert them to the format that makes sense. Thanks for calling this out!

**Comment by debopamsengupta** [comment]
Thanks, no problem !

**Comment by jgeewax** [comment]
Hey guys, any chance we can continue the old behavior by passing a special parameter? That is, what if I really just want the raw data? Can I ask for raw (un-schema-parsed) results? /cc @callmehiphop

**Comment by stephenplusplus** [comment]
The raw data will still come through in the `apiResponse` parameter:

```js
table.query('SELECT * FROM ...', function(err, rows, nextQuery, apiResponse) {
  // apiResponse:
  {
    "schema": {
      "fields": [
        {
          "name": "url",
          "type": "STRING",
          "mode": "NULLABLE"
        }
      ]
    },
    "rows": [
      {
        "f": [
          {
            "v": "https://github.com/jfeaver/hireme"
          }
        ]
      }
    ]
  }
});
```

**Comment by jgeewax** [comment]
OK cool :)

Where do we document the full apiResponse object? Do we link back to the
BigQuery page that defines the schema of that object?

**Comment by stephenplusplus** [comment]
It's a bit of a click-hunt, but if you get to the [`bigQuery#query` docs](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.26.0/bigquery?method=query), the last link on the page ("Jobs: query API Documentation" under the "More information" section) takes you to https://cloud.google.com/bigquery/docs/reference/v2/jobs/query which shows the response body.

I'll open a new issue for making the `apiResponse` callback parameter linkable directly to the response body. For now, I made a small note in the release notes about the raw response.

**Comment by jgeewax** [comment]
Oh that's a great idea. Maybe all our apiResponse parameters could point to
the API page on cloud.google.com?

**Comment by stephenplusplus** [comment]
Yeah, I think that'd be awesome! Issue opened: #1007
