### ISSUE TITLE
Can't view the Storage docs

### ISSUE THREAD

**Issue by eknkc** [GoogleCloudPlatform/gcloud-node#994]
The documentation page does not list Storage as far as I can tell. Maybe I'm critically sleep deprived but I'm sure it was here before :)

![](http://d.ekin.io/14ib9+)

**Comment by stephenplusplus** [comment]
That's my bad. On it!

**Comment by stephenplusplus** [comment]
Put in the fix, now we just need the docs to build. That happens after about ~30 minutes when our tests have completed running. Thanks for catching this and reporting it!

**Comment by stephenplusplus** [comment]
Side question... are the sidenav links always non-alphabetically sorted for you?

**Comment by eknkc** [comment]
Thanks!

Yeah they are. Never realised it before though but I get random orders.

**Comment by eknkc** [comment]
It's random on Safari btw. Seems to be in alphabetical order on Chrome.

**Comment by stephenplusplus** [comment]
Very interesting. Made a new [bug](#995) to track it.
