### ISSUE TITLE
pubsub: reused subscriptions should not rely on API response for data

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#997]
> at line `471` in `pubsub/index.js` you should use `resp.name || subName` (if the status is 409 and `reuseExisting` is true i got `The name of a subscription is required.` error).
> \- https://github.com/GoogleCloudPlatform/gcloud-node/pull/992#issuecomment-162304897

Reported by @leibale.

**Comment by leibale** [comment]
??

**Comment by stephenplusplus** [comment]
@leibale This was fixed and merged in #999.

**Comment by leibale** [comment]
sorry, i didn't see it the phone.
thanks :)
